### ISSUE TITLE
Make nofollow (and noopener) available via checkbox on link modal

### ISSUE THREAD

**Issue by mikethehud** [craftcms/redactor#101]
# What
Allow activating `nofollow` and `noopener` for specific links within a redactor field, similar to how `linkNewTab` works with the target attribute (checkbox).

# Why
Within a redactor field, sometimes we want only some links to be marked with `nofollow` or `noopener` while others should not have those refs.

**Comment by andris-sevcenko** [comment]
That's Redactor's native functionality, not something Craft does. Craft _can_ override that modal and provide it's own, but that's a significant undertaking.

**Comment by jonlongnecker** [comment]
This is a sorely needed bit of functionality for anyone using affiliate links. I've been waiting a couple of years for this to get sorted out, but no luck so far.

Currently Redactor only has the option to make ALL links nofollow or none of them. I definitely don't want internal links set to nofollow so this option doesn't work.

> When set to true, all links inside of Redactor will get a nofollow attribute. This attribute restricts search engines indexing for these links.

On their end, it seems like the format/idea is already there and adding this option would be fairly easy. But no idea how to request this feature to the people that make Redactor. Is this something Craft can request for us?

**Comment by kringkaste** [comment]
FYI: We just released an plugin to add nofollow to the Redactor's link edit modal:

https://github.com/codemonauts/craft-redactor-nofollow

If you have any feedback, let me know.

**Comment by jonlongnecker** [comment]
@kringkaste Excellent - I'll take it for a spin soon and let you know.
