### ISSUE TITLE
Scroll performance (memory leak?) in Chrome – but only for one locale?!

### ISSUE THREAD

**Issue by mattandrews** [craftcms/redactor#105]
I've seen this for a while now using Craft Pro 3.0.25 and Redactor 2.1.6 (in Chrome). When I select a specific Site/locale and scroll around an entry, the browser begins to feel more and more sluggish and uses more and memory until scrolling/performance is degraded.

I ran the same test on a piece of content: loading the English version and scrolling around the Redactor instance, then loading the Welsh version (my other site) and doing the same thing. Here's how the Chrome performance log looks:

## English:
![screenshot 2018-12-04 13 14 33](https://user-images.githubusercontent.com/394376/49444411-063cca80-f7c7-11e8-854b-396d2a5195cf.png)

## Welsh:
![screenshot 2018-12-04 13 14 26](https://user-images.githubusercontent.com/394376/49444418-0a68e800-f7c7-11e8-9fa1-caa848449de8.png)

You can see that there are large blocks of "Scroll Update" events on the (broken) Welsh page, which corresponds with a large amount of time in Bottom-Up stack showing "Evaluate Script" which doesn't appear at all in the English one.

This happens in Incognito mode too so I'm confident it isn't a browser plugin on my end. The content in question is a few hundred words of text, no images or embeds etc. 

Has anybody else seen this, and can anyone reproduce it?

**Comment by mattandrews** [comment]
Update: I just created a fresh install of Craft and configured it like so:

- Made two sites (one English, one French)
- Made a "Blog" section
- Made a "Blogpost" Redactor field with Standard config and attached this to the section
- Added a new Blog entry in English, scrolling is fine
- Edited that entry in French: as soon as I click and scroll the Redactor instance, the memory leak kicks in.

**Comment by andris-sevcenko** [comment]
Just released 2.3.2 which also includes a newer Redactor version. If you can still reproduce this, let me know.
