### ISSUE TITLE
Redactor leaves extra markup in HTML source sometimes

### ISSUE THREAD

**Issue by guyinpv** [craftcms/redactor#106]
I'm on Craft 3.0.33 with Redactor plugin 2.1.6.

I don't have any other Redactor extension plugins installed. 

I DO have a custom config which is used to changed the buttons, and I use two plugins "fullscreen" and "video". I have some "removeEmpty" tags, "allowedTags", etc.

The problem is that sometimes with images or videos, when I switch between HTML and normal views, it will dump some extra code into the source which ends up staying there. It's not automatically removed again.

The behavior is sporadic, most of the time this does not happen. I'd say 1 out of 10 times switching to HTML mode the below markup gets added into source.

Here is a sample of code that was saved when doing a video embed:

`<span class="redactor-selection-marker">﻿</span><span class="redactor-selection-marker">﻿</span>`

I have to manually delete this stuff when I see it show up.

I can't figure out how to reproduce this, it just seems random.

**Comment by andris-sevcenko** [comment]
That sounds like a Redactor bug, not a bug with this plugin.

If you update to 2.1.7, which has a later Redactor version, does this still happen?
