### ISSUE TITLE
Redactor not using .json button within matrix field

### ISSUE THREAD

**Issue by mofman** [craftcms/redactor#107]
Here is my config

`{
  "buttons": ["html", "formatting", "bold", "italic", "unorderedlist", "orderedlist", "link", "image", "video"],
  "plugins": ["fullscreen", "video"],
  "toolbarFixed": true,
  "linkNewTab": true
}
`

This works fine in a normal field but when it is used from within a matrix it loads a very basic version of redactor and ignores the buttons ive add. i've been sure to select the right config from the field settings

![screen shot 2018-12-13 at 16 49 39](https://user-images.githubusercontent.com/3038169/49954117-a39aab80-fef7-11e8-95a1-eef9e04638fd.png)
- when used in matrix

![screen shot 2018-12-13 at 16 49 49](https://user-images.githubusercontent.com/3038169/49954118-a39aab80-fef7-11e8-9238-3e53109ce18a.png)
- when used as single field

**Comment by andris-sevcenko** [comment]
I am not able to reproduce this. What plugin version are you using?

**Comment by mofman** [comment]
Redactor 2.1.7 
Craft CMS 3.0.36

Would you like me to send you a copy of database?

**Comment by andris-sevcenko** [comment]
That and a zipped up `config/redactor` folder of would be awesome! The email to use would be support@craftcms.com.

**Comment by mofman** [comment]
Hey Andris

Appologies, I've just had another look at this, its quite a large Matrix field and I must have been testing the wrong field after switching the config over. 

Can I ask when you use the 'default' option does it use Simple.

**Comment by andris-sevcenko** [comment]
@mofman it just uses whatever Redactor itself thinks is the default setting. It does not use any of the provided files.

**Comment by mofman** [comment]
Ah I think that is what also threw me then because I was changing both Simple and Standard and not seeing any change. Thanka again
