### ISSUE TITLE
Redactor link to an entry - selection of channels sections is missing. 

### ISSUE THREAD

**Issue by vit-ruller** [craftcms/redactor#109]
### Description
Redactor link to an entry - selection of channels, sections is missing. It displays just single pages.

<img width="1079" alt="screenshot 2019-01-08 at 11 33 19" src="https://user-images.githubusercontent.com/5659112/50825503-7c3dcf80-1339-11e9-8d9e-0555760ff6aa.png">

### Additional info

- Craft version: Craft Pro 3.1.0-beta.5.1
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Redactor 2.1.7

**Comment by andris-sevcenko** [comment]
This will be resolved once a Redactor version compatible with Craft 3.1 is released, which will happen once Craft 3.1 is released.

**Comment by andris-sevcenko** [comment]
@Rias500 should be today.

**Comment by andris-sevcenko** [comment]
This should be fixed with the release of 2.2 for this plugin,

**Comment by jessie-gilligan** [comment]
> This should be fixed with the release of 2.2 for this plugin,

Just to confirm, this release is not out yet, correct? I have a client looking for a work around, which for now I will have them copy and paste the full URL, but advise them a fix is coming. Does that sound correct @andris-sevcenko? Thanks in advance!

**Comment by angrybrad** [comment]
@jessie-gilligan The plugin is up to 2.3.1 now, so it should be resolved: https://github.com/craftcms/redactor/releases

**Comment by jessie-gilligan** [comment]
@angrybrad yes! I ran a composer update and didn't get the newest version... however, I've gone back to `composer require ...` and I'm all up to date. Thanks again!

**Comment by lucasvallenet** [comment]
Hi,
I have the same issue with Redactor 2.6.1 and Craft 3.4.22.1
I have a multi-site setup with multiple sections and I can only see one.

**Comment by riccardolardi** [comment]
Is this still a bug? I can only see single entries when I try to create links.

**Comment by stillhartkonzept** [comment]
We still have this bug too. We have a multilingual setup.

**Comment by brianjhanson** [comment]
@stillhartkonzept what version of Craft & Redactor are you on? I tried to reproduce with Craft 3.7.62 and Redactor 2.10.11 but wasn't able to.
