### ISSUE TITLE
Problems by saving

### ISSUE THREAD

**Issue by wedot** [craftcms/redactor#115]
I have the problem that allways when i save a entry the new text content will not be saved into the db. This only happen with the content in a redactor field. if i use a regular plain text field the text will be saved to the db. Du you have a idea why?

**Comment by andris-sevcenko** [comment]
I am not able to reproduce. Can you get in touch via support@craftcms.com and reference this issue?

**Comment by jesuismaxime** [comment]
@wedot have you some parentheses or similar characters in your redactor content ? I experience the same issue, when I remove those `()`, the entry save correctly. I'm still trying to find which HtmlPurifier settings is in cause.
