### ISSUE TITLE
Limiter plugin not showing live limit updates in Craft 3

### ISSUE THREAD

**Issue by mikeebee** [craftcms/redactor#116]
Hello! I have successfully added the [Limiter](https://imperavi.com/redactor/plugins/limiter/) plugin to Craft by adding this to my `config/redactor/Standard.json` file.

```
{
  ...
  "plugins": ["fullscreen", "limiter"],
  "limiter": 200
}
```

It is working, the user stops being able to add any more content after 200 characters but there is no feedback in the UI like shown on the plugin page. I've had a dig around and saw some mention of needing to include some JS but that seems to be from Craft 2.

Any ideas what I'm missing?

Many thanks!
Mike

`Craft CMS 3.0.37`
`Redactor 2.1.7`

**Comment by andris-sevcenko** [comment]
What the demo code on that page fails to show, is that the redactor instance there also has the [counter](https://imperavi.com/redactor/plugins/counter/) plugin added to the configuration.
