### ISSUE TITLE
Setting unknown property: craft\redactor\Field::availableAssetSources upon installation

### ISSUE THREAD

**Issue by realflash** [craftcms/redactor#119]
I installed the Redactor plugin in Craft 3 from the store inside a working installation. Upon completion the CP page reloaded with this error. The site has been upgraded from Craft 2, and there are entries with the Redactor field type. I'm an admin adopting a site and so just starting out with Craft. I really don't know where to start with this. I'd appreciate any assistance.

I'm guessing that in enabling the plugin Craft is now trying to render the redactor fields where it wasn't before, and something about those fields is broken. I've checked this site for upgrade instructions to see if there's something I might need to do but haven't found any. I see that some entries in my DB have availableAssetSource as a column.

`yii\base\UnknownPropertyException: Setting unknown property: craft\redactor\Field::availableAssetSources in craft3/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 craft3/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('availableAssetS...', '*')
#1 craft3/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\redactor\Field), Array)
#2 craft3/vendor/craftcms/cms/src/helpers/Component.php(80): yii\base\BaseObject->__construct(Array)
#3 craft3/vendor/craftcms/cms/src/services/Fields.php(548): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#4 craft3/vendor/craftcms/cms/src/services/Fields.php(573): craft\services\Fields->createField(Array)
#5 craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1536): craft\services\Fields->getAllFields()
#6 craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1073): craft\elements\db\ElementQuery->customFields()
#7 craft3/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#8 craft3/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#9 craft3/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Query->createCommand(Object(craft\db\Connection))
#10 craft3/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#11 craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1215): craft\db\Query->one(NULL)
#12 craft3/vendor/craftcms/cms/src/elements/User.php(367): craft\elements\db\ElementQuery->one()
#13 craft3/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('228')
#14 craft3/vendor/craftcms/cms/src/web/User.php(474): yii\web\User->renewAuthStatus()
#15 craft3/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#16 craft3/vendor/yiisoft/yii2/web/User.php(360): yii\web\User->getIdentity()
#17 craft3/vendor/craftcms/cms/src/web/User.php(189): yii\web\User->getIsGuest()
#18 craft3/vendor/craftcms/cms/src/web/Application.php(259): craft\web\User->getIsGuest()
#19 craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 craft3/web/index.php(21): yii\base\Application->run()
#21 {main}`

**Comment by andris-sevcenko** [comment]
Is it possible to send the dump of your `craft_migrations` DB table over to support@craftcms.com, referencing this issue?

**Comment by realflash** [comment]
Thanks, sent

**Comment by andris-sevcenko** [comment]
Just released 2.3.2 which also improves/fixes some migrations. This should be fixed.
