### ISSUE TITLE
Fullscreen layout partially hidden under control panel menu

### ISSUE THREAD

**Issue by designkarma** [craftcms/redactor#120]
![staticshot_07-02-2019_21-45-00](https://user-images.githubusercontent.com/3372239/52445065-f7a1c500-2b21-11e9-92cd-cffa63c2e204.png)
As shown in screenshot, when you hit the fullscreen button Redactor tucks under the Craft menu. Chrome Version 71.0.3578.98 (Official Build) (64-bit).

**Comment by andris-sevcenko** [comment]
Unable to reproduce in Chrome 72.0.3626.96 (Official Build) (64-bit)

If you still can reproduce this, are you using any custom CSS plugins or something like that? What Craft/Redactor versions are you using?

**Comment by designkarma** [comment]
Hey Andris. It’s Craft CMS 3.1.8 and Redactor 2.3.1. Happens inside Matrix if that matters. Want me to swing you a login?

I wonder if it is a CSS thing like you say. Maybe a Craft update didn’t take? I notice too that the entries list looks wonky, but only for one section. See: https://www.dropbox.com/s/y6tsetr89tz1cjl/StaticShot_11-02-2019_13-20-58.png?dl=0

Ian

DESIGNKARMA
Building a better web since 1997

designkarma.co.uk
@designkarma

**Comment by andris-sevcenko** [comment]
Alright, I'll bite. Send the details over to support@craftcms.com and reference this issue, thanks!
