### ISSUE TITLE
Redactor Image button Missing In Toolbar

### ISSUE THREAD

**Issue by hollydo** [craftcms/redactor#122]
I've upgraded redactor to the latest version 2.3.1 and my craft cms is at version 3.1.12. The image button on the toolbar is missing. I have seen and used the image button on the toolbar before. Now, it only shows up if I downgrade redactor to version 2.1.0. 

![screen shot 2019-02-15 at 5 34 27 pm](https://user-images.githubusercontent.com/15054682/52892616-e4f24600-3148-11e9-89b2-3c803d5e58d5.png)

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this. Can you share your `craft_fields` table dump and redactor config over email to support@craftcms.com and reference this issue?

**Comment by andris-sevcenko** [comment]
This was an invalid config setting issue.
