### ISSUE TITLE
Redactor config ignores pasteImages, pasteBlockTags, ... 

### ISSUE THREAD

**Issue by glenndebacker** [craftcms/redactor#123]
Options like pasteImages, pasteBlockTags seems to be completely ignored. The only thing that seems to be working is pastePlainText. (https://imperavi.com/redactor/docs/settings/paste/)

This is my custom redactor config

```json
{
  "buttons": ["bold", "italic"],
  "pasteImages": false,
  "pasteBlockTags": ["blockquote", "p"]
}
```

Is there a reason why that is that I'm missing ?

**Comment by mightyfineyall** [comment]
@glenndebacker was having the same issue, but it appears that you need "pastePlainText" as the first option before the others will work. it's some kind of prerequisite. My config is as follows, and won't let you paste images:

```
{
  "buttons": ["formatting", "alignment", "bold", "italic", "unorderedlist", "orderedlist", "link", "file"],
  "formatting": ["p", "blockquote", "h3", "h4", "h5", "h6"],
  "plugins": ["fullscreen", "alignment", "counter"],
  "linkNewTab": true,
  "toolbarFixed": true,
  "pastePlainText": true,
  "pasteImages": false
}
```

**Comment by andris-sevcenko** [comment]
Closing this, since @mightyfineyall has provided a solution and it seems to be a redactor bug.
