### ISSUE TITLE
Non-breaking space

### ISSUE THREAD

**Issue by sandissauka** [craftcms/redactor#126]
We use to use Ctrl + Shift + Space (on a PC) to make a non-breaking space. Now that doesn't work. Works in Words still. Could this be affected by some recent updates?

**Comment by andris-sevcenko** [comment]
Can you reproduce this on https://imperavi.com/redactor/?

**Comment by sandissauka** [comment]
It works on your machine! 😆 We have Redactor 2.3.2 update pending. Should it resolve the issue?

**Comment by andris-sevcenko** [comment]
So if it works there, then updating to 2.3.2 should fix it, yes.

**Comment by sandissauka** [comment]
@andris-sevcenko, it doesn't work even after update latest Chrome, not so latest Chrome, latest Firefox (all PC). Maybe there are some settings we're missing?

**Comment by angrybrad** [comment]
@sandissauka weird... just tested on latest Chrome on Win10 and a Ctrl+Shift+Space adds a nbsp for me.

![annotation 2019-03-04 101307](https://user-images.githubusercontent.com/61869/53753481-38150a00-3e66-11e9-9663-2eced02af11e.jpg)

**Comment by sandissauka** [comment]
@angrybrad Doesn’t work on my machine. Do we possibly miss something in configuration? We haven’t changed anything in it for a year, just before the weekend we updated. A while ago client suddenly noticed that it doesn’t work.

**Comment by angrybrad** [comment]
@sandissauka try clearing your browser's cache? What version of Windows?

**Comment by sandissauka** [comment]
@angrybrad cache was cleared. I’ll
check on Win version tomorrow. Thanks.

**Comment by sandissauka** [comment]
@angrybrad Windows 10 Pro Version 1809 and Windows 10 Pro Version 1607.

Also we've got our hand on a PC, so will test some more on our end too.

**Comment by andris-sevcenko** [comment]
If you do a fresh install, can you also reproduce that on the fresh install with no config modifications? That would be a good indicator of the issue being on your end, too.

**Comment by sandissauka** [comment]
@andris-sevcenko that hurts 😢

**Comment by andris-sevcenko** [comment]
Redactor has been since updated to 3.3.0. Can you check if this is still an issue for you? I'll reopen the issue, if that's the case.

**Comment by sandissauka** [comment]
Sure thing @andris-sevcenko 👍🏼

**Comment by sandissauka** [comment]
@andris-sevcenko, we have updated everything now, including:

- Redactor: 1.0.24
- Redirect plugin for Craft 3: 2.0.7

I hit option+space, check <> (HTML editor). I see freshly baken "&nbsp;", but after the save, it disappears.

What might cause it?

**Comment by andris-sevcenko** [comment]
Redactor 1.0.24 does not sound entirely right since the latest is 2.5.0.

Either way, there's an "advanced" section of the field settings that has a "Replace non-breaking spaces with regular spaces" setting, can you check that?

<img width="348" alt="Screen Shot 2020-02-03 at 14 28 16" src="https://user-images.githubusercontent.com/1891118/73653241-6eb85d80-4691-11ea-84fa-a0d2b84a9401.png">

**Comment by sandissauka** [comment]
@andris-sevcenko thanks with the changes in the settings it works now. Much respect! ✌🏼
