### ISSUE TITLE
Lists can only generate in top level element

### ISSUE THREAD

**Issue by watchwood** [craftcms/redactor#128]
I have a couple custom redactor plugins to add tabs/accordions to my site's Redactor editor.  However, I can't add lists inside of these elements as the List plugin appears to require you be at the top level to function.  Could this be adjusted, perhaps with a config option?

Thanks.

**Comment by andris-sevcenko** [comment]
Redactor has been since to 3.3.0. Can you check if this is still an issue for you? I'll reopen the issue, if that's the case.
