### ISSUE TITLE
[FR] Conditionally allow html button by permission level

### ISSUE THREAD

**Issue by timkelty** [craftcms/redactor#129]
This was something from back in the EE/Wygwam days we miss (https://github.com/pixelandtonic/wygwam_super_admin_source).

It allowed html source editing ONLY for admins.

Implemented in Craft, I would say adding a new `redactor:viewHtml` user permission that toggled this would be ideal.

**Comment by andris-sevcenko** [comment]
Eh, I can see that implemented maybe sometime, but I wouldn't want to shove it under permissions as that's misleading.

Permissions allow or deny something, but this is purely a cosmetic thing. A user without this "permission" could just open up inspector and edit the HTML source, anyway, so calling them permissions and using the permission system for that would be misleading.

**Comment by timkelty** [comment]
@andris-sevcenko fair enough. Setting on the field then?

**Comment by andris-sevcenko** [comment]
Sounds like a good idea to me.

**Comment by lindseydiloreto** [comment]
Just stumbled across this old feature request... it sounds like a good idea to me too!

In the meantime, you could probably do a quick workaround using CP CSS and CP Body Classes.

**Comment by andris-sevcenko** [comment]
@timkelty hypothetically, how would that setting be called? "Only admins can view source"?

**Comment by timkelty** [comment]
@andris-sevcenko that sounds good to me…

Another option might be:

"Limit (HTML) source to admins"

**Comment by andris-sevcenko** [comment]
Added this for 2.7

**Comment by brandonkelly** [comment]
Redactor 2.7.0 is out now with this feature!

**Comment by jsunsawyer** [comment]
I just ran into an issue where this change required me to update a bunch of fields on an old site where users were previously able to access the HTML view. https://github.com/craftcms/redactor/issues/257

I find these field specific settings to be very tedious when you always want them to be set opposite of the default (false in this case). Any chance we could have an option to define whether or not users have this capability globally?
