### ISSUE TITLE
Redactor Video plugin not functioning after install.

### ISSUE THREAD

**Issue by Bshally** [craftcms/redactor#13]
- Using Craft CMS 3.0.0-RC12
- Hosted on Arcustech
- Using Multisite functionality
- Installed/uninstalled multiple times using the documentation here and the plugin store. Hasn't resolved.

Copy and pasting a YouTube link in the into the box brought up after clicking the video icon results in a preview of the video being shown in the field box. Saving then checking the rich text field again shows an empty field. Checking the html in the field shows `<div class="video-container"></div>`.

Copy/paste the full YT embed code into the video prompt shows the following :
![screen shot 2018-02-26 at 4 15 30 pm](https://user-images.githubusercontent.com/3440317/36695825-64c1c9aa-1b10-11e8-83e5-af1f74f605b8.png)
Checking the html shows(I removed my vid ID) : 
```
<iframe width="560" height="315" src="&lt;div class=" video-container"="">&amp;amp;lt;iframe style="width: 500px; height: 281px;" src="//www.youtube.com/embed/MYvideoID" frameborder="0" allowfullscreen&amp;amp;gt;</iframe>
<p>;controls=0&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen&gt;</p><p></p>
```
`path/to/project/config/redactor` only contains `GridTitle.json` `Simple.json` and `Standard.json`. Not seeing any redactor plugin directory or files.

Not sure if I just messed up the install, or if there is a bug here. Any help would be appreciated.

**Comment by angrybrad** [comment]
My guess is you're running into HTML Purifier "cleaning" the iframe input as controlled by the "Clean Up HTML" and "Purify HTML" settings mentioned in the question here: https://craftcms.stackexchange.com/questions/15291/youtube-video-embeds-in-rich-text-field-not-saving

Or if that's not the case, you're bumping into one of the things in the answer: https://craftcms.stackexchange.com/a/15292/57
