### ISSUE TITLE
Option to add rel="nofollow" attribute to links

### ISSUE THREAD

**Issue by jonlongnecker** [craftcms/redactor#135]
Related to #101 but realized it was closed after I commented.

Currently Redactor offers an option to open links in a new tab via a checkbox. I have a site with hundreds of Amazon affiliate links and best practice is to ad a `rel="nofollow"` to those. But they are inserted organically in the body content along with other links I want to be crawled (especially internal links)

Redactor's native option here is to `nofollow` all the links inside the field which isn't helpful: 

> When set to true, all links inside of Redactor will get a nofollow attribute. This attribute restricts search engines indexing for these links.

It seems like the UI convention and basic format is already in place to add a `nofollow` functionality to a link, but not sure what's possible if the core of Redactor doesn't have the functionality yet. 

Any ideas as to how to make this work?
![nofollow](https://user-images.githubusercontent.com/2390/56308891-3729f600-60fd-11e9-9d6d-0b913e975750.jpg)

**Comment by lpbouvier** [comment]
+1 with @jonlongnecker, this would be very useful!

**Comment by kringkaste** [comment]
FYI: We just released an plugin to add nofollow to the Redactor's link edit modal:

https://github.com/codemonauts/craft-redactor-nofollow

If you have any feedback, let me know.

**Comment by andris-sevcenko** [comment]
Closing this as @kringkaste has provided a solution for this. (Thank you, @kringkaste!!)
