### ISSUE TITLE
File Linking Issue

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/redactor#136]
Below is a video from the RedActor 2.3.2 Craft CMS plugin (v3.1.23):

http://shared.bl.ms/3U80cO

It shows two RedActor fields. 

The one on the left is from the demo found on Imperavi's website (https://imperavi.com/redactor/docs/settings/link/).

The one on the right is from Craft 3.1.23.

As you'll see, the Craft implementation has an issue whereby, if you have a couple of links next to each other, the File button wipes the "closest" link when you go to add the second link.

This doesn't seem to happen on the stock Imperavi version.

**Comment by andris-sevcenko** [comment]
Might be that when fixing https://github.com/craftcms/redactor/commit/0b8474928f283ba9d77ffc94e79562ed9c49b092 I should have taken a look here, too.

**Comment by bliswebagency** [comment]
Thanks for taking a look at this one.

I've updated to the latest version (2.3.3.1) but there still seems to be a problem.

Video: http://shared.bl.ms/xQn9RN

You'll notice it's not doing the same thing as it was but it's still not quite right either.

**Comment by andris-sevcenko** [comment]
Redactor has been since updated to 3.3.0. Can you check if this is still an issue for you? I'll reopen the issue if that's the case.
