### ISSUE TITLE
Issues saving entries with line breaks

### ISSUE THREAD

**Issue by diluno** [craftcms/redactor#137]
I'm having some trouble with entries not being saved, especially when inserting line breaks with Ctrl+Enter.
It says "Entry saved", but reverts to the old state.

![Screen Recording 2019-04-18 at 13 15 33](https://user-images.githubusercontent.com/2156626/56357630-8abf4100-61dc-11e9-97b3-d82d1f006292.gif)

**Comment by andris-sevcenko** [comment]
What plugins do you have installed? Also, what are the Redactor plugin and Craft versions?

**Comment by diluno** [comment]
Aside from the Redactor Plugin I only have the Element API Plugin.
Redactor is on 2.3.2 and Craft is on 3.1.23.

**Comment by andris-sevcenko** [comment]
@diluno any chance to get access to the site where you see this happening? If so, can you email the control panel access to support@craftcms.com?

**Comment by diluno** [comment]
Done. Thanks!

**Comment by andris-sevcenko** [comment]
This ended up being a Redactor bug, where Redactor would break if you were any HTML tags which were not "supported" by any buttons in the toolbar. To work around this, just make sure that, for example, if the field contains bolded text, there is a `bold` button in the toolbar.

**Comment by diluno** [comment]
Oh wow, I never would have guessed that. Thank you so much for your help!

**Comment by andris-sevcenko** [comment]
Redactor has been since updated to 3.3.0 which appears to have fixed this permanently.
