### ISSUE TITLE
Can't link to assets?

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/redactor#138]
In Craft 3.1, we are missing the option to link to an asset?

We can link to entries, categories and URL's, but not to assets anymore. We did add `"file"` to our Redactor config files, but this doesn't seem to work anymore.

We are using the newest Craft version (3.1.24) and the newest Redactor plugin (2.3.2)

Anyone else with this issue?

**Comment by andris-sevcenko** [comment]
You have to add the `file` button to your config file and then use the `File` button in redactor, not the `Link` button.

**Comment by thijskaspers** [comment]
Aww man, thanks! We completely overlooked that button as it used to be part of the "link" button.

**Comment by jamiematrix** [comment]
Was the "Link to asset" option added back in at some point?

We have a site using 2.4.0 that doesn't have the "link to asset" option in the "Link" menu, and a site using 2.8.5 that has got "Link to asset".

**Comment by andris-sevcenko** [comment]
@jamiematrix 2.7.0 was a pretty big release. One of the changes including also adding the `Link to Asset` option.
