### ISSUE TITLE
Setting unknown property: craft\redactor\Field::configFile

### ISSUE THREAD

**Issue by Tam** [craftcms/redactor#140]
Getting `Setting unknown property: craft\redactor\Field::configFile` after upgrading from `2.3.2` to `2.3.3.1`.

Seems to be caused by the field config having a `configFile` where it should be `redactorConfig`. The site is a recent upgrade from Craft 2 and was working prior to the update.

Fixed by manually replacing `configFile` with `redactorConfig` in field settings column in the database.

**Comment by Tam** [comment]
Also have to manually update project config with same fix.

**Comment by andris-sevcenko** [comment]
Can you send over a copy of your `storage/config-backups` folder over to support@craftcms.com and reference this issue?

**Comment by Tam** [comment]
@andris-sevcenko That's sent

**Comment by brandonkelly** [comment]
We just released Redactor 2.3.3.2 with a fix for this.
