### ISSUE TITLE
formattingAdd doesn't apply to text

### ISSUE THREAD

**Issue by harispepic** [craftcms/redactor#141]
I have been trying to add some formatting specific to my website by using the "formattingAdd" option, as documented here: https://imperavi.com/redactor/docs/settings/formatting/#s-formattingadd 

This is my .json file:

> {
  "buttons": ["html", "formatting", "bold", "italic", "deleted", "lists", "link", "email", "file", "image", "sup", "sub"],
  "plugins": ["fullscreen"],
  "formatting": ["p", "blockquote", "pre", "h2", "h3", "h4", "h5"],
  "formattingAdd": {
    "green-title-1": {
      "title": "Green header 1",
      "api": "module.block.format",
      "args": ["p", "class", "coriandr-green-text"]
    }
  },
  "pastePlainText": true,
  "pasteInlineTags": ["b", "u", "em", "sup", "sub"],
  "pasteBlockTags": ["h2", "h3", "h4", "h5", "h6", "ul", "ol", "li"],
  "toolbarFixed": true,
  "linkNewTab": true
}

Can you tell me what wrong is?

**Comment by andris-sevcenko** [comment]
Sorry for the extremely late response to this.

You're defining `args` as an array, while it should be a hash like this:
```json
 "formattingAdd": {
    "green-title-1": {
      "title": "Green header 1",
      "api": "module.block.format",
      "args": {"tag" : "p", "class" : "coriandr-green-text"}
    }
  }
```
