### ISSUE TITLE
Presence of the words "drop" and "table" in a sentence causes 403 error.

### ISSUE THREAD

**Issue by zacharybrady** [craftcms/redactor#143]
**Craft Version:** 3.1.28
**Redactor Version:** 2.4.0

> Drop resistance test only applies to fans that are portable, i.e. pedestal and table fans.

When typing out this sentence in a Redactor editor, as soon as the word "table" is entered a message in a red box saying "An Unknown Error Has Occurred" appears and a 403 "Permission Denied" error appears when I attempt to save the entry.

I have entered this sentence into different field types to make see if it was an issue beyond Redactor but only saw the issue with the Redactor field type.

I see why they would trigger a "403" but the level of aggressiveness is a little much.

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this on Craft 3.1.28 and Redactor 2.3.3.2, as there's no 2.4 version of the Redactor plugin.

There might be something in your log files, though, that would give us more information about what's happening here.

**Comment by angrybrad** [comment]
This will be because you've got something like Suhosin or mod_security installed on your server and one of their security rules is tripping up the POST request with that content.  You'll need to find the offending rule and modify/disable it.
