### ISSUE TITLE
HTML Purifier clears Redactor variables

### ISSUE THREAD

**Issue by Tam** [craftcms/redactor#147]
The HTML purifier clears all redactor [variables](https://imperavi.com/redactor/plugins/variable/) when the field is saved. Ideally it would make an allowance for variables, while purifing everthing else.

**Comment by andris-sevcenko** [comment]
Okay, so the trouble with HTML Purifier config setting here was twofold:

1) You can't just say "Okay, _also_ allow these attributes", you have to give the entire list. Which is tedious, to say the least.
2) Even if you gave HTML Purifier the whole list, there was this whole ordeal of "As far as I'm concerned, an attribute like that does not exist and will never be allowed".

So, the cleanest solution here was to figure out a way how determined individuals could actually modify what HTML Purifier considers valid attributes.

So, this commit slated for the next (probably 2.6) release adds the event for this and the code example in the even documentation is actually for your use case.

To get the fix early, change your `craftcms/redactor` requirement in composer.json to:

```json
"require": {
  "craftcms/redactor": "dev-v2#d3e1f6cb9e9de20f515be8505ce264c341d99aa2 as 2.5.0",
  "...": "..."
}
```

Then run `composer update`.

You will still have to roll a custom module or plugin that attaches to the event, of course.
