### ISSUE TITLE
Redactor clears inlined styles on save

### ISSUE THREAD

**Issue by Manzanit0** [craftcms/redactor#149]
Basically, we added the following content to a Redactor field in `code` mode, the one noted with the `< >` button:

```html
<h3 style=“color:#400099”><strong>Hello world!</strong></h3>
```
But upon save it's changed to:

```html
<h3><strong>Hello world!</strong></h3>
```

Basically stripping all inlined styles out of the HTML.

We're currently using:

- PHP 7.1.27
- Craft Pro 3.1.30
- Redactor 2.3.3.2

Any insight into why is greatly appreciated! Thanks!

**Comment by andris-sevcenko** [comment]
As of 2.3.3 there's a setting for that on Redactor fields under `Advanced` - "Remove inline styles".

**Comment by brandondeweese** [comment]
Yea, still removes inline styles regardless.

**Comment by brandondeweese** [comment]
https://user-images.githubusercontent.com/18017918/169583278-8fbfeaa1-d4ec-4444-9b98-3e32e04e8526.mov

**Comment by rossnorthrup** [comment]
> Screen.Recording.2022-05-20.at.10.34.47.AM.mov

I'm experiencing something like this as well. Were you able to find a solution?
I thought for sure it was going to be the checkbox in the settings > fields, but it doesn't seem to matter either way.

**Comment by tomascordero** [comment]
> > Screen.Recording.2022-05-20.at.10.34.47.AM.mov
> 
> I'm experiencing something like this as well. Were you able to find a solution? I thought for sure it was going to be the checkbox in the settings > fields, but it doesn't seem to matter either way.

I was dealing with this myself, when I unchecked `Purify HTML` it seems to work now. My use case doesnt matter if the HTML is purified or not however if yours does you might be able to use a custom purify json file.
