### ISSUE TITLE
Missing image and video buttons

### ISSUE THREAD

**Issue by larahilal** [craftcms/redactor#150]
I can't see the image and video buttons, although the are listed in the config standard.json file as such:

"buttons": ["formatting", "bold", "italic", "unorderedlist", "orderedlist", "link", "image", "video"],
  "plugins": ["fullscreen", "video", "table"],
  "linkNewTab": true,
  "toolbarFixed": true

I also added the "table" to plugin, but made no difference.
 From the filed setting in the Craft 3 admin panel, I can only select "default" as "redactor config".

Any suggestions?

**Comment by andris-sevcenko** [comment]
What ended up being the issue?
