### ISSUE TITLE
Can I link to a tag from Redactor?

### ISSUE THREAD

**Issue by nitech** [craftcms/redactor#155]
I have tags that I use to relate entries to each other. When typing inside a Redactor field I would like to be able to write something like #engineering and have that tag become a link that lists all entries that has that tag.

I realize this is really kind of "link to an entry of type tag" - but tags don't appear in the dialog for selecting an entry. 

Is this possible? Should it be possible? Or should I solve it differently?

**Comment by andris-sevcenko** [comment]
Tags don't have URLs, so you can't really link to them. If you have a landing page, you could roll your own plugin that listen to the `craft/redactor/Field:: EVENT_REGISTER_LINK_OPTIONS` event and adds your own link types. You can look [here](https://github.com/craftcms/redactor/blob/v2/src/Field.php#L559) for an inspiration.

**Comment by andris-sevcenko** [comment]
Actually, scratch that. Element modals won't work for tags, so this is not possible at the moment, sorry.

There are plans to change Tags/Categories to be Entry elements in Craft 4.0, I think, which will help your issue, but that is still some time away.

**Comment by nitech** [comment]
Thanks for the clarification Andris. I kind of figured that tags was a choice. I should have used categories. Anyhow ;-)
