### ISSUE TITLE
toolbarFixed:true toolbars become detached in live preview

### ISSUE THREAD

**Issue by croxton** [craftcms/redactor#157]
The toolbar can become detached from a textfield when using live preview.

This only happens when the editor has scrolled down the screen causing the toolbar to become fixed at the top of its field. If the editor then clicks the live preview button the toolbar becomes detached from the field and is fixed relative to the screen rather than the field.

Tested in Chrome 76.0.3809.100

**Comment by croxton** [comment]
Workaround:

```
.lp-editor-container .redactor-toolbar-fixed {
    position: static !important;
    width: auto !important;
    top: auto !important;
}
```

**Comment by andris-sevcenko** [comment]
Should be nicely fixed in the next release!
