### ISSUE TITLE
[Bug?] Redactor config conflict between buttons property and "image" button

### ISSUE THREAD

**Issue by xavianaxw** [craftcms/redactor#158]
**Plugins**
Redactor version `2.3.3.2`
AWS S3 version `1.2.5`

I was trying to achieve the following sequence on my toolbar

![Screen Shot 2019-08-19 at 4 03 15 pm](https://user-images.githubusercontent.com/8082158/63242487-e25cde80-c29a-11e9-952c-dcd3b74f21a6.png)

and came up with this config

```
{
  "grammarly": false,
  "structure": true,
  "toolbarFixed": true,
  "buttons": [
    "format", 
    "bold", 
    "italic", 
    "underline",
    "deleted",
    "lists", 
    "alignment",
    "line",
    "link"
  ],
  "buttonsAddAfter": { 
    "after": "link", 
    "buttons": [
      "redactoranchors",
      "image",
      "video",
      "table",
      "html"
    ]
  },
  "buttonsAddBefore": { 
    "before": "html", 
    "buttons": [
      "fullscreen"
    ]
  },
  "plugins": [
    "alignment",
    "redactoranchors",
    "video",
    "table",
    "fullscreen",
    "counter"
  ],
  "formatting": [
    "h1", 
    "h2", 
    "h3", 
    "h4", 
    "h5", 
    "p", 
    "blockquote",
    "pre"
  ]
}
```

but my image upload looks like this when done this way

![Screen Shot 2019-08-19 at 4 04 08 pm](https://user-images.githubusercontent.com/8082158/63242523-fef91680-c29a-11e9-8c34-3c8a5743c27c.png)

But when I change it to the conventional config with all buttons within the `buttons` property like so:

```
{
  "grammarly": false,
  "structure": true,
  "toolbarFixed": true,
  "buttons": [
    "format", 
    "bold", 
    "italic", 
    "underline",
    "deleted",
    "lists", 
    "alignment",
    "line",
    "link",
    "redactoranchors",
    "image",
    "video",
    "table",
    "fullscreen",
    "html"
  ],
  "plugins": [
    "alignment",
    "redactoranchors",
    "video",
    "table",
    "fullscreen",
    "counter"
  ],
  "formatting": [
    "h1", 
    "h2", 
    "h3", 
    "h4", 
    "h5", 
    "p", 
    "blockquote",
    "pre"
  ]
}
```

I get the right image popup but the order of my buttons in the toolbar is messed up.

![Screen Shot 2019-08-19 at 4 06 07 pm](https://user-images.githubusercontent.com/8082158/63242628-57301880-c29b-11e9-9418-1310baceaa2c.png)

![Screen Shot 2019-08-19 at 4 06 01 pm](https://user-images.githubusercontent.com/8082158/63242630-5b5c3600-c29b-11e9-8691-72451d2b5c4a.png)

Anyone can point me to the right direction so I can achieve both?

**Comment by andris-sevcenko** [comment]
@xavianaxw ah, it's because Craft does some button replacing with its own and probably does not take into account the advanced button management things you've done. I'll take a look at this.

**Comment by andris-sevcenko** [comment]
Just pushed a fix to address this.

A small caveat, though, is that plugins add their buttons after they are initialized, so plugin buttons will always appear at the end, as far as I can tell, and referencing to plugin buttons in button configuration options will just cause them to be skipped as they don't exist yet.
