### ISSUE TITLE
ctrl+u adds underline even though shortcut is set to false

### ISSUE THREAD

**Issue by ricdev** [craftcms/redactor#159]
I have the following json configuration:
`{
  "buttons": ["bold"],
  "plugins": ["limiter", "counter"],
  "linkNewTab": true,
  "toolbarFixed": true,
  "limiter": 64,
  "shortcuts": false,
  "pastePlainText": true,
  "pasteImages": false,
  "pasteLinks": false,
  "pasteInlineTags": ["strong", "b"]
}`

The issue is when the user ctrl+u, the Highlighted text becomes underlined.

**Comment by andris-sevcenko** [comment]
That's a Redactor issue, unfortunately, still reproducable on their site.
