### ISSUE TITLE
Text styles aren't updating in Live Preview

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/redactor#160]
The Redactor text styles aren't live updating in the live preview. When we add new text there is no problem, but when we set text to bold or italic, the live preview isn't updating. After we click somewhere on the page it changes to the correct style.

![Screen Shot 2019-08-30 at 09 12 13](https://user-images.githubusercontent.com/42932673/64000561-53578e00-cb06-11e9-9fd9-ae234bcdd91a.png)

Craft CMS 3.3.0.1
Redactor: 2.3.3.2

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this with Craft 3.4 and Redactor 2.5.

Please, let me know if, after updating, the issue persists.

**Comment by am0** [comment]
Hi @andris-sevcenko - I'm having the same issue as @carolineboeykens. Have just updated CMS and Redactor to latest and am still having this issue. Seems to be whether or not the field is standalone or within a block. (Tested in Chrome/Mac and Windows, could test with other browsers if you wish.)

Have narrowed it down to the toolbar buttons not triggering the preview update. Using the Ctrl/Cmd-B shortcut to bold text updates the preview as expected, but when clicking the bold button, nothing happens until you defocus the editor or change something else within it. This also seems to affect the other toolbar buttons as well- tested with the Italic, Link and Formatting and the same thing occurs, only updating when defocusing or making another change.

Not a huge issue, but something a client has flagged up recently.

**Comment by carolineboeykens** [comment]
We are still having this issue. Can we do something about this?

Craft CMS 4.10.0
Redactor: 3.1.0
