### ISSUE TITLE
Inconsistent imageResizable behaviour

### ISSUE THREAD

**Issue by engram-design** [craftcms/redactor#162]
I'm seeing inconsistent behaviour with the `imageResizable` setting, when using with a caption. It seems like Craft is overriding the Redactor behaviour by setting the style (width/height) or the `img` element, and not the `figure` element too.

To illustrate, see the video below for how it works of the Redactor site:
https://www.dropbox.com/s/r80p65nkg1kpb8n/redactor.mov?dl=0

And how it works on the Craft site:
https://www.dropbox.com/s/8j6llbz2v8qotal/redactor-craft.mov?dl=0

I've also included the web inspector, so you can see what's not being applied.

Its not related, but noticing some severe lag (captured in the video) when resizing on Craft.

Related to https://github.com/craftcms/redactor/issues/39

**Comment by engram-design** [comment]
Looks like this might be a Redactor issue, as testing with `https://imperavi.com/assets/redactor/js/redactor3.js` works as expected. So I suppose updating to the latest version would fix.

**Comment by johndwells** [comment]
+1 for this.  Would be great to get Redactor updated to latest (3.2.2 as of August 23, 2019).

**Comment by andris-sevcenko** [comment]
This should be resolved with the release of Redactor 2.4.0
