### ISSUE TITLE
"Link to entry" - element api, multisite

### ISSUE THREAD

**Issue by boxadesign** [craftcms/redactor#163]
Hi,

I have a multi language set up and using redactor for the text editor. I'm using the element-api and this could be an issue with that plugin.

When using the "link to entry" method the url given to the link is something like...

`/foo/bar#entry:5:url`

I have three sites and the id for an entry is the same across all three. Say my default site is English (this propagates across the others) and I have a french and german site the links within each may look like:

`/foo/bar#entry:5:url (default)`
`fr/foo/bar#entry:5:url`
`de/foo/bar#entry:5:url`

I get the content with this simple method in my element api endpoint:

```php
'body' => $entry->body
```

But the url that comes through is only for the default site for each of my language endpoints.

It appears that (perhaps??) only the id is used to build the url and gets that url from the default site and doesn't respect the site it comes from.

Thanks

**Comment by boxadesign** [comment]
@brandonkelly Why has this been closed?

**Comment by brandonkelly** [comment]
Your duplicate issue was closed; this one hasn’t.

**Comment by brandonkelly** [comment]
But now it has :) Because we just released version 2.4.0 with a fix.

**Comment by boxadesign** [comment]
@brandonkelly Awesome thanks. Sorry for the confusion!
