### ISSUE TITLE
Redactor v2.4.0 breaks the formatting

### ISSUE THREAD

**Issue by EmptyStreets** [craftcms/redactor#165]
The latest release randomly removes the breakes within the text. It means that all existing entries can't be read properly. Sample can be seen here:

https://gyazo.com/2b7ab8c37f25ea19cb15aac8940b59a4

**Comment by verbeeksteven** [comment]
Can confirm this is also happening for us

We needed to add

    "breakline": false,

to the redactor configs to "sort of" fix it.

**Comment by verbeeksteven** [comment]
Seems to be due to #161 I have reverted for now.

**Comment by andris-sevcenko** [comment]
Assuming this has been fixed? Closing, please let me know if this still appears with 2.5.0
