### ISSUE TITLE
Including CodeMirror for the source/html view?

### ISSUE THREAD

**Issue by timmyomahony** [craftcms/redactor#167]
In the Redactor docs there is a `source` option:

https://imperavi.com/redactor/docs/settings/source/

that allows you to customise the raw html view. For example you can have:

```
"source": {
  "codemirror": true
},
```

Which (as I understand it) renders the HTML source area with [CodeMirror](https://codemirror.net/) making it easier to edit the underlying text.

When I enable this I get the the console error:

> ReferenceError: CodeMirror is not defined

Obviously this is expected as I haven't included CodeMirror. 

Is there any best practises on how to best add CodeMirror to the Craft Control CP so that I can get this working? Is the easiest thing to create a custom plugin that does this?

**Comment by m8brgarc** [comment]
I need some guidance on this as well.

**Comment by andris-sevcenko** [comment]
You can use the [CP JS](https://plugins.craftcms.com/cp-js) and the [CP CSS](https://plugins.craftcms.com/cp-css) plugins to include the relevant files.

It doesn't seem reasonable to include the required files for this in this plugin.
