### ISSUE TITLE
When saving an entry the enters/line breaks disappear.

### ISSUE THREAD

**Issue by martijnvanonz** [craftcms/redactor#173]
Hello.
when saving an entry the enters/line breaks disappear.
(Those fields are inside a matrix block)

Craft version: 3.3.13
Redactor version: 2.4.0

**Text like this:**

test test words test

test more words test

**Becomes this after saving the entry:**

test test words test
test more words test

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has actually already been covered by #171,
and it’s been fixed for the next release.
