### ISSUE TITLE
Figure/iFrames

### ISSUE THREAD

**Issue by gbaumbach** [craftcms/redactor#175]
I've noticed the figure tag is being added when I insert an iFrame (Google Map embed). I tried disabling the image figure which does eliminate figures for images, but has no impact on iFrames. Any way to disable figures being added on iFrames?

**Comment by andris-sevcenko** [comment]
How are you embedding the iframe? Just opening the code view and pasting it?

Does this happen immediately or after saving?

**Comment by gbaumbach** [comment]
I paste it in code view and it inserts the figure upon saving.

**Comment by andris-sevcenko** [comment]
Unfortunately, that's just part of the cleanup routine Redactor runs at multiple points and there are no settings to exempt `iframes` from that behavior.
