### ISSUE TITLE
Links at the end of sentences break HTML on Save

### ISSUE THREAD

**Issue by mzlock** [craftcms/redactor#177]
I wrote an importing tool that saves some content to a Redactor field. In this case the `<p>` tags run together, so you get content imported into Redactor that looks like this:

```
<p>Sentence that ends in a link https://example.com/links-ends-sentence.</p><p>New sentence.</p>
```

But with this content, the link breaks the HTML. On save, Redactor will convert that to:

```
<p>Sentence that ends in a link <a href="https://example.com/links-ends-sentence.</p><p>New" class="redactor-autoparser-object">https://example.com/links-ends...</a> sentence.</p>
```

It tries to automatically hyperlink the URL, but incorrectly takes the url **plus** every character before a space as the `href`.

**Comment by andris-sevcenko** [comment]
It seems like Redactor is, indeed, getting confused there.

You can disable the hyperlinking behavior by setting the `autoparse` setting to `false` in the Redactor config.
