### ISSUE TITLE
redactor in the pediment frotntend

### ISSUE THREAD

**Issue by thefubon** [craftcms/redactor#185]
<img width="1352" alt="Снимок экрана 2019-12-05 в 14 46 59" src="https://user-images.githubusercontent.com/43171309/70232799-43d38b00-176e-11ea-9aab-b7cd0f35ab50.png">

It is possible to display the redactor in the pediment frotntend?
https://docs.craftcms.com/v3/dev/examples/entry-form.html

**Comment by andris-sevcenko** [comment]
I'm afraid that's not possible. Also, the Redactor editor itself is not free.

How about using [CKEditor](https://ckeditor.com/ckeditor-5/) for front-end text fields?
