### ISSUE TITLE
Missing single sections when linking to entry on a multisite

### ISSUE THREAD

**Issue by andersaloof** [craftcms/redactor#188]
I'm not seeing the single sections, when trying to link to an entry in a redactor field.

My Craft setup has 7 sites, 6 of them different languages, the 7th site being a splash page to select one of the language sites. The splash page is setup as the primary site (though changing this doesn't seem to affect the issue i'm experiencing).

I have different channels, structures and singles which are available across all the language sites, but not the splash site and a single section for the splash page, available only for the splash site.

The issue occurs when I try to link to an entry in a redactor field in one of the language sites, the section list only list the channels and structures for the relevant site, not the singles which should be able to ble linked to.

If I change the language sites singles to also be available for the splash site (which they shouldn't have to be), they are listed correctly when linking to an entry in a redactor field.

I'm currently using Craft CMS 3.3.18.1.

**Comment by brandonkelly** [comment]
Just got this fixed for the next release!
