### ISSUE TITLE
Add option for Mailto link

### ISSUE THREAD

**Issue by JayBox325** [craftcms/redactor#189]
It would be nice for this list to include a 'mail' link. My clients may not be aware of how `mailto:` is a required prefix for mail links.

<img width="537" alt="Screenshot 2019-12-15 at 02 18 12" src="https://user-images.githubusercontent.com/13233809/70857136-41490200-1ee1-11ea-901d-bb331ff111d0.png">

**Comment by cedricsteiner** [comment]
I just found this redactor plugin:
https://gist.github.com/daltonrooney/f4bf5b6fa668012016f4400d82d34b9e
With credits to:
https://www.jackbarber.co.uk/blog/2019-04-26-email-address-plugin-for-redactor

And was able to integrate it in craftcms with the description here:
https://github.com/craftcms/redactor#redactor-js-plugins

Works fine. Hope that helps.

**Comment by andris-sevcenko** [comment]
Closing this, as @cedricsteiner has provided a solution.

**Comment by mmikkel** [comment]
For anyone who ends up here; don't know if this was always the case, but at least since v. 2.8.8, Redactor will automatically add the `mailto:` prefix if you simply insert an email address via the `Insert link` option.
