### ISSUE TITLE
Error when viewing HTML source

### ISSUE THREAD

**Issue by piotrpog** [craftcms/redactor#190]
Hi, 
i seem to have some kind of problem with redactor plugin on chrome browser. This problem occurs on multiple machines.

When redactor field is higher than viewport size and i try to display html source, editing area gets stuck scrolled down to bottom and i cant scroll up. This problem occurs only when redactor field is nested in matrix.
Here is recording showing this behaviour:
https://drive.google.com/file/d/1ncvHHKDmr732UTPDTd4vPODSL8_fWQ31/view?usp=sharing

**Comment by andris-sevcenko** [comment]
Can you try updating to Craft 3.4.x and Redactor 2.5? A lot of markup changed in 3.4, so it's entirely possible this has gone away. Let me know if the issue still persists and I'll re-open the issue.
