### ISSUE TITLE
Problem with searchindex table data

### ISSUE THREAD

**Issue by iainhenderson** [craftcms/redactor#191]
When saving the search index keywords for a redactor field it seems to be running a strip_tags and strtolower or something similar to remove the html markup and just save the text (make sense).

However in this process it's not adding spaces when stripping tags, so the text content at the end of a tag is running into the text content at the start of the next tag:

So for redactor content:

```
<p>Welcome to thing</p>
<p>Howdy partner</p>
```

The searchindex data for this field would be: "welcome to thinghowdy partner"

This combined with the the fact that Craft's search term options [only enables subRight by default](https://github.com/craftcms/cms/issues/1420 ), means that a Crafts default search doesn't match any word at the start of a html node.

i.e. a keyword search for "Howdy" wouldn't match the above content due to the characters before the "howdy" string

For the time being you can work around this behaviour by enabling subLeft in defaultSearchTermOptions

**Comment by andris-sevcenko** [comment]
This appears to have been resolved at the same time #171 was resolved, since fixing that one addressed aggressive whitespace stripping.
