### ISSUE TITLE
Beyond Grammar not working

### ISSUE THREAD

**Issue by perea-truelogic** [craftcms/redactor#193]
Hi there!

I've been struggling enabling the beyond grammar plugin, as it doesn't seem to be working.

My standard.json file looks like this:

For the plugin part:

`"plugins": ["fullscreen", "table", "clips", "definedlinks", "beyondgrammar"],`

Beyond grammar config:

"beyondgrammar":{
      "service":{
          "apiKey": "A_Valid_Key",
          "userId": "ing.alexperea",
          "serviceUrl": "https://rtg.prowritingaid.com"
      },
      "grammar":{
        "languageFilter": ["en-US", "en-GB"],
        "languageIsoCode": "en-US",
        "checkStyle": true,
        "checkSpelling": true,
        "checkGrammar": true,
        "showThesaurusByDoubleClick": true,
        "showContextThesaurus": false
      }
  }

I don't know if my configuration is missing something or if there is a problem with the plugin. Tested it craft version: 3.3.7 and 3.3.19 and craftcms redactor version: 2.3.3.2 and 2.4.0.

No console errors are displayed

Thank you in advance

**Comment by andris-sevcenko** [comment]
If you look at https://imperavi.com/redactor/plugins/beyondgrammar/, they are including external JS to make it work.

You should be able to achieve this using the [CP JS plugin](https://plugins.craftcms.com/cp-js.

<img width="824" alt="Screen Shot 2020-02-06 at 14 31 42" src="https://user-images.githubusercontent.com/1891118/73937297-68beb880-48ed-11ea-8ad4-d8458c0c5462.png">
