### ISSUE TITLE
"Normal text" option not removing classes

### ISSUE THREAD

**Issue by jairedden** [craftcms/redactor#194]
If I add a new style to the formatting dropdown in my config file, like this:
```
"formattingAdd": {
 "large-header": {
  "title": "Large Header (H1)",
  "api": "module.block.format",
  "args": {
   "tag": "h1",
   "class": "large-header"
  }
 }
}
```
and then apply that to some text, it works fine. But if I then apply the "normal text" option to that text, it does change it from being an `<h1>` back to being a `<p>` but it retains the "large-header" class, which should obviously be removed too.

This never used to happen, only in relatively recent versions of the plugin, although I can't say exactly which version broke it.

**Comment by jsunsawyer** [comment]
@jairedden Just ran into this issue myself. Ended up simply adding a custom "Normal text" option. Unfortunately, I have to actually add a default class to override the custom one.

Initially, I tried using the `type` argument with a value of `set`, but that didn't work. See: https://imperavi.com/redactor/docs/settings/formatting/

```
"normalText": {
  "title": "Normal Text",
  "api": "module.block.format",
  "args": {
    "tag": "p",
    "type": "set"
  }
}
```

Here's what did work. (Note: I also cleared out default formatting, as I'm only allowing for custom options)

```
"normalText": {
  "title": "Normal Text",
  "api": "module.block.format",
  "args": {
    "tag": "p",
    "class": "color-default"
  }
}
```

Definitely seems like there's an issue somewhere.

**Comment by jairedden** [comment]
@jsunsawyer Great minds think alike, thats exactly the fix I ended up with too. It's not ideal though, would be nice to see this get a proper solution.
I should say, this is on Craft CMS 3.3.19 with Redactor 2.4.0

**Comment by andris-sevcenko** [comment]
This is just how Redactor treats the formatting functionality. ([Source](https://imperavi.com/redactor/examples/formatting/add-formatting-tags/))

**Comment by jsunsawyer** [comment]
@jairedden After checking out what @andris-sevcenko linked, I came up with a better solution for clearing any custom classes.

```
"normalText": {
  "title": "Normal Text",
  "api": "module.block.format",
  "args": {
    "tag": "p",
    "class": "color-gold color-blue",
    "type": "remove"
  }
}
```

Just include any custom classes you have set up so they all get removed from a single formatting tag.

I still think that the default Normal Text option should clear out any styles though. Perhaps it's worth submitting an issue/request to them directly. I just don't know where that's supposed to be done.
