### ISSUE TITLE
Is it possible to apply specific class or heading to selected text?

### ISSUE THREAD

**Issue by peterchang2** [craftcms/redactor#195]
For example, if I want to change dolor to code formatting I can't and it will apply the code formatting to the entire line of text. This is the same when using Properties plugin to ass classes and ID. 

- Redactor 2.4.0
- Craft CMS 3.3.19

Expected result:
Lorem ipsum `dolor` sit amit.

Actual result:
`Lorem ipsum dolor  sit amit.`

**Comment by andris-sevcenko** [comment]
The [Inline style](https://imperavi.com/redactor/plugins/inlinestyle/) plugin is probably what you're looking for.
