### ISSUE TITLE
HTML Source Code - not formatted

### ISSUE THREAD

**Issue by willard** [craftcms/redactor#196]
We updated to latest craft, and we notice that HTML/Source code is not displaying correctly after saving the entry.

**it should be like this :**
<img width="1074" alt="2020-01-13_1634" src="https://user-images.githubusercontent.com/544756/72294418-84eb7480-3623-11ea-9caf-3a84489d5788.png">

**but its render like this :** 
<img width="1055" alt="2020-01-13_1635" src="https://user-images.githubusercontent.com/544756/72294416-84eb7480-3623-11ea-98f6-ff09723ff77b.png">

**Additional info**
Craft version: 3.3.20.1
PHP version: 7.2.21
Database driver & version: MySQL 5.6.22
Plugins & versions: Redactor 2.4.0

**Comment by willard** [comment]
I made some temp fixed.

in redactor config i added 
`"removeNewLines": false`

and commented out 

`//$value = preg_replace('/[\r\n]/', '', $value);`

at line 362 in Field.php

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has actually already been covered by #171,
and it’s been fixed for the next release.
