### ISSUE TITLE
Link to entry -  status disabled (and other site)

### ISSUE THREAD

**Issue by danielenstrom** [craftcms/redactor#198]
There is a status dropdown when "link to entry" but only "Live" entries are shown.

<img width="858" alt="Skärmavbild 2020-01-15 kl  16 43 16" src="https://user-images.githubusercontent.com/260478/72447938-7da8a000-37b6-11ea-9b9f-37591768d37e.png">

We also unable to link to entries in other sites/languages (all entries, including status Live). 

Craft: 3.3.19
Redactor: 2.4.0

**Comment by andris-sevcenko** [comment]
Cross-site linking was added in Redactor 2.5.0.
