### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by mightyfineyall** [craftcms/redactor#199]
Latest stable build of Craft CMS (published 8 days ago) is [3.3.20.1](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md). Redactor now requires Craft CMS 3.4, which results in the following error when using `composer require`:

`Problem 1
    - Installation request for craftcms/redactor ^2.5 -> satisfiable by craftcms/redactor[2.5.0].
    - craftcms/redactor 2.5.0 requires craftcms/cms ^3.4.0-RC1 -> satisfiable by craftcms/cms[3.4.0-RC1, 3.4.0-RC1.1, 3.4.0-RC2, 3.4.0-RC3, 3.4.x-dev] but these conflict with your requirements or minimum-stability.`

Is there a reason Redactor is dependent on a version of Craft not readily available?

**Comment by angrybrad** [comment]
The final 3.4 release is roughly a week away and RC1 is in a stable enough state we feel comfortable with it.
