### ISSUE TITLE
Cannot insert multiple images at once

### ISSUE THREAD

**Issue by rungta** [craftcms/redactor#200]
### Description

Redactor appears to be inserting only the last image, regardless of how many are selected in the asset selector modal. This was reported by a client who we migrated from Craft 2, where authors were able to add multiple images in one go just fine.

### Steps to reproduce

1. Click on the `image` button
2. Select 2 or more images
3. Click 'Select'
4. Only the last image is inserted in the field

### Additional info

- Redactor version: 2.4.0
- Craft version: 3.3.19

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has been fixed for the next release.

**Comment by rungta** [comment]
Thanks @andris-sevcenko! Eagerly awaiting the [Snow Leopard](https://9to5mac.com/2018/01/31/snow-leopard-became-reliability-legend/) Redactor release.
