### ISSUE TITLE
Link context bar is mispositioned in Craft 3.4.x

### ISSUE THREAD

**Issue by rmales** [craftcms/redactor#201]
### Description

When you focus a link in the Redactor editor it should show a black overlaid 'context bar' above the link. In Craft 3.4 this is mispositioned, and often outside the user's viewport.

### Additional info

- Craft version: 3.4.1
- Redactor plugin version: 2.5.0

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has been fixed for the next release.
