### ISSUE TITLE
Toolbar is no longer sticky in Craft 3.4.x

### ISSUE THREAD

**Issue by rmales** [craftcms/redactor#202]
### Description

In previous versions of Craft the Redactor toolbar would stick to the top of the entry page scrolling content area, in 3.4.x this is no longer the case which makes editing long content difficult.

### Additional info

- Craft version: 3.4.1
- Redactor plugin version: 2.5.0

**Comment by matthillco** [comment]
+1 Yes, it's now extremely difficult to add formatting or links within long blocks of text because the redactor toolbar has scrolled off screen by the time the text to select is in view.

**Comment by andris-sevcenko** [comment]
Thanks for reporting. Fixed for the next release!
