### ISSUE TITLE
Volume permissions are ignored

### ISSUE THREAD

**Issue by gglnx** [craftcms/redactor#203]
1. Create an user with only access to one volume (and another to which the user hasn't access).
2. Click `file` or `image` button.
3. You will see both volumes and the user can select files from the volume they don't have access to.

**Comment by andris-sevcenko** [comment]
We'll take a similar approach to this as https://github.com/craftcms/cms/issues/887#issuecomment-565152805

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has been fixed for the next release.
