### ISSUE TITLE
Fullscreen toolbar is mis-positioned for long richtext fields

### ISSUE THREAD

**Issue by matthillco** [craftcms/redactor#204]
When switching to full screen on long richtext fields, the Redactor toolbar is misplaced too far down the screen.

This has been an issue for some time, I can duplicate this problem in these setups:
Redactor 2.5.0 in Craft 3.4.1
Redactor 2.4.0 in Craft 3.3.9

![image](https://user-images.githubusercontent.com/2166204/73583282-2fb7bb80-4489-11ea-92ab-649794aa0f21.png)

**Comment by andris-sevcenko** [comment]
This was fixed in 63425f287742399aba3faa773c827a21bff789af for the next release.
