### ISSUE TITLE
Image editor and resize bar is mispositioned in Craft 3.4

### ISSUE THREAD

**Issue by petertindemans** [craftcms/redactor#206]
To reproduce:
1. Clean install Craft CMS 3.4.5
2. Installed the latest redactor plugin
3. Uploaded a image
4. Resize handle and image editor are now positioned lower that the normal bottom positon

Tested in Chrome and Safari:
![Uploading Schermafbeelding 2020-02-10 om 14.21.13.png…]()

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has actually already been covered by #1234.
Please follow along over there.
