### ISSUE TITLE
Redactor context toolbar displayed over Craft entry title

### ISSUE THREAD

**Issue by niektenhoopen** [craftcms/redactor#207]
If you open the Redactor toolbar by for example clicking on a link, and then scroll down the (longer) page, the context menu shows over the Craft title

Tested on the latest commit (unreleased) da375f5345305f6803a7c8c739644b0b42c942 

![Screenshot 2020-02-12 at 10 34 04](https://user-images.githubusercontent.com/3450011/74321843-444a5c80-4d83-11ea-97a1-bc2f21c12bd9.png)

**Comment by andris-sevcenko** [comment]
Yeah, I'm sort of on the fence about this. Craft uses z-index in moderation, while Redactor pulls out all the stops.

The header has a z-index of 12, while Redactor has its context bar (what they call it) with a z-index of 1051.

If I override their z-index and set it to a value less than 12, it's entirely possible that something else will break in their element visibility order, so maybe it's better for Craft to up the z-index of the header.

We'll discuss this and get back to you.

**Comment by niektenhoopen** [comment]
I get it. No need to hurry. Just wanted to bring it to your attention in case you didn't notice this (very specific) behaviour yet. Keep up the good work! 👍

**Comment by andris-sevcenko** [comment]
Okay then, this is fixed as well, time to cut a release!
