### ISSUE TITLE
2.6.0 removes Redactor toolbar altogether

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/redactor#208]
![image](https://user-images.githubusercontent.com/1377169/74466985-e474b400-4e5d-11ea-862a-e0887d352bb3.png)

![gone](https://user-images.githubusercontent.com/1377169/74467217-433a2d80-4e5e-11ea-8ac6-6c7523fa71be.gif)

**Comment by EmptyStreets** [comment]
This applies only if you select the default config, custom or simple configs are ok. So def a bug.

**Comment by andris-sevcenko** [comment]
Oopsies. Just cut a release to address this.

This is the last time you've thwarted my plans to achieve the ultimate purity in design, @chasegiunta!

![giphy](https://user-images.githubusercontent.com/1891118/74508304-65d45100-4f07-11ea-9ac5-6aeea20ae1b0.gif)
