### ISSUE TITLE
White Space on top of content editor

### ISSUE THREAD

**Issue by willard** [craftcms/redactor#211]
**Description**
There is a huge white space above the content editor when in HTML mode.

![image](https://user-images.githubusercontent.com/544756/74977494-cfb59480-53f8-11ea-9ea4-5c6172f4a9ae.png)

**Additional info**
Craft version: Craft Pro 3.4.6.1
PHP version: 7.2.21
Database driver & version: MySQL 8.0.17
Plugins & versions:  Redactor | 2.6.0.1

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this. Which browser are you using?
Also, can you share your Redactor config?

**Comment by willard** [comment]
i'm using google chrome and in my config i have "minHeight": "300px", i think this option is the reason, but we need this to have min height for the text editor. 

<img width="1598" alt="2020-02-21_0853" src="https://user-images.githubusercontent.com/544756/75040152-23bb8a00-5488-11ea-84df-fe7fce0bdc20.png">

**Comment by brandonkelly** [comment]
I was able to reproduce this with the `minHeight` setting as well. Turns out it is a result of a5ebd0d829b301d7e9232293f84c093bb28a407a. Just released Redactor 2.6.1 with a fix.
