### ISSUE TITLE
Adding text above a list wraps in a div instead of <p> / <h3> etc

### ISSUE THREAD

**Issue by darylknight** [craftcms/redactor#213]
When you're trying to add content above a list in Redactor:
If a redactor field contains a list, and you press return before the first item in that list, it creates a blank list item. That's normal. To clear that and be able to add normal text, you then press backspace. That gives you a cursor above the list that doesn't add new items. If you then start typing and try to format that text, it wraps that text in a div instead of a `<p>` tag, and it's impossible to format it in any way without source code view.

1. Redactor field contains a list:

![image](https://user-images.githubusercontent.com/1250017/75329469-50a4de00-5888-11ea-8880-a8e4f17ad46d.png)

2. Press return to get a new blank list item:
![image](https://user-images.githubusercontent.com/1250017/75329486-5b5f7300-5888-11ea-9b0d-b7aa76ae0b67.png)

3. Press backspace to be able to start typing:
![image](https://user-images.githubusercontent.com/1250017/75329506-631f1780-5888-11ea-973a-9d505017a9a2.png)

4. Start typing:
![image](https://user-images.githubusercontent.com/1250017/75329536-6d411600-5888-11ea-883a-fd6dce908539.png)

5. This content has been wrapped in a div, so it's impossible to add formatting:
![image](https://user-images.githubusercontent.com/1250017/75329567-7af69b80-5888-11ea-8cde-66426b29e621.png)

Craft CMS 3.3.20.1
Redactor 2.4.0

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Is this consistently reproducible for you?

**Comment by darylknight** [comment]
Annoyingly, no not consistently. It happens on multiple websites but only occasionally. I guess this is worth closing unless me/someone manages to track down the cause.
