### ISSUE TITLE
Why is Redactor trying to order my plugins?

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/redactor#218]
For a few of the plugins being added automatically, they are telling Redactor to `addButtonBefore` or `addButtonAfter` another **specific** button...

 - https://github.com/craftcms/redactor/blob/v2/lib/redactor-plugins/table/table.js#L105
 - https://github.com/craftcms/redactor/blob/v2/lib/redactor-plugins/video/video.js#L70
 - https://github.com/craftcms/redactor/blob/v2/lib/redactor-plugins/inlinestyle/inlinestyle.js#L56

It feels like the Craft plugin shouldn't be making decisions as to what order our Redactor plugins show up. Ideally, they would just appear in whatever order I have them listed in the JSON file.

```text
  "buttons": [
    "bold",
    "italic",
    "underline",
    "link",
    "lists"
  ],
  "plugins": [
    "alignment",
    "table"   <--- Table is at the end
  ],
```
<img width="303" alt="Ω 2020-04-11 at 3 33 56 PM" src="https://user-images.githubusercontent.com/5309692/79056378-bf58b380-7c0a-11ea-928a-0d24225b0792.png">

Because the Craft plugin is making these decisions, it's leading to strange behavior in my custom toolbar. When I add a plugin (for example `table`), it automatically places itself in the toolbar in a _specific_ position. It's confusing because the plugin button ends up **not where I placed it**.

Can we please remove the preset order preferences? Or somehow make them overridable?

**Comment by andris-sevcenko** [comment]
Those are plugins provided by Redactor, so not sure how smart it would be to tamper with that code.

**Comment by lindseydiloreto** [comment]
Huh, I assumed that was just Craft's implementation of those libraries. It's odd that Redactor would be so strict about where those buttons will appear... isn't the entire point of Redactor its flexibility?

Is there any way to override that? I find it hard to believe that a Table button _must_ go next to a Link button, no exceptions. 😕

**Comment by andris-sevcenko** [comment]
It's probably possible to override that with some JS code, but, if we're going to tamper with this, let's do it right.

If you _wanted_ to insert the table button in the middle there - how would you expect to define this in the config?

**Comment by lindseydiloreto** [comment]
Hmm... that's a great question, because Redactor is already squirrely about how you arrange the buttons.

Ideally, we'd be able to use the `before` and `after` methods to place them anywhere we want...

https://imperavi.com/redactor/docs/settings/button/#s-buttonsaddafter<br/>

But worst case scenario, I'd just expect it to land exactly where I put it in the `plugins` array...

```
  "plugins": [
    "alignment",
    "fontcolor",
    "table",   <--- Table should be in the middle
    "fullscreen",
    "clips"
  ]
```

**Comment by andris-sevcenko** [comment]
@lindseydiloreto what I meant is how would you insert it between the bold and italic buttons, for example?

**Comment by lindseydiloreto** [comment]
Are you asking "how do I envision it working?" Maybe something like this...

```js
  "buttonsAddAfter": {
    "after": "bold",
    "buttons": ["table"] // Places the plugin button
  },
  "plugins": [
    "table" // Loads the plugin
  ],
```

... or possibly like this...
```js
  "pluginsAddAfter": {
    "after": "bold",
    "buttons": ["table"] // Loads & places the button
  },
```

I have no idea how easily that jives with what Redactor and/or the Craft plugin are already doing. Glancing at [this commit](https://github.com/craftcms/redactor/commit/5a3212eb97906b16766af753ae638ea719dc10af), it seems that the Craft plugin occasionally needs to use brute force with Redactor anyway.

Let me know your thoughts, or if I completely misunderstood the question! 😄

**Comment by visuallization** [comment]
It is really weird that redactor isn't able to just order the buttons like they are defined in the array. It is the default behaviour I would expect when defining buttons. Considering that redactor is a paid tool I would wish for more flexibility and predictability.

**Comment by andris-sevcenko** [comment]
Took me a few months, but the solution is finally here in the form of a brand new `enforceButtonOrder` Redactor config option!

**Comment by andris-sevcenko** [comment]
(With the next release)

**Comment by lindseydiloreto** [comment]
Ahh, brilliant @andris-sevcenko! Thanks so much for nailing that down, my OCD will be much happier for it. 😄 

Can't wait to take it for a spin! 🍺
