### ISSUE TITLE
Page jumps to top of field when adding a hyperlink

### ISSUE THREAD

**Issue by janmeeus** [craftcms/redactor#222]
When you have a redactor field with a whole lot of text and you add a hyperlink to a word at the end of that text, after adding the link the page jumps all the way back to the top of the field.

It'll be nice if the modal would just close and the page wouldn't jump.

**Comment by andris-sevcenko** [comment]
This has been fixed for the 2.7 release!

**Comment by brandonkelly** [comment]
Redactor 2.7.0 is out now with this fix.
