### ISSUE TITLE
Ability to set a default transform for the entire field

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/redactor#223]
It would be great if we could determine a _default_ transform, so that the client doesn't have to remember to do it each time. It's incredibly rare that we'd want clients to be inserting full-sized images.

Implementation of the feature could be relatively straightforward...
- In the field settings, add a dropdown menu of available transforms.
- In the Redactor field, automatically apply that transform when no other transform is specified.

Hope that's a reasonable request!  🙂

**Comment by andris-sevcenko** [comment]
@lindseydiloreto how would the content editor specify a non-transformed image? With https://github.com/craftcms/redactor/issues/134 they could remove any transform after selecting the asset, but that's cumbersome, too.

**Comment by lindseydiloreto** [comment]
@andris-sevcenko how about this...
> - In the field settings, add a dropdown menu of available transforms.

... with a default option of "No default transform".

So by default, there would be no Default Transform. You'd need to manually select one from the "Default Transform" dropdown in the field settings.

Does that make sense?

**Comment by andris-sevcenko** [comment]
Right, but if there _is_ a default transform selected, how would a content editor add an image _without_ a transform?

**Comment by lindseydiloreto** [comment]
In that case, the Admin would need to set the field settings to use "No default". All other defaults would need to be applied manually.

**Comment by lindseydiloreto** [comment]
... which honestly, is actually just the current behavior.

**Comment by andris-sevcenko** [comment]
Right. So, if the admin has set a "default" transform, then there's no way of adding an image without one.

How about the transform dropdown just acting like a dropdown and if there's a default transform selected, it's selected on load? Well, prettier than "just a dropdown", but you get the idea.

**Comment by lindseydiloreto** [comment]
Yeah, that sounds even better! Keep the existing dropdown menu, but just allow us to set a _default_ value for it. Assuming the clients don't mess with that transform dropdown (and most of them won't), then it should effectively work as a default transform!

Brilliant. Thanks @andris-sevcenko!

**Comment by andris-sevcenko** [comment]
Alright, added this for the next Craft 3.5 themed release.

**Comment by lindseydiloreto** [comment]
Ahh, brilliant!! Thanks @andris-sevcenko! 🍺

**Comment by brandonkelly** [comment]
Redactor 2.7.0 is out now with this feature!
