### ISSUE TITLE
Default config missing image and file

### ISSUE THREAD

**Issue by digason** [craftcms/redactor#224]
The documentation lists the following as defaults:
['html', 'format', 'bold', 'italic', 'deleted', 'lists', 'image', 'file', 'link']

I can see where this is declared in the source redactor.js, but when I use the default setting, image and link never get added to the toolbar.

**Comment by andris-sevcenko** [comment]
This has been fixed for the Redactor 2.7 release.

**Comment by brandonkelly** [comment]
Redactor 2.7.0 is out now with this fix.
