### ISSUE TITLE
Keyboard shortcuts duplicate inline formatting elements like <em>

### ISSUE THREAD

**Issue by theAdhocracy** [craftcms/redactor#227]
When using common keyboard shortcuts whilst typing – such as `ctrl + b` for **bold** text – you cannot escape the formatting without adding a second set of empty HTML elements.

The expected common behaviour (as implied by the toggle argument on [inline modules](https://imperavi.com/redactor/docs/api-modules/inline/)) would be that the first instance of the shortcut adds the formatting and the second instance stops it. That allows you to format text as your type. What actually happens is that the second instance both stops the formatting **and** adds an empty HTML element i.e. `<strong></strong>` at the end of the line.

That can lead to long strings of inline elements at the end of paragraphs, which then wrap to new lines as they are created and become the default formatting for that new line.

I've tested the behaviour across Chrome/Firefox/Edge/Opera on Windows 10 in both Craft and on the Imperavi website. There are some issues inherent to Redactor when _combining_ inline formating (such as _**bold italics**_) but the issue of duplicating HTML inline elements for every keyboard shortcut appears to be specific to the Craft implementation.

Relatedly, I have tested overriding the keyboard shortcuts in my Redactor profiles with the `toggle` argument explicitly set, but it doesn't help.

**Comment by andris-sevcenko** [comment]
I'll put this on hold until after 2.7, as that release will include the latest Redactor version, so it's possible that this will be fixed.

**Comment by andris-sevcenko** [comment]
This is a wee bit delayed but seems to have been fixed with the latest Redactor version.
