### ISSUE TITLE
Add "All Entries" tab to Redactor's Entries modal

### ISSUE THREAD

**Issue by cakleimeier** [craftcms/redactor#228]
It would be helpful to have an "All Entries" tab in the Entries modal accessed via the "Link" button in Redactor. This would be particularly useful large sites with lots of Entries across lots of channels.

I understand that this is more complex in the Redactor "Link" Entries modal than in a standard Entries field because the purpose of the "Link" button is to get the _url_ of the selected Entry and so it should _not_ show Entries that don't actually _have_ urls, while the standard Entries field doesn't have that same restriction. However, if there's some way of adding an "All Entries" tab that only includes Entries that _do_ have urls, that would be a very helpful feature.

**Comment by andris-sevcenko** [comment]
This has been added for the next release which will require Craft 3.5.

**Comment by cakleimeier** [comment]
That's fantastic, thank you!

**Comment by brandonkelly** [comment]
Redactor 2.7.0 is out now with this change.
