### ISSUE TITLE
UTF-16 stripping?

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/redactor#229]
We occasionally have users paste from Microsoft Word, which can include UTF-16 encoding, is there a way to get Redactor to sanitize this input?

**Comment by andris-sevcenko** [comment]
It's probably worth looking into
https://imperavi.com/redactor/docs/settings/clean/ and https://imperavi.com/redactor/docs/settings/paste/

Source: @lindseydiloreto and his infinite wisdom over at https://craftcms.stackexchange.com/questions/8673/paste-from-ms-word-to-redactor

**Comment by ryanpcmcquen** [comment]
Hmm, most of that seems to refer to HTML stripping/cleaning, I'll do some testing and see what happens.
