### ISSUE TITLE
Keep fullscreen button enabled when in html mode

### ISSUE THREAD

**Issue by FrancisMawn** [craftcms/redactor#230]
Hi there,

When a user switch to the HTML display/mode, all other buttons are automatically disabled. 

I think it would make sens to keep the fullscreen button enabled, as this button is not used for text formatting. 

![image](https://user-images.githubusercontent.com/45174482/83801104-8c64f600-a676-11ea-836c-5edb01cac86e.png)

Thoughts?

Thanks

**Comment by andris-sevcenko** [comment]
This is done by the plugin provided by Redactor editor. Sorry! (https://imperavi.com/redactor/plugins/fullscreen/)

It's possible to go fullscreen and then switch to HTML mode, though.
