### ISSUE TITLE
Question - Behaviour when "linkNewTab": true and "linkTarget": "_blank" is defined

### ISSUE THREAD

**Issue by boldenamsterdam** [craftcms/redactor#231]
When you set the redactor config ```"linkNewTab": true``` the option to [open a link in a new tab](https://imperavi.com/redactor/docs/settings/link/#s-linknewtab) is being displayed in the modal. The option is being displayed as a checkbox.
This checkbox is always ```unchecked``` by default.

To make sure the links [open by default in a new tab ](https://imperavi.com/redactor/docs/settings/link/#s-linktarget)you extend the config with the redactor config with ```"linkTarget": "_blank"```. The checkbox is now always displayed as ```checked```. 

But with these both options set, I can not undo that the link is being opened in a new tab. Because even when you uncheck the box, it's not saving/overwritting the ```linkTarget``` setting.

In most cases 9 out of 10 times I want to open the link in a new tab. But for the other 1 out of 10 times, I still want to be able to **not** open the link in a new tab.

Any one experiencing the same issue and is there workaround for this?

Cheers

**Comment by andris-sevcenko** [comment]
That's how Redactor handles this on their end, unfortunately. Setting the `linkTarget` enforces it on inserting a link.

Craft _could_ override it, but that does not seem like a good idea - overriding the way a setting acts inside Redactor.
