### ISSUE TITLE
redactor adds <figure> around <iframe>

### ISSUE THREAD

**Issue by rolfkokkeler** [craftcms/redactor#234]
adding a youtube iframe results in this:

`<figure><iframe width=“560” height=“315" src=“https://www.youtube.com/embed/mQeP1orRTrw” frameborder=“0" allow=“accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture” allowfullscreen=“”></iframe></figure>`

**Comment by andris-sevcenko** [comment]
This is something Redactor does, unfortunately.

**Comment by rolfkokkeler** [comment]
issue was not redactor adding <figure>.
Cookiebot was the problem, it prevented showing any videos if not using youtune-nocookies url
