### ISSUE TITLE
Filter by "disabled" broken in element Index triggered from "link to entry" (multisite)

### ISSUE THREAD

**Issue by timkelty** [craftcms/redactor#236]
This was broken in Craft 3.4 (3.4.16 for me), but then fixed by `3.4.24` for all element indices.

To reproduce:
- On a multi-site, disable some entries in a section
- On the entries screen, filter by "disabled" and verify you can see them
- Now, from a redactor field, try to "Link to Entry", and filter by "disabled"

Comparing the `cp/actions/element-indexes/get-elements` request payloads, between the entries screen where it works, and the from redactor where it doesn't, it looks like the only difference is the criteria has `enabledForSite: null`, where the request redactor makes has no `enabledForSite` param in the criteria.

**Comment by andris-sevcenko** [comment]
> This was broken in Craft 3.4 (3.4.16 for me), but then fixed by 3.4.24 for all element indices.

So... it's not an issue if it was fixed?

To clarify, it's working as expected for me on Craft 3.4.23 and Craft 3.5. Both on Redactor 2.6.1 and 2.6.0.1

**Comment by timkelty** [comment]
@andris-sevcenko no, what I meant was by 3.4.24 it was fixed for all of the element indices trigger by Craft itself (eg Main entries screen, entry selection modal of entries field).

In 3.4.24/2.6.1, this behavior is fixed for those element indices, but still broken for the "Insert Entry Link" one triggered by Redactor.

**Comment by timkelty** [comment]
Here is the `element-indexes/get-elements ` request from the Craft entries when you select "disabled". It works. Note that it has `enabledForSite: null` in the criteria:
<img width="846" alt="from entries" src="https://user-images.githubusercontent.com/18329/85772137-8f3d8e80-b6ea-11ea-8a56-0de4f103287d.png">

Here is the `element-indexes/get-elements ` request triggered when you insert an entry link from redactor, and then select "disabled". It does not work. Not that is has no `enabledForSite` param in the criteria:
<img width="833" alt="from redactor" src="https://user-images.githubusercontent.com/18329/85772512-e93e5400-b6ea-11ea-8f7e-59d09673ce9b.png">

**Comment by timkelty** [comment]
Did a bit more digging: 

The reason it works from the main Craft entries index, is it passes `criteria: Craft.defaultIndexCriteria` (https://github.com/craftcms/cms/blob/6c579f86de714350a2af4b9e7adb956b54bf3bcf/src/templates/_layouts/elementindex.html#L69) which contains `enabledForSite => null` (https://github.com/craftcms/cms/blob/6c579f86de714350a2af4b9e7adb956b54bf3bcf/src/web/assets/cp/CpAsset.php#L288)

Similarly, it works for relation fields, because enabledForSite is getting set explicitly to `null` again: https://github.com/craftcms/cms/blob/6c579f86de714350a2af4b9e7adb956b54bf3bcf/src/fields/BaseRelationField.php#L852

So 2 questions…maybe more applicable to @brandonkelly:

- why all the setting of `null` vs, `false`, when the ElementQuery interface doesn't even allow it?
- it seems odd that each implementation of an element index would have to do this. Shouldn't `enabledForSite` just always be false when status=disabled in an element index?

**Comment by brandonkelly** [comment]
I think the reason it’s working as expected for normal Craft indexes is because they are passing `status: "disabled"` – which as of 3.4.19 will look for elements that are either disabled globally **or** disabled for the selected site (see craftcms/cms@acb88805dfdc37b8964eb6740f1ff49b13a69aee).

So @andris-sevcenko I think the issue here is that for whatever reason, `status: "disabled"` isn’t getting passed.

**Comment by timkelty** [comment]
@brandonkelly no, `status: "disabled"` is getting passed (see screenshots of reqs: https://github.com/craftcms/redactor/issues/236#issuecomment-649728981).

The difference is `enabledForSite: null`.

**Comment by timkelty** [comment]
Pretty sure the actual fix here is https://github.com/craftcms/cms/pull/6274, or something like it.

**Comment by brandonkelly** [comment]
@timkelty this is fixed for you in 3.5 right?

**Comment by timkelty** [comment]
@brandonkelly just tested, yep – looks all good.

**Comment by timkelty** [comment]
Fixed by deprecation of `enabledForSite` and changes to status in 3.5
