### ISSUE TITLE
Extend docs with example how to add vimeo videos

### ISSUE THREAD

**Issue by Jones-S** [craftcms/redactor#238]
I realized that I had to extend the html purify settings to allow vimeo iframes.

Redactor itself (with the necessary settings) converts youtube and vimeo links into iframes.
So I extended the youtube iframe regex like this:
`"URI.SafeIframeRegexp": "%^(https?:)?//(www\\.youtube(?:-nocookie)?\\.com/embed/|(www\\.)?player\\.vimeo\\.com/video)%"`

I would suggest, that this is added somewhere in the readme, saving some people some time when trying to embed vimeo.

**Comment by brandonkelly** [comment]
Just released Redactor 2.8.7 with support for `www.youtube-nocookie.com` embeds, so you shouldn’t need to override `URI.SafeIframeRegexp` anymore.
