### ISSUE TITLE
"pasteLinks": false, is not working and links are still pasted and auto formatted into <a href> links

### ISSUE THREAD

**Issue by terryupton** [craftcms/redactor#240]
### Description
I am trying to restrict the ability to paste links into a redactor field.
Having tried this setting "pasteLinks": false, it isn't working and users can still paste in links to the redactor field. These get auto converted into `<a href=""></a>` links

```
{
  "buttons": [
    "html",
    "bold",
    "italic"
  ],
  "pastePlainText": true,
  "pasteLinks": false,
  "toolbarFixed": true
}
```

https://imperavi.com/redactor/docs/settings/paste/#s-pastelinks

### Steps to reproduce

1. Setup json code (as above) and use this redactor field
2. Copy a link/url and paste it into the field.
3. The link within the redactor field gets auto turned into a link (`<a href=""></a>`) rather than being pasted as plaintext.

### Additional info

- Craft version: Craft Pro 3.4.26
- PHP version: 7.2.31
- Plugins & versions: 2.6.1

**Comment by andris-sevcenko** [comment]
The redactor settings are a bit confusing.

You will probably want to [disable the autoparser](https://imperavi.com/redactor/docs/settings/autoparse/#s-autoparse), otherwise Redactor just ends up converting it all back to HTML :)
