### ISSUE TITLE
Redactor fields not saving inline styles for tables

### ISSUE THREAD

**Issue by nickolasjadams** [craftcms/redactor#241]
### Description
Despite the redactor fields being configured to keep inline styles, the tables plugin is working correctly, but when you save the entry, the inline styles are often removed.

### Steps to reproduce

1. Create a redactor field with the following advanced configuration and attach it to a section

> advanced
[ ]	Remove inline styles
[X]	Remove empty tags
[X]	Replace non-breaking spaces with regular spaces
[ ]	Purify HTML

2. Add the table and alignment plugins for redactor

{
  "plugins": ["table", "alignment"],
}

3. Create a table and try to make alignments to cells (whoops. mislabeled that first one)
![image](https://user-images.githubusercontent.com/15788998/86987950-6be7fa00-c154-11ea-905e-edd138669be3.png)
4. Cells will very rarely actually keep the correct inline styling on save.
    - Most of the cells strip out the styling
    - The styling that stays isn't on the correct cell
![image](https://user-images.githubusercontent.com/15788998/86988320-35f74580-c155-11ea-83c1-149241978331.png)

### Additional info
Resulting code after save
`<table><tbody><tr><td><p style="text-align: right;">left</p></td><td>right</td><td>center</td></tr><tr><td>center</td><td>left</td><td>right</td></tr></tbody></table>`

- Craft version: Craft Pro 3.4.3
- PHP version: 7.2.30
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
Redactor	2.4.0
Cloner	1.1.2
Contact Form	2.2.6
Contact Form Honeypot	1.0.2
Control Panel CSS	2.2.1
Control Panel JS	2.2.1
Control Panel Nav	3.0.12
Copy	1.0.0-RC9
CP Field Inspect	1.0.7
Entry Instructions	1.0.7
Field Manager	2.1.1
Image Resizer	2.0.6
Incognito Field	1.1.1.1
MatrixMate	1.2.5
Postmark	2.0.2
Store Hours	2.1.1.1
Super Table	2.4.4

**Comment by nickolasjadams** [comment]
Really wacky.  Copying and pasting a table from google docs makes craft save the alignment styles.
But using the redactor buttons is still not working.

Open up a word processor like Google Docs.
In the toolbar. Insert > Table

Type up your content here. Then copy and paste it into the website editor.
![image](https://user-images.githubusercontent.com/15788998/87098244-12d79f00-c204-11ea-9f94-fec42f913d46.png)

![image](https://user-images.githubusercontent.com/15788998/87098263-1f5bf780-c204-11ea-8d15-799039afc792.png)

Now use the alignment button

![image](https://user-images.githubusercontent.com/15788998/87098283-2d117d00-c204-11ea-931b-aef39b20e281.png)

It saves properly.

**Comment by nickolasjadams** [comment]
Created a fresh install.  Latest version of everything.  No other installed plugins. Just to make sure that wasn't my issue.

PHP version 7.2.30
MySQL 5.5.5
Craft Solo 3.4.27

Redactor | 2.6.1

Still saved the table without the inline styling.

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this. I'll cut a new release today (2.8.3) and if, after installing that, you still see this issue, please let me know.

**Comment by andris-sevcenko** [comment]
Correction - it will be next week and 2.9, not 2.8.3
