### ISSUE TITLE
Delete button does not work on images

### ISSUE THREAD

**Issue by jonathanpuc** [craftcms/redactor#244]
### Description
When trying to delete an image, it hides the element from the browser rather than actually deleting the HTML.

### Steps to reproduce

1. Add in in-line image.
2. Click the image.
3. Press delete.
3. Click on HTML tab and see <img> tag is still there.

### Additional info

- Craft version: 3.4.6
- Redactor version: 2.6.1

Loom video: https://www.loom.com/share/bdc46ccd82c348b890c33f5645c8ee7e

**Comment by brandonkelly** [comment]
We refactored how images are managed quite a bit in Redactor 2.7.0, and I’m not able to reproduce this there. Can you please try updating (requires Craft 3.5.0) and see if you’re still experiencing this?

**Comment by jonathanpuc** [comment]
> We refactored how images are managed quite a bit in Redactor 2.7.0, and I’m not able to reproduce this there. Can you please try updating (requires Craft 3.5.0) and see if you’re still experiencing this?

I'll give it a shot. Thanks.

**Comment by andris-sevcenko** [comment]
@jonathanpuc did it work?
