### ISSUE TITLE
Embedded video is saved with removing some parameters

### ISSUE THREAD

**Issue by Stalex89** [craftcms/redactor#245]
### Description

When inserting iframe with video from Vimeo with 'allowfullscreen' or "allow='autoplay; fullscreen'" parameter, it is removed by the HTML Purifier. Parameters as 'width', 'height', 'frameborder' are left untouched.

Maybe there is the same issue with Youtube videos, didn't test it. 

Is there a way to allow those parameters for HTML purifier?

### Steps to reproduce

1. Install redactor and enable video plugin for it
2. Insert iframe with 'allowfullscreen' or allow='autoplay; fullscreen' parameter
3. Save

### Additional info

- Craft version: Craft Pro 3.4.25
- PHP version: 7.2.32
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Redactor 2.6.1

**Comment by andris-sevcenko** [comment]
There's an [event](https://github.com/craftcms/redactor/blob/a6772463a332a5c8a535e31d4d27a9cbea09ed12/src/Field.php#L57-L74) for modifying the HTML purifier config.

However, we'll be moving away from HTML purifier towards Html Sanitizer as soon as possible, as purifier is rather clunky.
