### ISSUE TITLE
[Feature / Question] Default Config

### ISSUE THREAD

**Issue by OwenMelbz** [craftcms/redactor#247]
Currently we can add "additional" configs - which is 👍 

However when you're adding loads and loads of Redactor fields and always having to change the dropdown to your "default" it gets easily missed and a bit of a pain.

With that in mind, is it possible to set a default redactor config? e.g. maybe it could look for `config/redactor/Default.json` and use that if found, unless there is another way?

Thanks

**Comment by brandonkelly** [comment]
Great idea! Just released Redactor 2.7.0 which adds this feature.
