### ISSUE TITLE
Preventing line breaks on paste won't add needed space

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/redactor#248]
### Description
A couple issues that are all related to the same problem: preventing line breaks on paste.
Not sure if it is related to the Craft plugin or to the core of Redactor.

#### Issue 1

Per redactor docs about the `enterKey` Setting: 
"With this set to 'false' and `pastePlainText` is set to true, line breaks will be **replaced by spaces**." (emphasis mine).

So the following config:
```
{
  "enterKey": false,
  "pastePlainText": true
}
```

Should transform this code:
```
<p>
Sentence 1.<br><br>
Sentence 2.
</p>
```

Into this code on paste:
```
<p>
Sentence 1. Sentence 2.
</p>
```

But the space between Sentence 1 and Sentence 2 is not getting added.

#### Issue 2

Somehow related to the previous issue, I would argue that paragraphs should be under the same circonstances treated the same way as issue 1. Take the same config with this code:

```
<p>Paragraph 1.</p>
<p>Paragraph 2.</p>
```

I would expect the following result:
```
<p>
Paragraph 1. Paragraph 2.
</p>
```

But get this instead:
```
<p>
Paragraph 1.<br><br>
Paragraph 2.
</p>
```

I can somehow mitigate this issue by restricting the `br` and `p` tags via the `pasteInlineTags` and `pasteBlockTags` settings:
```
{
  "enterKey": false,
  "pastePlainText": false, // needs to be false or pasteInlineTags and pasteBlocTags won't apply
  "pasteBlockTags": [], // removes p tag
  "pasteInlineTags": [] // removes br tag
}
```

But it feels like a hack and doesn't help with that space that still needs to be added.

### Additional info

- Craft version: Latest (3.5)
- Plugins & versions: Latest

**Comment by palomamtnez** [comment]
@JeanLucEsser were you able to solve it:)?

**Comment by JeanLucEsser** [comment]
Nope, I gave up at the time, I need to check if the issue is still there.
Will try and find time this WE to get back to you on the subject.

**Comment by andris-sevcenko** [comment]
Craft passes the Redactor settings straight through to Redactor, so this is on how they interpreted the settings.

Looking at Redactor's code, 
* disabling `enterKey` will simply suppress the event, so it has nothing to do with pasting. It just prevents the user from hitting the enter key.
* Enabling `pastePlainText` will replace all newlines with the `<br>` tag for some reason.
* The other two settings effectively disable _any_ HTML tags.

You can probably use your first approach and on output run this through a Twig replace filter that replaces `<br>` with `\n`.
