### ISSUE TITLE
Automatic site-link detection

### ISSUE THREAD

**Issue by Mosnar** [craftcms/redactor#249]
### Description
Redactor should be able to detect if a link is one that matches a site on the Craft installation - if it does, it should attempt to lookup the URL to determine if an entry exists. If the entry exists, the link URL should be modified to include the reference tags to the entry in question.

Content is very often pasted from a document with links embedded. This is usually the case for us since the content writing process always occurs externally and goes through several stages of approvals before being pasted into the CMS - at this point, most content entry people don't think or care to relink all of the internal links in the article to entries in the CMS.

**Comment by andris-sevcenko** [comment]
Alright, just added this for the next Redactor release. Joy!

**Comment by brandonkelly** [comment]
Redactor 2.9.0 is out now with this ✨
