### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by woeye** [craftcms/redactor#25]
The documentation link on the README.md is incorrect because it points to the new version 3 of Redactor. Because of the many changes (https://imperavi.com/redactor/docs/get-started/upgrade-from-2-to-3/) the settings described there won't work with the current Redactor's version of this plugin. 

It also seems that the documentation for Redactor 2 is no longer available on Imperavi's website.

**Comment by brandonkelly** [comment]
We just released v2.0.0, which is now powered by Redactor 3, so this problem has sorted itself out :)
