### ISSUE TITLE
Support AddAttribute in purifier config

### ISSUE THREAD

**Issue by phillipdaviesdeveloper** [craftcms/redactor#251]
### Description

Cannot set undefined directive HTML.AddAttribute to value invoked on line 837 in file /var/www/html/vendor/craftcms/redactor/src/Field.php

You can configure HTML purifier with your own custom configuration, however, this JSON blob approach does not allow you to use the AddAttribute customisation directive. As HTML purifier does not support data- attributes this means any data attributes you set are always stripped and cannot be added to the allowed attributes configuration.

To resolve the issue, and other related issues, it would be great to be able to add supported attributes as per their configuration docs here: http://htmlpurifier.org/docs/enduser-customize.html

**Comment by andris-sevcenko** [comment]
As of Redactor 2.6, it' possible to configure Html purifier [using events](https://github.com/craftcms/redactor/commit/d3e1f6cb9e9de20f515be8505ce264c341d99aa2) - note that we are aiming to replace Html purifier with Html sanitizer Symfony package with Craft 4 release.
