### ISSUE TITLE
Field's asset source in the Redactor field setting disappeared

### ISSUE THREAD

**Issue by chanwhab** [craftcms/redactor#254]
### Description
After Updating to v2.7, i cannot no longer select the field's asset source from the field setting
![Screenshot 2020-08-13 at 2 17 15 AM](https://user-images.githubusercontent.com/7658690/90052358-99076980-dd0b-11ea-97a5-db14e11cb974.png)

### Steps to reproduce
 1.
2.

### Additional info

- Craft version: 3.5.3
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Plugins & versions: v2.7

**Comment by andris-sevcenko** [comment]
Wow. Sorry! Fixed for the next release coming soon!

**Comment by brandonkelly** [comment]
Redactor 2.7.1 is out now with the fix for this.
