### ISSUE TITLE
AWS image assets disappear on save with Craft 3.5.3 and Redactor 2.7.0

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/redactor#255]
### Description
After updating to Craft 3.5.3 and Redactor 2.7.0, images assets (coming from AWS S3 bucket) are disappearing on save, but show properly prior to saving.

### Steps to reproduce

1. Use the "Image" toolbar button to add an image from the asset library
Note: Prior to saving, HTML looks like this and displays properly:
`<figure><img src="https://awlefffelksajf.cloudfront.net/default/my_image.png?mtime=20200812134807&focal=none#asset:3997:url" data-image="3997" style="opacity: 1;"></figure>`

2. Save entry
Note: After saving, HTML looks like this and does not display in the CP or site front end:
`<figure><img src="{asset:3997:url||https://awlefffelksajf.cloudfront.net/default/my_image.png}?mtime=20200812134807&focal=none" data-image="3yh14ojuck5l"></figure>`

### Additional info

- Craft version: 3.5.3
- PHP version: 7.3.8
- Database driver & version: MySQL v5.7.26
- Plugins & versions: craftcms/redactor v2.7.0, craftcms/aws-s3 v1.2.9

If it's helpful at all, the URL attempting to load from the CP and hitting a 404 after saving looks like this:
`https://local.my_site.com/manage/entries/landingPages/%7Basset:3997:url%7C%7Chttps://awlefffelksajf.cloudfront.net/default/my_image.png%7D?mtime=20200812134807&focal=none`

**Comment by brandonkelly** [comment]
Thanks for reporting that! Redactor 2.7.1 is out now with a fix.
