### ISSUE TITLE
Craft character limit and counter for Redactor RTF

### ISSUE THREAD

**Issue by ghost** [craftcms/redactor#256]
It would be nice to have the ability to set character limits with the counter like in plain text fields for RTF.

Currently, it's only possible to set character limit per Redactor config, that starts to being messy with few fields with different limits (with [limiter](https://imperavi.com/redactor/plugins/limiter/) plugin).

Also, Redactor [counter](https://imperavi.com/redactor/plugins/counter/) plugin doesn't work for me at all, though even if it would work, having counted character amount is not so oblivious like having left characters counter.

**Comment by brandonkelly** [comment]
😬

**Comment by pette87** [comment]
Same issue. 

JSON Config:

```
{
  "buttons": ["html", "bold", "italic"],
  "plugins": ["fullscreen", "limiter", "counter"],
  "linkNewTab": true,
  "toolbarFixed": true,
  "limiter": 235
}
```

In backend no display counter and no limit

**Comment by brandonkelly** [comment]
Just released Redactor 2.7.3 which fixes this.

**Comment by pette87** [comment]
It works now 👍 
Thank you very much :)

**Comment by samuelreichor** [comment]
Still having the same issue.. I have put the js file in config/redactor/plugins and that is my config:

{
  "plugins": [
    "limiter"
  ],
  "toolbarFixed": true,
  "limiter": 20
}
