### ISSUE TITLE
bullets of lists are not visible if uiMode is enlarged

### ISSUE THREAD

**Issue by nflorentin** [craftcms/redactor#262]
Hi,

I don't know if it is a bug or a feature but feel free to close the issue if it is not a bug.

If you set a redactor field uiMode to "enlarged", the css class "readable" is removed from the wrapper div.class=redactor in the form of the entry, in the Control Panel. Therefore, the bullets of the lists are not visible anymore. I don't know if there is other consequences.

By the way, I don't understand the difference between enlarged and normal mode, is there a documentation for that ?

Thanks you for your awesome work!

**Comment by brandonkelly** [comment]
Just released Redactor 2.7.3 which fixes this. Thanks for reporting!

**Comment by brandonkelly** [comment]
> By the way, I don't understand the difference between enlarged and normal mode, is there a documentation for that ?

Just changes the size of the field. Traditionally it’s always been “Enlarged”, but you can change to “Normal” to shrink the field down to match the padding/font sizes of normal Plain Text fields.

**Comment by nflorentin** [comment]
Thank you so much for your reactivity and your explanation!

**Comment by carlcs** [comment]
@brandonkelly there’s still issues with lists, please see #266
