### ISSUE TITLE
Translate redactor plugins

### ISSUE THREAD

**Issue by itrlink** [craftcms/redactor#263]
Hello! Can you help me? How i can translate plugins? sample fontsize. Thanks

**Comment by andris-sevcenko** [comment]
The best would be to open a PR with the translation strings added to the relevant JS file. In your example, that would be https://github.com/craftcms/redactor/blob/main/lib/redactor-plugins/fontsize/fontsize.js.

Once that's in, we'll review it, re-build the Redactor and add it to the next release.

Also, it will happen much faster than me taking the time to answer to this issue - sorry about that!
