### ISSUE TITLE
Redactor 2.2 unordered list not showing bullets

### ISSUE THREAD

**Issue by angrybrad** [craftcms/redactor#264]
### Description

The proper markup is generated when viewing source, but no bullets are showing in the front-end view.

![2017-02-27_11-09-54](https://cloud.githubusercontent.com/assets/61869/23375477/662d421c-fcdd-11e6-87c4-c20803141c07.png)

### Steps to reproduce

1. Run Redactor 2.2
2. Create an unordered list.
3. Revel in the nothingness.

### Additional info

- Craft version: 2.x and 3.x
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
@paulgoodfield That was already reported in #262. We just released Redactor 2.7.3 with a fix.
