### ISSUE TITLE
Redactor "onbutton.observe" event stops working if button is disabled

### ISSUE THREAD

**Issue by ken-gladeye** [craftcms/redactor#265]
### Description
I made a plugin that observe changes in the editor, and enable / disable the button depending on the type of the block that has been selected.

It used to work in version `2.6` but not in `2.7`

I followed the same [`onbutton.observe` pattern in `redactor/widget` plugin](https://github.com/craftcms/redactor/blob/v2/lib/redactor-plugins/widget/widget.js#L87)

Note that if I don't disable the button, then the `onbutton.observe` event works fine.

### Steps to reproduce

1. Create a `ctaButton` plugin with the following code
```
// ctaButton.js
(function ($R) {
  $R.add("plugin", "ctaButton", {
    translations: {
      en: {
        ctaButtonOff: "Link: CTA Button",
        ctaButtonOn: "Link: Normal",
      },
    },
    init(app) {
      this.cssClass = "cta-button";
      this.app = app;
      this.lang = app.lang;
      this.toolbar = app.toolbar;
      this.inspector = app.inspector;
      this.selection = app.selection;
    },
    start() {
      const $button = this.toolbar.addButton("ctaButton", {
        title: this.lang.get("ctaButtonOff"),
        api: "plugin.ctaButton.toggle",
        observe: "ctaButton",
      });

      $button.disable();
    },

    onbutton: {
      ctaButton: {
        observe(button) {
          this._observeButton(button);
        },
      },
    },

    toggle() {
      const block = this.selection.getBlock(),
        inline = this.selection.getInline(),
        data = this.inspector.parse(inline);

      if (!inline || !data.isLink()) return;

      block.classList.toggle(`${this.cssClass}-container`);
      inline.classList.toggle(this.cssClass);
    },

    _observeButton(button) {
      const inline = this.selection.getInline(),
        data = this.inspector.parse(inline);

      if (!inline || !data.isLink()) return button.disable();

      button.setTitle(
        this.lang.get(inline.classList.contains(this.cssClass) ? "ctaButtonOn" : "ctaButtonOff")
      );

      button.enable();
    },
  });
})(Redactor);
```
2. Activate the plugin on a Redactor field
3. Create a link in the Redactor field

Expected Behaviour:
- The `Link: CTA Button` should appear if cursor is on the link

Actual Behaviour:
- The `Link: CTA Button` doesn't appear

### Additional info

- Craft version: Craft Pro 3.5.7
- PHP version: 7.2.11
- Database driver & version: MySQL  5.5.5
- Plugins & versions: 2.7.3

**Comment by Mmasson-01** [comment]
Having issues with observe as well. Working fine on version 2.6.x.
Updated today to latest version and my plugins relying on the observer were broken

**Comment by andris-sevcenko** [comment]
Is there any proper documentation about observe? Redactor docs aren't very helpful, as far as I can tell.

**Comment by ken-gladeye** [comment]
@andris-sevcenko no such proper documentation afaik unfortunately, I only discovered that API by looking at the existing [widget plugin](https://github.com/craftcms/redactor/blob/v2/lib/redactor-plugins/widget/widget.js#L72-L79)

**Comment by andris-sevcenko** [comment]
Well, that's strange. Unfortunately, it's hard for me to fix this because I have no idea what should be going on, which is usually the case when using undocumented APIs.

@ken-gladeye Since you only care when links get clicked, maybe you can tap into an also undocumented, yet more understood, API - https://github.com/craftcms/redactor/blob/v2/lib/redactor-plugins/widget/widget.js#L50 ?

The contextbar would appear when clicking a link, so seems like as good of a hook.

@Mmasson-01 does that sound like something you could also do?

**Comment by ken-gladeye** [comment]
@andris-sevcenko thank you your suggestions, found a reliable fix to work around this so all good.

@Mmasson-01 i find the `observe` event is working fine as long as you don't call ".disable()" method on the button, hope that little fact helps with your case.

**Comment by Mmasson-01** [comment]
We've upgraded to **2.8.7** and the regression is not happening anymore with the `.disabled()` method.

Quick follow up in case someone get the same behavior.
