### ISSUE TITLE
List margins are broken

### ISSUE THREAD

**Issue by diluno** [craftcms/redactor#266]
### Description

`body .redactor-box .redactor-styles ol, body .redactor-box .redactor-styles ul {
    margin: 1em 0;
}`
This margin from 'node_modules/craftcms-sass/_mixins.scss' is breaking the display of lists in redactor fields:
<img width="241" alt="Screenshot 2020-08-31 at 16 44 42" src="https://user-images.githubusercontent.com/2156626/91732997-4ce07400-eba9-11ea-87fe-92f1a3037485.png">

### Steps to reproduce

1. Create list in redactor field

### Additional info

- Craft version: Craft Pro 3.5.7
- PHP version: 7.4.8
- Database driver & version: MySQL 8.0.21
- Plugins & versions: Redactor 2.7.3

**Comment by carlcs** [comment]
There’s also an issue with nested lists. And when using “normal” UI mode, markers are not visible at all.

**Comment by brandonkelly** [comment]
Sorry, that has been fixed in Redactor 2.7.4.
