### ISSUE TITLE
Redactor Air Low Button Contrast

### ISSUE THREAD

**Issue by bradlilley** [craftcms/redactor#271]
### Description

When using the air toolbar on redactor fields the button icons are difficult to see due to low contrast. This issue is worse when when considering those with accessibility needs.

![Screen Shot 2020-09-17 at 2 37 22 PM (2)](https://user-images.githubusercontent.com/1869849/93521075-19b21a80-f8f5-11ea-84bb-a74e5c37c41f.png)

### Steps to reproduce

1. Create a Redactor field.
2. Add the `"air": true` option to either the simple or standard Redactor config.

**Simple.json**
```
{
  "buttons": ["bold", "italic", "deleted", "underline", "link"],
  "air": true,
  "toolbarFixed": true
}
```
### Additional info

- Craft version: 3.5.10.1
- PHP version: 7.3.18
- Database driver & version: PostgreSQL 12.4
- Plugins & versions: Redactor 2.7.4

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed this for the next release.

**Comment by brandonkelly** [comment]
2.7.5 is out now with that fix.

**Comment by bradlilley** [comment]
Thank you for the quick fix. I'll be using it in my current project.
