### ISSUE TITLE
Mysterious dissapearing of links since Craft 3.5.x/Latest Redactor Plugin version(s)

### ISSUE THREAD

**Issue by bencresty** [craftcms/redactor#272]
### Description
After having entered lots of external links suddenly links dissapear. They are still shown as links, but when clicking on them inside Redactor to edit them the popup-menu shows 'null | edit | unlink' (so adds 'null') and when clicking on 'edit' the fields of url and title are empty. These links were definitely entered the right way and checked afterwards and were just fine.

[edit] The links doesn't even seem to make it to the code when clicking 'Save' on the link edit form. The interface shows the link, but when editing everything the link by clicking on 'edit' everything inside the link is gone.

Sometimes this issue can be recovered by re-entering the data in the link editform, but other times a link cannot even be recovered after tenths of tries by editing the link again and than it can only be done with a manual edit in the code-view of Redactor. Can't find any logic on when a link throws an issue, when the link keeps on throwing the issue and when there will be no problem.

![image](https://user-images.githubusercontent.com/69322733/94365877-b5e9d780-00d4-11eb-81ad-d6a8a181ff5e.png)

![image](https://user-images.githubusercontent.com/69322733/94365886-c306c680-00d4-11eb-9c58-91b40952ed6a.png)

### Steps to reproduce

No clue on why and when this happens. It seems completely random. Never had this issue on Craft 3.4.30 though, so it seems either Craft 3.5.x related or related to on of the latest Redactor versions available for the 3.5.x upgrade.

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5
- Redactor Plugin version: 2.7.5
- Redactor Anchors Plugin version: 1.1.0

**Comment by brandonkelly** [comment]
Redactor 2.8.1 is out now with a fix for this. Thanks for reporting!

**Comment by bencresty** [comment]
@brandonkelly Just did a quick test before and after upgrading the plugin. Immediately saw the issue before upgrading and didn't see the issue when doing the same things after upgrading to 2.8.1.

Unfortunately this issue was seemed very random and I couldn't find logic to it before, so for me it's hard to tell if it's completely fixed or just was working this once as some were working before and some didn't. But it looks promising. 

Was it a known issue with Redactor as far as you know and did they fix it?

Either way; Thanks for the quick action!
