### ISSUE TITLE
Link title text between double quotes got removed when click 'edit' on link / Escape issues link edit form

### ISSUE THREAD

**Issue by bencresty** [craftcms/redactor#273]
### Description

When entering double quotes on a link title at first it looks like it's working fine when saving the link; The link gets inserted fine, shows the right title in the Redactor code-view with the quotes escaped as expected. 

But when editing the link the Title-field has changed (also in the Redactor code-view) and now suddenly has doublequote-escape-issues; causing adding of unwanted attributes to the anchor-tag in html because of the double quote.

### Steps to reproduce

see above

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5
- Redactor Plugin version: 2.7.5
- Redactor Anchors Plugin version: 1.1.0

**Comment by olivierbon** [comment]
@bencresty could you update to latest (`2.8.1`) and see if that helps, please?

**Comment by bencresty** [comment]
@olivierbon just did a quick test before and after upgrading to 2.8.1 to see if it changes. Couldn't replicate the double quote issue before upgrading now, because at first the other issue was in the way (https://github.com/craftcms/redactor/issues/272) so the complete link-fields were emptied again after re-editing the set link with double quotes in the title. And the second time it worked with the old version for some weird reason when using double quotes.
Not sure why it does work one time and doesn't the other time. Doesn't make sense to me at all.

So couldn't replicate it now before the upgrade. After the upgrade I still see it working, but not sure if something really fixed this 'random' issue or not. Guess time will tell.

**Comment by andris-sevcenko** [comment]
Closing this, then!
