### ISSUE TITLE
Copy/Paste of YouTube Embed Code: Removes Iframe

### ISSUE THREAD

**Issue by Enijar** [craftcms/redactor#277]
### Description

Copy/pasting a YouTube embed code removes the `<iframe/>` and replaces it with an empty `<figure/>` element.

### Steps to reproduce

1. Copy/paste `<iframe width="560" height="315" src="https://www.youtube.com/embed/RpMYjjZWxrc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>` into the `video` plugin modal for Redactor
2. Save the page
3. Video embed code is removed from HTML

### Additional info

- Craft version: 3.5.5
- PHP version: 7.4.11
- Database driver & version: MySQL 8.0.19
- Plugins & versions: Redactor 2.7.1

**Comment by iamkeir** [comment]
We are experiencing this too. I double-checked to see if we had any rogue `HtmlPurifier` settings in our config [based on this advice](https://craftcms.stackexchange.com/questions/13924/redactor-video-plugin-not-working), but nope.

**Comment by iamkeir** [comment]
I take that back, I was looking for a `HtmlPurifier` config, whereas it is actually a checkbox against the specific field settings:

![screenshot_622](https://user-images.githubusercontent.com/539615/95784990-d321c700-0ccc-11eb-9397-e601bbdc690a.png)

@Enijar maybe check that? Unticking it worked for me.

**Comment by Enijar** [comment]
Yes that was the solution but according to the docs the config/htmlpurifier/*.json file overrides that config. Unless I'm reading the docs wrong then this is still a bug AFAIK

**Comment by cyress** [comment]
I've noticed similar behavior when inserting a YouTube link through the redactor "video" plugin.
The preview of the video appears first, but the code is removed when saving the entry.

Maybe the following regex-rule is causing the problem. `%^https?://(www.youtube.com/embed/|player.vimeo.com/video/)%`
https://github.com/craftcms/redactor/blob/v2/src/Field.php#L1019

The rule expected that the url start with http or https and the generated iframe markup use a protocol-less url.
`<iframe style="width: 500px; height: 281px;" src="//www.youtube.com/embed/Ftm2uv7-Ybw" frameborder="0" allowfullscreen=""></iframe>`

The protocol part including the colon should be optional. Something like this.
`%^(https?:)?//(www.youtube.com/embed/|player.vimeo.com/video/)%`

And maybe it is possible so support the YouTube-nocookie domain as well like recommended in this [here](https://craftcms.stackexchange.com/questions/20133/html-purifier-config-file/20140#20140).

**Comment by brandonkelly** [comment]
> And maybe it is possible so support the YouTube-nocookie domain as well like recommended in this [here](https://craftcms.stackexchange.com/questions/20133/html-purifier-config-file/20140#20140).

Redactor 2.8.7 is out now with support for `www.youtube-nocookie.com`.
