### ISSUE TITLE
Cannot get formattingAdd to apply custom formats to text

### ISSUE THREAD

**Issue by rhyshalsey** [craftcms/redactor#28]
I have been trying to add some formatting specific to my website by using the "formattingAdd" option, as documented here : https://imperavi.com/redactor/docs/settings/formatting/#s-formattingadd All the other options seem to work fine. 

Here is my code in the /config/redactor/Advanced.json file : 
```{
  "buttons": [
    "formatting",
    "bold",
    "italic",
    "unorderedlist",
    "orderedlist",
    "link",
    "image",
    "video"
  ],
  "plugins": [
    "source",
    "fullscreen",
    "video",
    "alignment"
  ],
  "toolbarFixed": true,
  "imagePosition": true,
  "imageFloatMargin": true,
  "imageResizable": true,
  "formattingAdd": {
    "green title": {
      "title": "Green header 1",
      "api": "module.block.format",
      "args": {
        "tag": "h1",
        "class": "coriandr-green-text",
        "type" : "toggle"
      }
    }
  }
}
```
The item appears in the formatting dropdown menu : 
![image](https://user-images.githubusercontent.com/13952823/39205586-17ae1b38-47c9-11e8-9f5b-587e7291be69.png)

However, when I try to click on that button, I get the following error : `Cannot read property 'toLowerCase' of undefined`. Here is the stacktrace : 
```
redactor.js:5697 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at init.arrangeTag (redactor.js:5697)
    at init.format (redactor.js:5429)
    at init.clickCallback (redactor.js:2026)
    at init.toggle (redactor.js:1988)
    at init.buildClick (redactor.js:3946)
    at init.<anonymous> (redactor.js:3926)
    at HTMLAnchorElement.i (jquery.js:496)
    at HTMLAnchorElement.dispatch (jquery.js:5206)
    at HTMLAnchorElement.v.handle (jquery.js:5014)
```

Is this an issue with the Redactor itself, or with the Craft plugin? Or is there an issue with the format of my configuration in the JSON file?

**Comment by rhyshalsey** [comment]
After digging some more, I realize now this is due to the fact that this plugin bundles Redactor 2 and not Redactor 3. I was following the documentation for Redactor 3. The config should look like so instead : 
```
{
  "buttons": [
    "formatting",
    "bold",
    "italic",
    "unorderedlist",
    "orderedlist",
    "link",
    "image",
    "video"
  ],
  "plugins": [
    "source",
    "fullscreen",
    "video",
    "alignment"
  ],
  "toolbarFixed": true,
  "imagePosition": true,
  "imageFloatMargin": true,
  "imageResizable": true,
  "formattingAdd": {
    "green-title-1": {
      "title": "Green header 1",
      "api": "module.block.format",
      "args": ["h1", "class", "coriandr-green-text", "toggle"]
    }
  }
}
```

**Comment by Thirdwrist** [comment]
Hello @rhyshalsey You just saved me some days. 

Please any luck to get the documentation for this? I cannot seem to find where to get version two. I am currently using v2.1 

I am stuck on how to add other attributes like **ID** and more...

Kindly help...

**Comment by Yazan-Muallla** [comment]
Hey @Thirdwrist, did you find a way to add ID attributes?
