### ISSUE TITLE
The table is deleted when the delete key is pressed instead of placing the cursor at the beginning of the table.

### ISSUE THREAD

**Issue by TomHell** [craftcms/redactor#281]
### Description
The table is deleted when the delete key is pressed instead of placing the cursor at the beginning of the table. The same problem exists if I remove the line below the table which will also remove the table as well.
This problem has been fixed in Redactor 3.4.5 but is not available for CraftCMS yet.

When does the new Version 3.4.5 of Redactor will be implemented to fix this issue?

### Steps to reproduce

1. Create a field of type Redactor and use ie. Simple for configuration.
2. Enable the table plugin for field like so:
  * open  /config/redactor/Simple.json and add this line `"plugins": ["table"]`
3. go to your backend field and **add**: **text, table, text**
4. position cursor at the beginning of the first line and click DEL to remove the chars
5. now it will also remove the table at the end instead of removing the line and jump to the fist table cell as you can test it here in the demo: [Redactor Demo](https://imperavi.com/redactor/)

### Additional info
- Bug report has been fixed in Redactor version 3.4.5. (https://imperavi.com/redactor/log/)
---
- Craft version: 3.5.14
- PHP version: 7.4
- Database driver & version: MySQL
- Plugins & versions: Redactor Plugin 2.8.3

**Comment by TomHell** [comment]
Is there any update or can I find this on your road map?

**Comment by andris-sevcenko** [comment]
Thanks for the reminder! I'll try to get a Redactor version update out today!

**Comment by andris-sevcenko** [comment]
Just cut a release to address this!
