### ISSUE TITLE
Redactor Toolbar loses fixed position after closing preview mode

### ISSUE THREAD

**Issue by riekusdn** [craftcms/redactor#282]
**Description**
When previewing an entry, then closing the preview mode, all instances of the redactor toolbar lose their fixed position upon scrolling.

**Steps to reproduce:**
1. Open an entry in the CMS
2. Scroll, see the redactor toolbar(s) taking a fixed position
3. Preview the entry
4. Close preview
5. Scroll again, see the redactor toolbars(s) not taking a fixed position (the `redactor-toolbar-fixed` CSS class is missing by now)

**Additional info**

PHP version | 7.2.29
Linux 4.19.76-linuxkit
MySQL 5.7.31
Craft Pro 3.5.12.1
Redactor | 2.8.1
Browser: Chrome Version 86.0.4240.111 (though also reported by clients using MS Edge)

**Comment by darylknight** [comment]
+1, just ran into this myself. Works before opening Preview, works during Preview. Once you close the pane, the toolbar is positioned in the wrong place (screenshot attached) and isn't sticky anymore

![image](https://user-images.githubusercontent.com/1250017/102082790-39d17700-3e1b-11eb-97f4-ba2252b03324.png)

PHP 7.4.10
Craft 3.5.16
Redactor 2.8.5

**Comment by lenvanessen** [comment]
+1 also having issues with this, but right now when you create a draft and only after save and refresh it's sticky.

**Comment by JoshCoady** [comment]
@brandonkelly I have tracked this down to an exception being thrown at line 417 in RedactorOverrides.js when the preview is closed.

Looks like something about this causes `distanceFromScreenTop` to become fixed at a positive number and it no longer changes while scrolling. Perhaps `this.livePreview` never gets set back to `false` due to the exception and so it is still calculating based on the preview?

`417: var toolbarService = $R['services']['toolbar'];`

> Uncaught TypeError: Cannot read property 'createDocumentFragment' of undefined
>     at xe (jquery.js:5008)
>     at Oe (jquery.js:6059)
>     at b.fn.init.append (jquery.js:6250)
>     at b.fn.init.b.each.b.fn.<computed> [as appendTo] (jquery.js:6384)
>     at Object.handler (RedactorOverrides.js:417)
>     at s.constructor.trigger (garnish.js:836)
>     at s.constructor.close (Preview.js:413)
>     at s.constructor.<anonymous> (garnish.js:889)
>     at HTMLButtonElement.o (jquery.js:10780)
>     at HTMLButtonElement.dispatch (jquery.js:5430)

Any idea on a timeline when this might get fixed?

**Comment by JoshCoady** [comment]
If this the same exception as in #329 then that fix may fix this as well

**Comment by andris-sevcenko** [comment]
Sorry for the delay, sir. Just cut the 2.8.8 release that should, indeed, fix this!

**Comment by darylknight** [comment]
No worries! Thank you :)
