### ISSUE TITLE
Youtube embed doesn't work when the no cookie option is selected

### ISSUE THREAD

**Issue by markwijsman** [craftcms/redactor#289]
### Description
Youtube video iframe is cleared out when using privacy mode 

`<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/LXb3EKWsInQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

### Steps to reproduce

1. When generating an embed link for a youtube video select "Privacy mode"
2. Enter the iframe in redactor
3. Upon saving it clears out the iframe 

### Additional info

- Craft version:  Craft Pro 3.5.16
- PHP version:7.3.9
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Redactor 2.8.3

**Comment by andris-sevcenko** [comment]
This [has been fixed](https://github.com/craftcms/redactor/commit/3fc897527314502cdf7d43bd7a9a0f1d508ddc83) in Redactor 2.8.7!
