### ISSUE TITLE
Content of entry being replaced

### ISSUE THREAD

**Issue by watchwood** [craftcms/redactor#291]
### Description

On a couple specific entries we're seeing the content of our redactor fields being replaced entirely - the only notable clue is that in one entry the following replacement contents have been observed:

"xtagstartzsection class="highlight highlight-secondary" &gt;"

I don't recognize the 'xtagstartz' bit, though the rest of it appears to be our code.  That's the entire contents of that field, replacing what was in it previously.  Does anyone have any idea where it's coming from?

The really unusual thing is that the entry it still serving normally out of the database on the front end.  Whatever is happening appears to be happening to the entry as it's loaded into the admin panel.

### Steps to reproduce

1. Create an entry.  
2. Save the entry
3. Open the entry edit page in the admin panel

**Comment by jishi** [comment]
I found the culprit. Someone had managed to paste `<a href="mailto:<some@example.org>">` into the redactor field, which causes it to insert that `"xtagendz` placeholder.

**Comment by brandonkelly** [comment]
@jishi Interesting… sounds like a Redactor.js bug. Can you try updating the plugin to the latest version to see if Redactor.js 3.4.6 fixes it?

**Comment by jishi** [comment]
I will upgrade and report back.

**Comment by jishi** [comment]
Tested with latest redactor, still the same issue. This is not only a copy paste issue, because defining the link URL with `mailto:<test@example.org>` triggers the same behavior:

![image](https://user-images.githubusercontent.com/3165475/101050588-d62a8c80-3584-11eb-8ce3-0800cff8b730.png)

**Comment by jishi** [comment]
Some more testing concludes that I can't find any mention of valid mail syntaxes in mailto: links, but at least gmail do support having `mailto:"my name" <email>` syntax and it will correctly address the email with a name to it, however, it only work on first save, on subsequent saves, redactor will obfuscate that markup to something like this:

`<a href="mailto:" test="" name"="" &lt;test@example.org&gt;"="">test</a>` which seems completely bonkers.

**Comment by brandonkelly** [comment]
`mailto` is a URL scheme just like `http` and `https`. The correct syntax is `href="mailto:test@example.org"`. Gmail may be able to interpret incorrect syntaxes because it’s in their interest to be as forgiving as possible, but browsers wouldn’t know what to do with `mailto:<test@example.org>`, etc.

**Comment by andris-sevcenko** [comment]
Closing this as the `xstarttagz` and `xtagendz` are Redactor proprietary placeholders. If they are not being replaced back to `<` and `>`, check the browser console for JS errors.

Also, as @brandonkelly noted, `mailto` is pretty strict :)
