### ISSUE TITLE
Links break when propagating under specific conditions

### ISSUE THREAD

**Issue by tim-van-dijkhuizen** [craftcms/redactor#292]
### Description
Recently the way entry links are stored got changed so that links include their original URL. The old format still works fine until the entry gets propagated to a new site, then you see a HTML encoded version of the tag.

Entry in primary site (working link):
![image](https://user-images.githubusercontent.com/14998282/101048331-d164d900-3582-11eb-9f5b-0529b8ad8565.png)

Entry in new site (broken link):
![image](https://user-images.githubusercontent.com/14998282/101048450-eb9eb700-3582-11eb-8812-f60813801c7e.png)

While trying to reproduce this bug I found out that this bug only occurrs when the target entry is in a section that isn't enabled yet. So the target entry needs to be in another section that has not yet been enabled by the time the referencing entry is being propagated.

### Steps to reproduce

1. Existing entry with a redactor link that references another section (old link format).
2. Create a new site and enable the section that contains the source entry.
3. Wait until the source entry has been propagated to the new site.
4. Enable the section that contains the target entry.
4. Open the source entry and you will see a broken link.

### Additional info

- Craft version: 3.5.16
- PHP version: 7.2.18
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
   - Redactor 2.8.4

**Comment by TimvanDijkhuizen** [comment]
To simulate an existing entry I've created a new entry and remove the new ||url part from the redactor field content in the content table.

**Comment by andris-sevcenko** [comment]
@tim-van-dijkhuizen I can reproduce this locally, however, here's my understanding and, please, correct me if I'm wrong.

If you add a site-agnostic URL in the old syntax with no fallback to an entry, that is not available on some sites:
* on sites where the entry is available, the URL is resolved
* on other sites, you get the unresolved `{entry:ID:url}` as the URL

If the entry at any point in time becomes available, the element reference is resolved and a correct URL is displayed (as element refs are parsed on display time).

So, given all of that is true and there are points in time where you can get the element reference displayed unparsed - what would be the optimal resolution for this? Resolve it to an empty string?

I appreciate the fact that you opened this issue a while ago and I've been incredibly slow to respond, but I'd be happy if you could provide with a desired solution, given the fact that you are the person originally hit by this.

**Comment by tim-van-dijkhuizen** [comment]
@andris-sevcenko From what I remeber the links would stay broken, even if the target section was enabled later. So I would end up with HTML encoded links everywhere.

This problem occurred on a project where we would create a new site for each year. Then, if we enabled the sections in the wrong order a lot of links would get corrupted.

I don't work for the same company anymore, so unless there are more bug reports you can close this.

**Comment by andris-sevcenko** [comment]
I like that attitude!

And so, I'm closing this. Let me know if anything changes!
