### ISSUE TITLE
Image Button disappears in 2.8.4

### ISSUE THREAD

**Issue by strandofgenius** [craftcms/redactor#293]
### Description
The button for adding an image worked in `2.8.3` and disappears after updating to `2.8.4`. I tried Default.json as well as other custom Redactor JSON files.
`"buttons": ["html", "formatting", "bold", "italic", "deleted", "unorderedlist", "orderedlist", "link", "file", "image"],`

**Comment by petertindemans** [comment]
Same here, custom configs are not applied anymore. It will show the default settings.

**Comment by andris-sevcenko** [comment]
Yeesh. Just fixed this for the next release due today - just a little polish before I cut the release.
