### ISSUE TITLE
"Indent" button not appearing

### ISSUE THREAD

**Issue by cherrykoda** [craftcms/redactor#296]
### Description
Adding "indent" to the buttons list does not work, however "outdent" does.

### Steps to reproduce

1. Add "indent" to the redactor config
2. open an entry that's meant to use the config
3. attempt to locate the indent button

![image](https://user-images.githubusercontent.com/3789834/104336164-1fde8f00-54c2-11eb-9d58-ce723b51403f.png)

![image](https://user-images.githubusercontent.com/3789834/104336192-25d47000-54c2-11eb-9df9-d78abe393f50.png)

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.3.19
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Redactor 2.8.5

**Comment by andris-sevcenko** [comment]
I tested out this behavior and it's strange. "Indent" will actually put the "list" button there.

It almost makes sense - Redactor only allows indenting and outdenting list times and the button is actually a dropdown list that does contain the "indent" option.

I'm unsure as to why "outdent" would warrant a stand-alone button then, but this is not something that this plugin affects.

**Comment by acres42** [comment]
Did this ever get solved? I am having a very similar issue with "lists" in the Standard.json file as well. 
Description
Adding "lists" to the buttons list works for unordered lists and ordered lists, however the "indent" and "outdent" buttons remain disabled

**Steps to reproduce**
Add "lists" to the redactor config
open an entry that's meant to use the config
click the lists button

![Screen Shot 2021-06-30 at 9 43 23 AM](https://user-images.githubusercontent.com/3231614/124000822-d529d400-d988-11eb-8cec-4ad8da6d38e1.png)
![Screen Shot 2021-06-30 at 9 52 51 AM](https://user-images.githubusercontent.com/3231614/124001370-68fba000-d989-11eb-92cf-9e7ca5701b2b.png)

AS THE OP mentions above, I can get the Outdent button to show up by explicitly calling it in Standard.json, but it still does nothing if I click it, and explicitly calling the Indent button makes this show the lists button, but does not work.

**Additional info**
Craft version: 3.5.14
PHP version: 7.4
Plugins & versions: Redactor 2.8.3

**Comment by andris-sevcenko** [comment]
@acres42 this is something that Redactor itself does (you can test it here: https://imperavi.com/redactor) and modifying that behavior is out of scope for this plugin.

My observations include that it's not possible to indent the first list item, however, you can indent all the other list items.
