### ISSUE TITLE
ampersand in Asset Volume name

### ISSUE THREAD

**Issue by heymarkreeves** [craftcms/redactor#297]
### Description

If an Asset Volume has an ampersand in the name, ex: "SEO & Social", it outputs as `SEO &amp; Social` in the list of Available Volumes when configuring a Redactor field.

### Steps to reproduce

1. Create or rename an existing volume with "&" in the name.
2. Create or edit a Redactor field and view the list of Available Volumes.

### Additional info

- Craft version: 3.5.17.1
- Plugins & versions: Redactor

**Comment by andris-sevcenko** [comment]
Thanks, fixed for the next release!

**Comment by brandonkelly** [comment]
Redactor 2.9.0 is out now with this fix.
