### ISSUE TITLE
Toolbar disappears

### ISSUE THREAD

**Issue by thislogancall** [craftcms/redactor#30]
There is a bug where the toolbar sometimes disappears. 

I've found this to happen on two occasions. 

1. When you have several WYSIWYG editor fields in the same entry/post and you've edited them one by one, once I get to the third one it happens. 

2. When the WYSIWYG field is collapsed when you first open the entry/post to edit it, you uncollapse it, and the toolbar is sometimes gone. 

In both instances, saving the entry (thus also reloading the page) brings the toolbar back.

**Comment by brandonkelly** [comment]
Hi @thislogancall, we just released v2.0.0, which is powered by the new Redactor 3. Can you try updating your Redactor plugin and see if this issue persists?

**Comment by thislogancall** [comment]
Yes, that fixed the issue. Thank you.

**Comment by brandonkelly** [comment]
Great, thanks for checking!
