### ISSUE TITLE
Redactor saving absolute URLs for links to entries

### ISSUE THREAD

**Issue by sidm1983** [craftcms/redactor#301]
### Description
**NOTE: I know the title says "Redactor", but this could be an issue with how my craft default site is set up.**

I have a Craft CMS site running in headless mode. The site has a section/entry type called `Article` which has a `Matrix` field with a `Redactor` field within it.

When I insert a link in the redactor field to another article entry, I can see that it saves the `<a>` tag with an `href` value of `http://localhost:5000/article/my-first-article#entry:35@1:url`.

How do I get redactor to save a relative URL (i.e. not save the `http://localhost:5000` part)? Like this `/article/my-first-article#entry:35@1:url`

As I mentioned above, the CMS is running in headless mode as a back-end to a SPA. Having an absolute URL will likely cause the SPA to do a full refresh instead of just updating a part of the view.

Apologies if this is a redactor issue. I thought I'd ask here first in case it was a configuration issue with my site's base URL.

Please let me know if this is a redactor issue and I will raise a new issue in the redactor repo.

Thank you.

### Additional info

- Craft version: v3.6.4.1
- PHP version: 7.3
- Database driver & version: PGSQL 11
- Plugins & versions: Redactor 2.8.5

**Comment by sidm1983** [comment]
@brandonkelly thanks for the explanation. I guess that is what I am wondering at the moment. When I query the rich text field using graphQL, it looks like it is returning the fallback value even though entry with ID 35 does exist in site ID 1. I am not sure what I need to do to get it to return just the relative URL without the base URL.

**Comment by andris-sevcenko** [comment]
@sidm1983 If you output the content in a twig template, are you seeing a relative URL?

**Comment by sidm1983** [comment]
@andris-sevcenko I am not using twig templates at all in this particular case. I am using the CMS in headless mode, so all my querying and retrieval of data is happening via GraphQL which outputs the fully-qualified absolute URL. By the way, I am also seeing this behaviour (of outputting the full absolute URL) in other plugins (e.g. Linkit) too and not just Redactor. They are probably all calling some sort of a general Craft CMS link resolver function which is including the site's base URL. Would be great to be able to configure whether or not the site's base URL is included via either `app.php` or `general.php`.

Any thoughts?

**Comment by andris-sevcenko** [comment]
Okay, as a next step can you try modifying the fallback URL before saving it?

The goal of this would be to understand, whether you are getting the fallback URL or rather if the element reference tag gets output as an absolute URL.

**Comment by sidm1983** [comment]
@andris-sevcenko So I inserted the link to an entry and it initially set the value as `http://localhost:5000/article/my-first-article#entry:97@1:url`.

Then I changed it to `https://localhost:5008/article/my-first-article#entry:97@1:url` and hit save on the article entry.

When I checked the HTML in the redactor field after saving the entry, it reverted back to `http://localhost:5000/article/my-first-article#entry:97@1:url` and in graphQL I get the reverted localhost:5000 absolute URL too.

It looks like the element's reference tag is getting returned as an absolute URL. Is this a config issue on my part or a bug or do we need an enhancement here?

**Comment by andris-sevcenko** [comment]
@sidm1983 still can't rule out either. IIRC, Redactor does some stuff before saving.

Is it possible for you to modify the DB contents? If so, can you find the relevant record in `matrixcontent_<handle>`, where `<handle>` is the Matrix field handle?

The relevant row would be trickier to find through the relations, so you can probably create a new Matrix Block to ensure a new row gets created. Then, insert a link to the entry in this new Matrix Block, save it, find the row in the table (should be the last one now, if you created a new Matrix Block) and modify the value in the `content_<handle>` column, except this time `<handle>` is the Redactor field handle.

Now, this should tell us whether Redactor saves something in a strange manner or does Craft just return the absolute URL.

Sorry for the runabout!

**Comment by sidm1983** [comment]
@andris-sevcenko sorry for the delay in getting back to you about this.

So, I just added a link to an existing redactor content and was able to find the record pretty easily in the `matrix_articlebody` table. Here is the what redactor saves into the database:

```
<p>This is the body of description for the <a href="{entry:23@1:url||https://localhost:5001/article/the-first-article}">article</a> card</p>
```

Is this correct? If so, it looks like Craft is just returning the absolute URL when querying via GraphQL (or in general maybe?).

Please let me know what you think of this.

Thank you!

**Comment by andris-sevcenko** [comment]
@sidm1983 right, so the plan is to modify the content in the database. Change the fallback URL to a random one and then we'll see whether the entry URL is resolved incorrectly for you or GraphQL is outputting the fallback URL for you.

**Comment by sidm1983** [comment]
@andris-sevcenko I modified the content in the database to this:
```
<p>This is the body of description for the <a href="{entry:23@1:url||https://random-domain-name.net/article/the-first-article}">article</a> card for QA</p>
```
but when I do the GraphQL query, I get this back:
```
<p>This is the body of description for the <a href="http://localhost:5000/article/the-first-article">article</a> card for QA</p>
```
So it is definitely not outputting the fallback URL. The entry seems to be resolving to the absolute URL.

How do I get it to resolve to the relative URL or is this a bug?

**Comment by andris-sevcenko** [comment]
What is your Site's URL set to?

**Comment by sidm1983** [comment]
@andris-sevcenko Site URL is set to `http://localhost:5000`.

**Comment by brandonkelly** [comment]
> How do I get it to resolve to the relative URL or is this a bug with GraphQL / general link resolution in Craft?

@sidm1983 What exactly do you mean by “relative URL”? As in a root-relative URL? If that’s what you want, you can change your site’s Base URL to a root-relative URL (e.g. `/`).

**Comment by sidm1983** [comment]
@brandonkelly yes, root-relative is what I mean. If I set the site's base URL to `/`, then won't my view/preview buttons on an entry go to the wrong URL? As in won't it try to load the preview using my Craft CMS/CP URL as the base URL? If so, this would be incorrect in this case as the view/preview buttons still need to resolve to the URL of the front-end site and not the Craft CMS/CP URL.

Basically, I still need to have the view/preview button resolve to the absolute URL of the front-end site, but I also need redactor (and any other plugins/fields that return entry URLs) to return a root-relative URL when it is being queried via GraphQL by the front-end as it is a SPA and needs a root-relative URL.

**Comment by sidm1983** [comment]
@andris-sevcenko / @brandonkelly any thoughts on the above scenario?

Thank you. 🙏🏽

**Comment by brandonkelly** [comment]
@sidm1983 The preview pane is an `<iframe>` set to the entry’s actual front-end URL, so any root-relative URLs within your Redactor field should assume the site’s hostname, not the CP’s.

**Comment by sidm1983** [comment]
@brandonkelly But how will it assume the site's hostname if I change the site's base URL to `/`? It won't actually know what the value of the site's hostname is, right?

Sorry, I am not sure I follow what you mean. I will try it out and share some screenshots if it doesn't work.

**Comment by sidm1983** [comment]
@brandonkelly, I just tested your suggestion of using a `/` as my site's base URL value. Unfortunately, it doesn't solve the problem. As I anticipated, setting the site's base URL to `/` made the view/preview button load the entry page using the Craft CMS hostname instead of the front-end hostname (i.e. the URL it loaded was `https://my-craft-cms-domain.com/article/my-first-article` instead of `https://my-front-end-domain.com/article/my-first-article`), which is not correct in this scenario/architecture. My front-end is a completely different web application to the Craft CMS web application and they both have different domain names.

Secondly, even with the site's base URL set to `/`, redactor still returned the fully-qualified absolute URL, but this time using the Craft CMS hostname. It seems like there is currently no way to get redactor to return a root-relative URL even when the site's base URL is set to `/`.

Here is what the redactor field returned when queried via GraphQL (the site's base URL is set to `/` in this case):
```
<p>This is <em><strong>some</strong></em> rich text</p><blockquote>This is a block quote!</blockquote>\n<p>Okay this is a regular <a href=\"http://my-craft-cms-domain.com/article/my-first-article\">paragraph</a> again.</p>
```
You can see that the value of the `href` attribute on the `<a>` tag is an absolute URL and uses the Craft CMS hostname. I am trying to figure out if there is a way for that `<a>` tag to be generated like this: `<a href=\"/article/my-first-article\">paragraph</a>` while still allowing the view/preview buttons to properly load an entry page using the fully-qualified front-end URL like this: `https://my-front-end-domain.com/article/my-first-article`

Please let me know your thoughts or if you need further clarification on my scenario/architecture.

**Comment by brandonkelly** [comment]
Sorry, you’re right.  Not really sure what we can do about this though. You’ll just have to set your site’s base URL to an absolute URL. You can use the Find And Replace utility to update any `http://localhost:5000` references to the real hostname.

**Comment by sidm1983** [comment]
@brandonkelly, I don't actually need to use "Find and Replace" because the redactor URLs correctly update when I change the site's base URL to a different value. Redactor is definitely NOT hard-coding the hostnames. That is not the issue here. I think I was sometimes using `https://localhost:5000` and sometimes using `https://my-front-end-domain.com` in my examples and that probably caused a bit of confusion here. I apologise for that.

Just to clarify, both of those URLs above represent the same thing...the front-end URL in this case. `https://localhost:5000` is just what the front-end URL is on my local machine and `https://my-front-end-domain.com` is an example of what the front-end URL could be on another environment like UAT or PROD. The way redactor saves the links is fine and is not the issue. This is why I first raised this as a Craft CMS issue and not a redactor issue as it feels like a oversight in the link resolution functionality of Craft CMS when it is running in headless mode.

Basically, the problem here is that I must have my site's base URL set to my front-end hostname for the view/preview button to work correctly, but I also need a way to get the redactor field to generate root-relative URLs when it is being queried via GraphQL. Is this something that can be added to the GraphQL syntax using some sort of directive or additional property on the redactor field to tell it to return root-relative URLs? Similar to how we can apply image transforms to asset fields to return a differently sized image. Here we would in essence be applying a "transform" to the redactor field to request an override of its default absolute URL link resolution behaviour so that it returns root-relative URLs instead.

What do you and @andris-sevcenko think about this as a possible solution for this?

Looking forward to hearing your thoughts. Thank you.

**Comment by andris-sevcenko** [comment]
@sidm1983 @sidm1983 GraphQL itself does not come up with an idea about transforms - that has to exist in Craft for GrahpQL to take advantage of it. There would need to be a way for the element references to return relative URLs that could then be leveraged.

Have you considered removing the absolute part of the URL as you're processing the GraphQL response?

**Comment by sidm1983** [comment]
@andris-sevcenko yup I know and agree that GraphQL does not come with the idea of transforms. I was actually suggesting that maybe it could be added to Craft's GraphQL implementation and have it work in a conceptually similar way to image transforms. Like you said, it would involve changing Craft CMS to allow the default link resolution behaviour for elements to be overridden so that it returns root-relative URLs.

As for the workaround you suggested, I was actually already thinking along those lines. I am definitely planning on manually stripping out the absolute part of the URL for links that start with the browser's current hostname on the front-end. However, I will need do this for each of the redactor fields that are used in the various blocks of the article body matrix field. While this is a feasible workaround, it still feels unnecessary in my opinion.

I guess this is now more of a feature request rather than a big report. It would be really nice to give developers the option to query for either absolute URLs or root-relative URLs via GraphQL. I know this would probably require a change to the way element links are resolved as well as Craft's GraphQL implementation, but I think it could be a worthwhile change/enhancement.

Imagine a scenario where you have a single Craft CMS instance running in headless mode and serving the same content to 5 different websites/mobile apps. Now let's say (for whatever reason) that 2 of these websites/mobile apps require fully-qualified absolute URLs, while the rest of them only need root-relative URLs. As a developer of these sites, it would be awesome if I could achieve this by simply modifying my GraphQL query slightly to request root-relative URLs for the websites that need them. I know I can just do the workaround you mentioned and have those websites just strip out the absolute part, but that feels like a hack to me.

Apologies if this is just not possible given the current architecture of Craft CMS. I have worked with other CMS products that do allow this type of on-the-fly overriding of their links, so that's why I am requesting something like this be added to Craft CMS as well.

What do you think?

**Comment by brandonkelly** [comment]
> but I also need a way to get the redactor field to generate root-relative URLs when it is being queried via GraphQL

Sorry, get it now. It’s against best practices to have root-relative URLs returned by APIs – the only time it’s an OK idea is if you know the URL is only going to show up on a webpage, where the absolute URL is implied from the page’s hostname.

If you need a relative URL for routing, you should add your own find + replace logic on the client side of the GraphQL request.

**Comment by sidm1983** [comment]
@brandonkelly yup, understood. In my particular scenario the URL is only going to show up on a webpage (at least for the foreseeable future anyway).

All good though. Like you and Andris have suggested, I will just strip out the hostname from the URL if it matches the hostname of the page on the client side.

Thank you and @andris-sevcenko for your time and patience throughout this discussion. I really appreciate it. ❤️🙌🏽

**Comment by nickroberts** [comment]
What I'm currently doing, is passing an environment variable to the client (I'm using NextJs, as it has the ability to handle client side environment variables), and using that in my redactor component to replace the urls.

One of the downsides to this, is I have to build the site on a per-environment basis, as each environment needs to replace the correct url.

I have also thought about training end users to just remove the extraneous stuff from the link when adding, but that might be a bit confusing. Essentially, instead of http://my-cms-url/some-page?id/whatever, they would just edit the url to /some-page.

It would be great if there was some option to insert links to entries just based on the slug ,without the base url.

I am making things work at the moment, but I feel like these are all hacks.

**Comment by michaelroper** [comment]
I'm running into these exact issues at the moment, and @sidm1983 explained it all far better than I would have.

I agree that a setting or way to "transform" element urls to root-relative in the GraphQL would be ideal. The "replace it on the client-side" method could messy when you're deploying your front-end to different environments and branch "preview" domains (cf Vercel, Netlify, etc).

@brandonkelly - is there a reason why setting `siteUrl` to `/` is ignored and the CMS url gets used instead? 

--
The other option that has been pointed out to me is that if you can get to the element in your graphql call (eg in plugins like Typed Link Field or Navigation), you can access the `uri` property, which is the path part of the url.. this almost works, but the `uri` doesn't include the slash at the start, which means the urls are _page_-relative, not _root_-relative.
