### ISSUE TITLE
Importung content from feedme into redactor - content is outputted as plaintext

### ISSUE THREAD

**Issue by piotrpog** [craftcms/redactor#303]
There seems to be some problem related to redactor and feedme plugins. When i import content containing text with newlines (but no html) into redactor field:

![image](https://user-images.githubusercontent.com/42622545/109651381-be9c7900-7b5e-11eb-8952-85719e3bda00.png)

 ...this field later shows text with newlines changed into paragraphs.

![image](https://user-images.githubusercontent.com/42622545/109651426-cf4cef00-7b5e-11eb-94d7-ae05d4afd7c9.png)

But when i output field contents into twig, it shows as plain text:

![image](https://user-images.githubusercontent.com/42622545/109651450-d542d000-7b5e-11eb-9bfd-d701ee215423.png)

PS: I overcame this problem by processing text into paragraphs myself before import, using feedme events.

**Comment by andris-sevcenko** [comment]
Redactor converts them to paragraphs on the field load using JS. I'm guessing that if you resaved the field after, it would be converted to paragraphs, too. 

As things are, you imported a text without paragraphs and, without additional process, it was displayed as a text without paragraphs on the frontend.

Glad you resolved it!
