### ISSUE TITLE
Large quantity of console errors when using redactor to embed videos 

### ISSUE THREAD

**Issue by wallythewebdev** [craftcms/redactor#305]
### Description
On my page I have embeded several links to different videos, when the page loads it presents a large number of console log erros and I was wondering if anyone had some across this before and might know of how to: 

1) explain what these are and the cause of them?
2) Prevent them from printing to the console (preferably by solving the error) 

![image](https://user-images.githubusercontent.com/28821463/110106448-9a7caa00-7da1-11eb-91bd-edac3d3c2afa.png)

error: Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Opening file presents: window.google_ad_status = 1;
https://static.doubleclick.net/instream/ad_status.js

### Steps to reproduce

1. embed youtube video using redactor and have it output to the front end of the website
2. open console log and see the errors

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Pretty sure that error indicates that you have an ad blocker that prevented an ad from loading.
