### ISSUE TITLE
[Bug] Redactor 3 Broken When Used in Matrix

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/redactor#31]
[See Screenshot](https://goo.gl/5rkzW8)

PHP version: 7.0.29
Database driver & version: MySQL 5.5.5
Image driver & version: GD 7.0.29
Craft edition & version: Craft Pro 3.0.5

**Comment by mattcdavis1** [comment]
Seems to work locally but not on prod.  not sure what the difference is.

**Comment by mattcdavis1** [comment]
Looks like a case sensitivity issue: https://goo.gl/pngLRZ (URL is looking for `PluginBase.min.js`)

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed in 2.0.0.1.

**Comment by matt-adigital** [comment]
It looks like this issue has appeared again with the release of Redactor 2.1.1. All of the resources have loaded with a 200 status. I've included screenshots of the edit template and the console log below.

<img width="618" alt="screen shot 2018-07-13 at 16 03 53" src="https://user-images.githubusercontent.com/15085874/42698893-205c6d98-86b7-11e8-86d7-4321b9717470.png">

<img width="1219" alt="screen shot 2018-07-13 at 16 05 05" src="https://user-images.githubusercontent.com/15085874/42698894-20859c04-86b7-11e8-94ca-72fe3a6fb251.png">

**Comment by andris-sevcenko** [comment]
@matt-adigital try updating to 2.1.2 - it should fix things for you.

**Comment by matt-adigital** [comment]
That's fixed it. Thank you very much @andris-sevcenko!
