### ISSUE TITLE
Redactor Link to entry modals not showing entries to another site

### ISSUE THREAD

**Issue by Mmasson-01** [craftcms/redactor#313]
### Description

The link to another entry modules in the rich text editor is broken when trying to link to entries from another site than the default.

We have 5 different site in craftcms. If editing on the first (default) site and trying to embed link to an entry from the redactor plugins, the modal shows all possible entries.

If editing on another site (not the default) and trying to embed link to an entry from the redactor plugins, the modal to select an entry shows no results

### EDIT

1. There's no network error.
2. No error showing up (or I can't find any) on the debug mode.
3. I've tried to clear cache, reinstall (we actually tried of 3 different server (dev, qa, staging) and same behavior.

### Steps to reproduce

1. Edit an entry from the rich text editor (default site)
2. Click on the rich text editor (redactor) link -> Link to an entry -> select an entry from the results in the modal
3. Close the modal
4. Switch to another site from the default using the drop down selection next to the title of the entry
5. Click on the rich text editor (redactor) link -> Link to an entry -> no entries shows

### Alternative steps
1. Edit an entry from the rich text editor (default site)
2. Click on the rich text editor (redactor) link -> Link to an entry -> switch site to another one than the default -> no entries shows

![image](https://user-images.githubusercontent.com/39672866/117023620-4457b480-acc7-11eb-8a98-247748780ae5.png)

![image](https://user-images.githubusercontent.com/39672866/117023848-779a4380-acc7-11eb-9919-8afd06b07652.png)

![image](https://user-images.githubusercontent.com/39672866/117022350-2ccbfc00-acc6-11eb-8c88-845f06f105a6.png)

### Additional info

- Craft version: 3.6.11.2 (Pro)
- PHP version: 7.4
- Database driver & version: Mysql 5.7
- Plugins & versions:
 - Redactor 2.8.5
 - Amazon s3 1.2.11
 - Element API 2.6.0
 - Feed Me 4.3.6
 - SAML Service Provider 2.6.6
 - Workflow 1.5.9
 - Keychain 1.0.3

Here are all the site

![image](https://user-images.githubusercontent.com/39672866/117022581-5be26d80-acc6-11eb-9f6a-586e70ad631a.png)

Entries are showing for the first 2.
I've tried switching all site under the same group, and switching different site as default. It's doing nothing.

**Comment by andris-sevcenko** [comment]
I am unable to reproduce this locally. If you can still reproduce this, please send an email over to support@craftcms.com and reference this issue, as it's likely to be an environment problem.

**Comment by Mmasson-01** [comment]
@andris-sevcenko At some point I was unable to reproduce the bug and it got fixed somehow. I've hot worked on this project for a long time and the no flag have been raised since from the other devs.

I suppose we can close this, thank you !
