### ISSUE TITLE
Linking using reference tags show empty link after save

### ISSUE THREAD

**Issue by dowadidi** [craftcms/redactor#319]
### Description
It is possible to use reference tags as link. And they are being rendered properly in the frontend. But when editing the link in redactor, the url field is empty. 

Note: after saving, the tooltip shows the correctly rendered link, even if the url field is still empty.

### Steps to reproduce
1. Use a reference tag in the url field for adding a link.
2. Save entry and edit the same link.

### Additional info
- Craft version: 3.5.19.1
- PHP version: 7.3
- Database driver & version: mysql 5.6
- Redactor: 2.8.7

### Adding the link
![image](https://user-images.githubusercontent.com/3625639/118003280-b889fc00-b348-11eb-9d50-7db26f549208.png)

### After saving, tooltip shows rendered link
![image](https://user-images.githubusercontent.com/3625639/118003443-e1aa8c80-b348-11eb-95d2-7264248a968c.png)

### Editing the link, url is gone
![image](https://user-images.githubusercontent.com/3625639/118003589-00a91e80-b349-11eb-8321-0b0fe0fcce7f.png)

**Comment by andris-sevcenko** [comment]
For the next release of the Redactor plugin, the reference tag will show up straight away in the link edit modal.

However, it will not be parsed into a full link until it's been saved, as that is done in the backend.

**Comment by andris-sevcenko** [comment]
The next release will be early next week!
