### ISSUE TITLE
webcal:// links are being set to null

### ISSUE THREAD

**Issue by jskrivanek** [craftcms/redactor#321]
### Description

Adding a webcal:// url gets removed from text

### Steps to reproduce

1. Add a link webcal://your.domain.com/your-slug to the text in the editor
2. Save entry
3. Link is removed and just <a>

### Additional info

- Craft version: Craft Pro 3.6.13
- PHP version: 7.4.16
- Database driver & version: MySQL 8.0.23
- Plugins & versions: /

**Comment by andris-sevcenko** [comment]
It looks like [HTML Purifier doesn't support](http://htmlpurifier.org/live/configdoc/plain.html#URI.AllowedSchemes) `webcal` as a URI scheme.

You'll have to disable the "Purify HTML" option under the Advanced options for the Redactor field.

![Screen Shot 2021-05-24 at 15 06 38](https://user-images.githubusercontent.com/1891118/119345528-ab9ece00-bca1-11eb-937d-4fc60d762726.png)
