### ISSUE TITLE
Images srcset attributes and transforms

### ISSUE THREAD

**Issue by yingban** [craftcms/redactor#324]
### Description

When a user uploads an image through Redactor, if the file is big and with or without any transform, the image is just output in a raw way inside a <figure>, and the image will be output in the same way on every devices.

Is there a way to modify the output and include different <source> of the images in a <picture> for example ?

**Comment by nicbou** [comment]
Look at RetCon. The plugin allows you to insert responsive images.

**Comment by yingban** [comment]
@nicbou thank you very much ! looks like what I was searching
