### ISSUE TITLE
Unable to restart numbered lists at a specific number

### ISSUE THREAD

**Issue by pedromarzagao** [craftcms/redactor#325]
I'm unable to restart numbered lists at a specific number. Lists always start at 1. Adding a break to a numbered list doesn't allow you to continue the list at a different number. This is sometimes needed to add an image or a code snippet in the middle of a list as shown in the screenshots.

![Screenshot 2021-06-02 at 10 16 56](https://user-images.githubusercontent.com/37834524/120789891-1cf44180-c52a-11eb-8fe7-2c3dd2933f14.png)
![Screenshot 2021-06-02 at 10 16 46](https://user-images.githubusercontent.com/37834524/120789895-1e256e80-c52a-11eb-8408-325b646f9d19.png)

**Comment by andris-sevcenko** [comment]
Unordered lists are implemented in Redactor using the `<ol>` HTML tag.

To do what you want you'll have to enable the HTML source view for Redactor and add the `start` attribute to the `<ol>` tags to make the list start at a specific number.

Redactor does not enable this through UI out of the box.
