### ISSUE TITLE
breakline is added double

### ISSUE THREAD

**Issue by palomamtnez** [craftcms/redactor#328]
### Description

I have a simple field, with this config:

```
{
  "buttons": [
    "bold",
    "italic",
    "link"
  ],

  "breakline": true

}
```

What I want is to just have simple text with `<br>` but not other tags involved (except for link, bold, italic)
So when I do a test, every line break is added as double:

```
test<br><br>
this<br><br>
is a<br><br>
test
```

No matter if I enter the line breaks through the admin panel with Shift + Return, or just by Return 

How can I avoid this? and just get a simple return?

Thanks

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4
- Database driver & version: 5.7
- Plugins & versions:
![Screen Shot 2021-06-17 at 5 04 32 PM](https://user-images.githubusercontent.com/13962572/122334599-1801aa00-cf8e-11eb-9d28-84556d2d4a5a.png)

**Comment by andris-sevcenko** [comment]
Locally, testing on the Redactor version that'll be released next week (2.9), I'm able to get the desired behavior by using the `breakline` option. If you can still reproduce this after updating to it next week, let me know!
