### ISSUE TITLE
Links no longer have the "Open link in new tab" option

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/redactor#33]
It looks like the [linksNewTab](https://imperavi.com/redactor/docs/settings/link/#s-linknewtab) option has been disabled in 2.0.0.

Would be nice if we had access to some of these core settings in the CP, or a base redactor plugin that could be used as a config to control stuff like this.

**Comment by andris-sevcenko** [comment]
It's a config setting in Redactor now - https://imperavi.com/redactor/docs/settings/link/#s-linknewtab

**Comment by jsunsawyer** [comment]
@andris-sevcenko This is great! Totally didn't get that from the docs.

**Comment by stianmandarin** [comment]
It's unclear to me how I'm supposed to add this to my JSON config, could anyone show an example?

**Comment by jsunsawyer** [comment]
@stianmandarin Here's an example:

```{
  "buttons": [
    "html",
    "formatting",
    "bold",
    "italic",
    "unorderedlist",
    "orderedlist",
    "link",
    "file"
  ],
  "formatting": [
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "p",
    "blockquote"
  ],
  "plugins": [],
  "linkNewTab": true,
  "shortcodes": false
}
```

**Comment by stianmandarin** [comment]
@jsunsawyer Perfect, cheers!

**Comment by jolyonruss** [comment]
I'm also looking to activate the `Link in new tab` feature of redactor.

I've edited both the Simple.json and Standard.json to look like this:

Standard.json
```
{
    "buttons": [
        "formatting",
        "bold",
        "italic",
        "unorderedlist",
        "orderedlist",
        "link",
        "image",
        "video"
    ],
    "plugins": [
        "fullscreen",
        "video"
    ],
    "linkNewTab": true,
    "toolbarFixed": true
}
```

Simple
```
{
  "buttons": ["bold", "italic", "lists"],
  "linkNewTab": true,
  "toolbarFixed": true
}
```

Is there anything else I need to do in order to get this to work?

**Comment by brandonkelly** [comment]
@jolyonruss Make sure that your Redactor fields are using one of those two configs, from their field settings.

**Comment by jolyonruss** [comment]
@brandonkelly thanks for the reply. Looks like that was the issue - I installed Control Panel CSS and added a quick CSS hack to get this to always show.

We have a very large matrix and at some point I will have to go through every blocktype and field to check which Redactor template is being used.

🙁

**Comment by brandonkelly** [comment]
@jolyonruss Here’s a [content migration](https://docs.craftcms.com/v3/content-migrations.html) that will update your Redactor fields for you:

https://gist.github.com/brandonkelly/f9afdff10a952e6138ac5d35af892517

Just save that in your `migrations/` folder (you may need to create it), and then either run `./craft migrate/up` from your terminal, or run it from your Content Migrations utility within the Control Panel.
