### ISSUE TITLE
Image dimensions are not set

### ISSUE THREAD

**Issue by nicbou** [craftcms/redactor#330]
### Description

When inserting an image with Redactor, the image does not have width and height attributes. Those are important to prevent the content from jumping around while it loads, especially with lazyloaded images.

### Steps to reproduce

1. Insert an image
2. It does not have width and height attributes

**Comment by andris-sevcenko** [comment]
Is this when selecting a Craft asset?

For regular images, this could be pulled off, but if the user selects a transform, the width and height are unknown until the transform is actually created.

**Comment by nicbou** [comment]
I usually insert images as transforms, using the rich text editor's interface.
