### ISSUE TITLE
HTML button not showing for certain users

### ISSUE THREAD

**Issue by piperhaywood** [craftcms/redactor#333]
### Description

When HTML button is enabled, it doesn’t seem to show up for non-Admin users.

### Steps to reproduce

1. Install Craft and Redactor plugin
2. Set up a new Redactor field, then add this to a new entry type.
3. Set up a new User group with the following permissions checked:
  - General
    - Access the Control Panel
      - Access the Control Panel when the system is offline
  - Users
    - Select all
  - Sites
    - Select all
  - Section - [Section name]
    - Select all
  - Utilities
    - System Report
    - PHP Info
    - Database backup
4. Create a new user that has the newly-created user group
5. Log in as the new user and try to edit the text field via the missing HTML button

### Additional info

- Craft version: Craft CMS 3.6.17
- PHP version: 8.0.2
- Database driver & version: MySQL 5.7.32
- Plugins & versions: Redactor 2.8.7

**Comment by andris-sevcenko** [comment]
There's a setting on Redactor fields that's probably set to `true` for you. See here: https://github.com/craftcms/redactor/issues/129

**Comment by piperhaywood** [comment]
Thanks so much @andris-sevcenko, I suspected there must be a field for this somewhere but just could not find it! Sorry for the irrelevant issue.

**Comment by andris-sevcenko** [comment]
Glad that's all it was!
