### ISSUE TITLE
Multiple UL styling preset options

### ISSUE THREAD

**Issue by Alex-Waite** [craftcms/redactor#339]
I would like to add additional options inside the editor allowing the user of the redactor field to decide how to style their `ul`. In my experience I would like to add a Pros vs. Cons list in which either a cross-icon `ul` or a tick-icon `ul` can be selected from the lists tab however it seems this is not possible to do. 

Please let me know if I am simply making a mistake.

**Comment by andris-sevcenko** [comment]
You can add support for this by adding this to the Redactor config:

```json
"formattingAdd": {
    "pros": {
      "title": "Pros",
      "api": "module.block.format",
      "args": {
        "tag": "ul",
        "class": "pros"
      }
    },
    "cons": {
      "title": "Cons",
      "api": "module.block.format",
      "args": {
        "tag": "ul",
        "class": "cons"
      }
    }
  }
```

This will allow you to select text and convert it to an unordered list with either the "pros" or "cons" option in the Format dropdown.
