### ISSUE TITLE
Multiple authors see different content for the entries "current" in Craft

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/redactor#340]
### Description
I'll try to explain this the best I can. We've run into an issue where if you have simultaniously opened an entry with another author, and are both working on it, Craft loads different revisions for both authors, even after refreshing. 

Usually, there would be an indication of "edited" and the option to discard changes, but these are not visible for us. We've made a video of a side-by-side editing with a colluague to demonstrate:
https://backspace.stackstorage.com/s/avtK2983YMAFoAzY

You can see that no matter what we do, my changes will reflect on the revision that my colleague is working on, but not the other way around, her changes never make it to my revision and dissapear into the database.

### Steps to reproduce

1. Create an article and open up the editor screen with a colleague on a different machine
2. Updated the entry, refresh and check the current version together with that colleague. Both screens will show that they are currently showing the lastest revision, when in reality they are showing different things.

### Additional info

- Craft version: 3.7.14
- PHP version: 8.0
- Database driver & version: MySQL 8.

**Comment by andris-sevcenko** [comment]
@lenvanessen have you encountered this in more recent FF Developer Edition releases?

**Comment by lenvanessen** [comment]
@andris-sevcenko not recently no

**Comment by andris-sevcenko** [comment]
Well, I'll close this with fingers crossed, then :)
