### ISSUE TITLE
Removing link using Air toolbar doesn't save correctly

### ISSUE THREAD

**Issue by olivierbon** [craftcms/redactor#348]
### Description

When removing a link using the [Air toolbar](https://imperavi.com/redactor/examples/toolbars/air-toolbar/), Redactor doesn't trigger auto-save, the field doesn't get marked as dirty and the changes get lost on save. 

Things work correctly using the modal.

### Steps to reproduce

1. Unlink text using Air toolbar
2. Save entry
3. Re-open entry and the link is back

### Additional info

- Craft version: latest
- Plugin version: latest

**Comment by gglnx** [comment]
I can confirm this issue still with the lastest version (Craft CMS 3.7.26, Redactor Plugin 2.8.8). I'm using Firefox 95.

**Comment by KingFrank1982** [comment]
Also in the normal toolbar this happens:
![image](https://user-images.githubusercontent.com/16013074/148351363-245b7eb4-f9fd-42db-b7dd-14aad82532fc.png)
(Craft Pro 3.7.23 and Redactor 2.8.8).

**Comment by lauriechu** [comment]
original report Dec 1, 2021. Using "Edit"

![unlink doesn't save](https://user-images.githubusercontent.com/23465026/149214545-fd8ce9b3-5c8e-4dba-a78a-5e9e9adc8be5.png)

https://user-images.githubusercontent.com/23465026/149214838-e0de20a8-1264-4135-a747-3a9e21c8da53.mp4

**Comment by riekusvm** [comment]
I can confirm this is still the case in Craft 3.7.29 (chrome 97.0.4692.71)

**Comment by brandonkelly** [comment]
Redactor 2.9.0 is out now with this fix.
