### ISSUE TITLE
Not able to add strikethrough button

### ISSUE THREAD

**Issue by laurabennett** [craftcms/redactor#349]
### Description
I edited Default.json in config/redactor to include underline and strikethrough but only the underline button was added. 

{
  "buttons": [
    "html",
    "formatting",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "unorderedlist",
    "orderedlist",
    "link",
    "image",
    "video"
  ],
  "plugins": [
    "fullscreen",
    "video"
  ],
  "linkNewTab": true,
  "linkTarget": "_blank",
  "toolbarFixed": true
}

### Additional info

- Craft version: 3.7.29
- PHP version: 7.4.26
- Database driver & version: MySQL 5.5.5
- Plugins & versions:  2.8.8

**Comment by andris-sevcenko** [comment]
Redactor users `deleted` for strikethrough. Yeah, I know. :)
