### ISSUE TITLE
formattingAdd

### ISSUE THREAD

**Issue by daniellefrapp** [craftcms/redactor#35]
I just recently updated, and now my formatting add styles don't seem to be working. Is there a new way to do this. Here is what is in my standard.json

`{
    "buttons": [
        "format",
        "bold",
        "italic",
        "deleted",
        "underline",
        "unorderedlist",
        "orderedlist",
        "link",
        "image",
        "horizontalrule"
    ],
    "formatting": [
        "p"
    ],
    "formattingAdd": {
        "heading3": {
            "title": "Heading 3",
            "args": [
                "h3",
                "class",
                "title is-3"
            ]
        },
        "heading4": {
            "title": "Heading 4",
            "args": [
                "h4",
                "class",
                "title is-3"
            ]
        },
        "heading5": {
            "title": "Heading 5",
            "args": [
                "h5",
                "class",
                "title is-5"
            ]
        },
        "heading6": {
            "title": "Heading 6",
            "args": [
                "h6",
                "class",
                "title is-6"
            ]
        }
    },
    "plugins": [
        "inlinestyle",
        "imagemanager",
        "beyondgrammar",
        "specialchars",
        "fullscreen"

    ],
    "imagePosition": true
}`

**Comment by daniellefrapp** [comment]
Sorry, I looked at the redactor documentation and found what I was doing wrong. All set.

**Comment by brandonkelly** [comment]
Glad you got it sorted!

**Comment by Thirdwrist** [comment]
hello @brandonkelly I am having similar issues here, the code above works for me on redactor v2.1, but my challenge now is how to add other attributes like ID and more to the formatting. Kindly help out...
