### ISSUE TITLE
Input shows rtl on ltr Entry

### ISSUE THREAD

**Issue by internetztube** [craftcms/redactor#356]
In a multi-site setup with RTL and LTR languages mixed, the redactor inputs of the LTR entries are RTL.

### Additional info

- Craft version: Craft CMS 3.7.27.2
- PHP version: 7.3.30
- Redactor version: 2.9.0

**Comment by grids** [comment]
Same issue, on local and production.

PHP version | 7.3.33
Database driver & version | MySQL 5.5.5
Craft edition & version | Craft Pro 3.7.33
Redactor | 2.10.1
