### ISSUE TITLE
JS error with Redactor 2.9.1 on Craft 3.6.18

### ISSUE THREAD

**Issue by Saboteur777** [craftcms/redactor#359]
### Description

The following JavaScript error happens: 

```
Uncaught TypeError: invalid 'instanceof' operand Garnish._eventHandlers[s].target
    trigger garnish.js:834
    destroy garnish.js:916
    destroy garnish.js:3753
    e garnish.js:79
    init garnish.js:3536
    constructor garnish.js:764
    constructor garnish.js:40
    constructor garnish.js:40
    init MatrixInput.js:482
    constructor garnish.js:764
    constructor garnish.js:40
    constructor garnish.js:40
    init MatrixInput.js:109
    constructor garnish.js:764
    constructor garnish.js:40
    constructor garnish.js:40
    <anonymous> 487021-sportolj-kreditert-az-elte-n-2-2:2036
    jQuery 2
        l
        c
```

### Steps to reproduce

1. Install latest Redactor (2.9.1) with Craft 3.6.18.
2. Navigate to any element edit page, where a Redactor field is used.
3. Missing Redactor instances and Live Preview won't open. 

### Additional info

- Craft version: 3.6.18
- PHP version: 7.4.11
- Database driver & version: MySQL 5.5.5

**Comment by andris-sevcenko** [comment]
I'm not entirely convinced it's a Redactor issue, as there's no mention of Redactor in the stack trace.

What Redactor version were you using before?

**Comment by andris-sevcenko** [comment]
@Saboteur777 ah, got it reproducable. I'll look into this!

**Comment by andris-sevcenko** [comment]
Thanks! Fixed for the next release! By the way, if you're able to update Craft to 3.7, the error will go away, too!

**Comment by Saboteur777** [comment]
Awesome, thanks for the quick fix!

**Comment by andris-sevcenko** [comment]
@Saboteur777 the new Redactor version should be out either today or tomorrow!

**Comment by Saboteur777** [comment]
This issue is still present on Craft 3.5.19.1.
