### ISSUE TITLE
Automatic site-link detection not working when title attribute is present

### ISSUE THREAD

**Issue by NickLanger1990** [craftcms/redactor#365]
### Description
Automatic site-link detection not working when title attribute is present in the html.

### Steps to reproduce

1. go into html mode and paste `<a href="http://craftcms.test/testlink" title="title me" target="_blank">TestLink</a>` and save. 
2. the title attribute is striped off and the link will not be detected. without the title attribute everything works at aspected.

### Additional info

- Craft version: Craft Pro 3.7.28
- PHP version: 8.0.13
- Database driver & version: MySQL 5.7.36
- Plugins & versions: 2.10.0

**Comment by andris-sevcenko** [comment]
Thanks! Should be [fixed](https://github.com/craftcms/html-field/commit/d8ae4e3e4862a008ce50589eb7c90caf4fc0e2a2) if you run `composer update`!
