### ISSUE TITLE
Links are inserted at the beginning of the text

### ISSUE THREAD

**Issue by rene-haefliger** [craftcms/redactor#368]
### Description
When a word is selected in an existing text and a link is added to an entry, the link is created at the beginning of the text.

### Steps to reproduce

1. Edit Text in Redactor
2. Select a word
3. Add a link to an entry

### Additional info

- Craft version: 3.7.33
- PHP version: 7.4 .27
- Plugins & versions: 2.10.1

**Comment by andris-sevcenko** [comment]
Welp, there goes #364 😅

**Comment by andris-sevcenko** [comment]
Just reverted that change that brought this behavior around. Redactor 2.10.2 is out with this change now!
