### ISSUE TITLE
Multiple issues when using widget.js plugin

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/redactor#37]
1. Embedding a Tweet using the widget.js embed block with `toolbarFixed` causes the widget to be clicked when trying to use tools in the toolbar while the toolbar is overlapping the widget.

2. Using cmd + z to undo a text change visually removes any embed that has been placed. It also removes the toolbar.

**Comment by brandonkelly** [comment]
Fixed the toolbar focus issue.

I wasn’t able to reproduce the second issue. If you’re still seeing that after the next release, please post as its own issue with specific steps to reproduce (and in general please only post one bug per GitHub issue). Thanks!
