### ISSUE TITLE
Localisation issue after upgrade

### ISSUE THREAD

**Issue by netotaku** [craftcms/redactor#370]
### Description

After upgrading to 2.10.0 or 2.10.3, all redactor instances are right to left in the CMS on a localised site regardless of which language is selected. Primary Language English, Secondary language Hebrew. Downgrading to 2.8.3 fixes the issue. 

### Steps to reproduce

1. Upgrade Redactor to 2.10.0 or 2.10.3 

### Additional info

- Craft version: 3.7.33
- PHP version: 7.4.27
- Database driver & version: MySQL 8.0.28
- Plugins & versions: 
   - SEO
   - Supertable
   - Typed Link Field

**Comment by andris-sevcenko** [comment]
Can you post a screenshot of your user settings and how the Redactor field looks? 
I'm a little unsure what you mean with "secondary language".

**Comment by wsydney76** [comment]
Can confirm this behavior.

Sites:

![image](https://user-images.githubusercontent.com/60010597/155087941-027bc785-1276-48b9-a61a-c227e299b396.png)

English site in 2.8.8:

![image](https://user-images.githubusercontent.com/60010597/155088161-fda14e66-c307-44f6-ae08-56802252357d.png)

Update to 2.10.3:

![image](https://user-images.githubusercontent.com/60010597/155088475-3976342e-f7d8-4c2e-80b6-b80372af6ddc.png)

Same in german/russian site.

**Comment by grids** [comment]
Same issue, have now 3 Craft instances affected.

**Comment by andris-sevcenko** [comment]
Gotcha, I'll take a look!

**Comment by andris-sevcenko** [comment]
Thanks for reporting this! Just fixed it in 2.10.4!
