### ISSUE TITLE
Colors not being removed when using the Fontcolor plugin

### ISSUE THREAD

**Issue by angrybrad** [craftcms/redactor#376]
### Description

You can apply a color to text using the Fontcolor plugin, but you can't remove that color.

### Steps to reproduce

1. Fresh Craft and Redactor install of the latest releases.
2. Use this for Redactor config.

```
{
  "buttons": ["html", "formatting", "bold", "italic", "unorderedlist", "orderedlist", "link", "image", "video"],
  "plugins": ["fontcolor"],
  "fontcolors": ["#7ED2F6"]
}
```

3. Add some text to a Redactor field. Change the text color using the Fontcolor plugin.

4. View the source and notice the color has been added:

```
<p>This is a test of the <span style="color: rgb(126,210,246)">emergency</span> broadcast system.</p>
```

5. Save the entry. The color remains.
6. Remove the color using the Fontcolor plugin.
7. View the source again and notice the color has not been removed:
```
<p>This is a test of the <span style="color: rgb(126,210,246)">emergency</span> broadcast system.</p>
```

Note, I'm not able to reproduce on https://imperavi.com/redactor/plugins/fontcolor/, which makes me think it's a Craft issue.

### Additional info

- Craft version: 3.7.36
- PHP version: 8.0
- Database driver & version: n/a
- Plugins & versions: Redactor 2.10.5 using the [Fontcolor](https://imperavi.com/redactor/plugins/fontcolor/) plugin.

**Comment by andris-sevcenko** [comment]
Fixed for the next release!
