### ISSUE TITLE
Inserting inline images

### ISSUE THREAD

**Issue by pixleight** [craftcms/redactor#378]
### Description

There doesn't appear to be a way to insert images inline with paragraph text. While setting `"imageFigure": false` in Redactor config JSON does remove the wrapping `<figure>` element as [described here](https://imperavi.com/redactor/docs/settings/image/#s-imagefigure), inserting an image in the middle of a paragraph inserts a new `<p>` wrapping the `<img>`:

![image](https://user-images.githubusercontent.com/1278274/159051807-4f2ae03f-50da-4a17-ad84-2641a23a1c79.png)

```html
<p>Lorem </p><p><img src="https://path/to/image.svg#asset:293831:url" data-image="293831" style="opacity: 1;"></p>
<p>ipsum dolor sit amet</p>
```

It looks like this issue was previously addressed in #10, but the changes made there appear to no longer apply to current versions of the plugin.

### Steps to reproduce

1. Ensure `"buttons"` array includes `"image"` in a Redactor config JSON.
2. Edit content with in a Redactor field with that config applied.
3. Type a paragraph of text
4. Insert cursor somewhere within the text and insert an image

### Additional info

- Craft version: Craft Pro 3.7.16
- PHP version: 7.4.28
- Database driver & version: PostreSQL 14.2
- Plugins & versions: Redactor 2.8.8

**Comment by mmikhalko** [comment]
I have the same issue, I suppose that tag <p> is no need, and also "imageTag" parameter is no working from config

**Comment by brandonkelly** [comment]
@mmikhalko The `imageTag` config setting doesn’t exist anymore. I suspect it was replaced by `imageFigure`, but not totally sure.

**Comment by Evgeniy1806** [comment]
@brandonkelly I need the ability to insert inline images. Should we expect this feature in the near future?
