### ISSUE TITLE
Allow customization of redactor plugins

### ISSUE THREAD

**Issue by davist11** [craftcms/redactor#38]
The newest version of the Craft Redactor plugin comes with all of the Redactor plugins bundled in it, which is awesome!

But, these plugins don't give you the ability to customize with options passed from the Redactor configs. For example, the inlinestyles plugin, forces you to be locked into the [styles provided](https://github.com/craftcms/redactor/blob/v2/lib/redactor-plugins/inlinestyle/inlinestyle.js#L16-L40) (unless I'm missing something).

It would be awesome if we could pass in options from the Redactor config JSON files to override these.

**Comment by brandonkelly** [comment]
It’s upt oImperavi to make their plugins configurable, so I’ll pass this feedback on to them.

That said if you need to make a change to one of the bundled plugins, you can just copy the plugin into your `config/redactor/plugins/` folder, and make changes to it there. If the plugin is found in that directory, that one will take precidence over the bundled version.

**Comment by davist11** [comment]
Ah ok cool, didn't realize that we could make a copy in `config/redactor/plugins/`. That'll work for now, thanks!

**Comment by iMoses** [comment]
@brandonkelly I didn't realize it either and it's a great feature!
I recommend adding a reference to it in the README file...

**Comment by carlcs** [comment]
@davist11 I wrote the Custom Styles plugin that does exactly what you’re after. Have a look at the example JSON file https://github.com/carlcs/craft-redactorcustomstyles/blob/v3/_examples/redactor/Example.json

**Comment by davist11** [comment]
@carlcs I'm having <a href="https://github.com/craftcms/redactor/issues/58">this same issue</a> with your plugin too:

```
"button": {
	"args": {
		"tag": "a",
		"class": "button",
		"type": "toggle"
	}
}
```

![2018-07-02 14_44_34](https://user-images.githubusercontent.com/199985/42180810-946708a6-7e06-11e8-8455-4602464e2328.gif)

**Comment by carlcs** [comment]
@davist11 yeah, I can replicate, it appends a new anchor tag instead of applying the format to the selected tag. Unfortunatelly there’s nothing I can do, as this seems to be a bug with the `inline` service functions.

https://imperavi.com/redactor/docs/api-services/inline/

**Comment by bryantwells** [comment]
Just wanted to chime in here and second the comment made by @iMoses . Spent the better part of a day trying to put together a craft php plugin to add redactor functionality without knowing about the `config/redactor/plugins/` folder. Very convenient! I'm sure a quick line about this in the docs would save a lot of people time @brandonkelly .

**Comment by brandonkelly** [comment]
@bryantwells Done: https://github.com/craftcms/redactor/commit/06fbff665ea7c352260eafffa9a5de1b1d6e66b8

**Comment by nickolasjadams** [comment]
@brandonkelly 

Is it possible to do a similar thing with the redactor js files?

I want to modify CraftCMS's original configuration for images.

I can modify these lines in `vendor/craftcms/redactor/redactor.min.js`

```js
imagePosition: !1,
imageResizable: !1,
```

to 

```js
imagePosition: !0,
imageResizable: !0,
```

to get what I want.  But this obviously isn't a good idea because now I can't run updates.

I tried creating a copy here `config/redactor/redactor.min.js`
But that didn't work.  Is there a cool easy way to do this type of thing too?

If not, what do you think would be the easiest solution?

**Comment by andris-sevcenko** [comment]
Have you tried to set the relevant options in the Redactor config?

**Comment by nickolasjadams** [comment]
@andris-sevcenko 
Well I don't feel very smart now. 
But I'm definitely happy about how stupid easy that was.  Thanks!

**Comment by andris-sevcenko** [comment]
@nickolasjadams I'm just glad you got what you needed :)
