### ISSUE TITLE
[3.0.0-beta.1] Not possible to select available volumes (or transforms) in field settings, and assets selector HUD is empty

### ISSUE THREAD

**Issue by mmikkel** [craftcms/redactor#381]
### Description

No volumes appear under the "Available Volumes" setting.

When the field is saved, the setting stored is `"availableVolumes":"*"`, but the assets selector HUD opened via the Redactor field is empty.

### Steps to reproduce

1. Create a volume
2. Create a Redactor field, and observe that the volume (in fact, no volumes) show up for the "Available Volumes" setting
3. Add the Redactor field to a field layout and edit the element
4. Click the Image or File button in the Redactor field; observe that the assets selector HUD is empty

![CleanShot 2022-03-25 at 08 07 51@2x](https://user-images.githubusercontent.com/298510/160072066-ee7a738e-d38b-41d7-a7c1-fd7424653f5c.png)

<img width="1179" alt="CleanShot 2022-03-25 at 08 12 03@2x" src="https://user-images.githubusercontent.com/298510/160072222-75784e30-1208-40e7-9110-2e802242a6c7.png">

### Additional info

- Craft version: 4.0.0-beta.3
- PHP version: 8.0.15
- Database driver & version: MySQL 5.7
- Plugins & versions: Redactor 3.0.0-beta.1

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! Just pushed a fix for the next release.

**Comment by brandonkelly** [comment]
Redactor 3.0.0-beta.2 is out now with the fix.

**Comment by tibbis** [comment]
I still have this exact same issue on version 3.0.4, craft 4. The field is in side a matrix field. Is it really fixed?
