### ISSUE TITLE
Inserting entry link in other site suggests wrong site

### ISSUE THREAD

**Issue by umkasanki** [craftcms/redactor#382]
### Description
I still have same bug as https://github.com/craftcms/redactor/issues/372

> We have a multi domain setup, site-x.nl and site-y.nl, so separate site groups. The control panel works on site-x.
> When inserting a link we get the wrong site suggested

https://user-images.githubusercontent.com/496132/160275517-4f070d94-7cc5-4e63-b45b-6db1e2f324da.mp4

### Steps to reproduce

1. Install Craft
2. Add few subsites
3. Add new matrix field with reactor blocks
4. Try to create link in the matrix/redactor field

### Additional info

- Craft version:
- PHP version: 8.0.16
- Database driver & version: MySQL 8.0.28
- Plugins & versions:  Redactor 2.10.5

**Comment by brandonkelly** [comment]
Thanks for reporting! Redactor 2.10.9 and 3.0.1 are out with a fix for this.
