### ISSUE TITLE
[Craft CMS 4.0.0-beta4] Creating new redactor field not possible anymore

### ISSUE THREAD

**Issue by Nellyaa** [craftcms/redactor#386]
### Description

After updating my Craft CMS beta 3 to beta 4, creating a Redactor field is no longer possible. 
I just briefly looked but existing Redactor fields seem to show up and can be edited.
The browser console reveals a 400 error after choosing the Redactor field from the dropdown. ('Post request required')

### Steps to reproduce

1. Open 'Create a new field' page 
2. Change field type to 'Redactor'
3. Get a red message at the top:  'A server error occurred.'

### Additional info

- Craft version: Craft CMS 4.0.0-beta.4
- PHP version: 8.1.3
- Database driver & version: MySQL 10.7.3
- Plugins & versions: 
Craft Commerce	4.0.0-beta.2

Icon Picker	2.0.0-beta.2
ImageOptimize	4.0.0-beta.1
Navigation	2.0.0-beta.2
Redactor	3.0.0-beta.1
SEOmatic	4.0.0-beta.6

![Unbenannt-1](https://user-images.githubusercontent.com/38379317/162427092-d6388cf5-2e07-4c8a-9cc8-928a32b87ac2.jpg)

**Comment by JshGrn** [comment]
This is because of "Calling unknown method: craft\\services\\Volumes::getPublicVolumes()"

Issue still present
