### ISSUE TITLE
Third Redactor Field doesn't display

### ISSUE THREAD

**Issue by laurabennett** [craftcms/redactor#390]
### Description
Using three redactor fields in the same section causes the third to not display.

### Steps to reproduce

1. Create a Single and add multiple fields to the entry type including at least 3 redactor fields.
2. Edit the entry, Only the title of the third redactor field displays.

### Additional info

- Craft version: Craft Pro 3.5.19.1
- PHP version: 7.4.28
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Redactor	2.9.1
Admin Guide	2.1.2
Expanded Singles	1.2.0
Imager	v2.4.0
SEO	3.7.4

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Are you getting any JavaScript errors on the page?

**Comment by laurabennett** [comment]
It took me a bit to find this, looks like it is working on the live site with 3 Redactor fields but broken on dev so there must be some other variable. I'll see what else I can find.

Yes I am getting a javascript error.
Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at s.constructor.trigger (garnish.js:838:17)
    at s.constructor.initRedactor (RedactorInput.js:217:22)
    at s.constructor.init (RedactorInput.js:145:22)
    at s.constructor.constructor (garnish.js:768:19)
    at s.constructor (garnish.js:40:17)
    at new s.constructor (garnish.js:40:17)
    at HTMLDocument.<anonymous> (8-webpage:1381:1)
    at l (jquery.js:3762:29)
    at c (jquery.js:3830:12)

**Comment by laurabennett** [comment]
Redactor ver on live is 2.8.8. I will try to downgrade on dev and see if I still have the problem.

**Comment by laurabennett** [comment]
Downgrade fixed the problem so must be something between 2.8.8 and 2.9.1


PHP version	7.4.30
OS version	Linux 5.4.0-45-generic
Database driver & version	MySQL 5.5.5
Image driver & version	Imagick 3.7.0 (ImageMagick 6.9.10-23)
Craft edition & version	Craft Pro 3.7.46
Yii version	2.0.45
Twig version	v2.14.13
Guzzle version	7.4.5
Plugins
Admin Guide	2.1.2
Expanded Singles	1.2.0
Imager	v2.4.0
Redactor	2.8.8
SEO	3.7.4
