### ISSUE TITLE
Can't get source button to show up after latest update

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/redactor#40]
With the update, I can't use the source plugin anymore, but I can't seem to get the `source` button to show up on my toolbar.

This is my current `Standard.json` config:
```json
{
    "buttons": [
        "source",
        "formatting",
        "bold",
        "italic",
        "unorderedlist",
        "orderedlist",
        "link",
        "file"
    ],
    "plugins": [
        "fullscreen"
    ],
    "pastePlainText": true,
    "source": true,
    "formatting": [
        "p",
        "h3",
        "h4",
        "h5"
    ]
}
```
Toolbar looks like this:
![screenshot-safs local-2018 05 03-21-39-32](https://user-images.githubusercontent.com/7085184/39609903-81802436-4f1a-11e8-8ff5-7176c93bf9d7.png)

Previous config, that worked:
```json
{
  "buttons": ["formatting", "bold", "italic", "unorderedlist", "orderedlist", "link"],
  "plugins": ["source", "fullscreen"],
  "pastePlainText": true,
  "formatting": ["p", "h3", "h4", "h5"]
}
```

**Is anyone else having this problem?**

**Comment by KatieMFritz** [comment]
SOLVED: The button is called `html`. Whoops.

**Comment by fab4real** [comment]
Hello, i think you should udpate the doc or the Readme because adding "html" buttons only works if there is "source" = true.

That's not explained anywhere except reading all tickets in here. (i read all documentation both your Readme and the Redactor doc and could not find the proper solution)
