### ISSUE TITLE
Can't upload or select images when user is not an admin

### ISSUE THREAD

**Issue by pascalminator** [craftcms/redactor#409]
### Description

I can upload or select an image without any issues from the image button of redactor when I am an admin, but if I use a non-admin user, the image selection modal is totally empty (no upload button, no folders / images selection possible). This problem is happening in localhost and in production.:

![Capture d’écran 2022-05-26 105640](https://user-images.githubusercontent.com/13754636/170514921-d80b725d-ff7e-4031-abcc-3d8a7c27d33f.png)

If I try to upload an image from a non-redactor block, the modal is working fine:

![Capture d’écran 2022-05-26 110424](https://user-images.githubusercontent.com/13754636/170516474-a9c692ed-c807-41d1-9ca9-650de6980c80.png)

The non-admin users have the appropriate access rights to the assets and can browse them fron the "Assets" tab of Craft without any issues.  I never had this issue with Craft 3 + Redactor, this is the first time I encounter this.

### Steps to reproduce

1. Login as a non admin user and try to select / upload an image from redactor

### Additional info

- Craft version: 4.0.3
- PHP version: 8.1.5

**Comment by braedencrankd** [comment]
I am also having this issue with non-admin users. I can see the following error in my error logs where the CraftCMS web controller expects to receive JSON: `[web.ERROR] [yii\web\HttpException:400] yii\web\BadRequestHttpException: Request must accept JSON in response`.

**Comment by urbantrout** [comment]
I encountered the same problem. I’m pretty sure it has something to do with `$userService->checkPermission("viewVolume:$volume->uid")` here:
https://github.com/craftcms/redactor/blob/main/src/Field.php#L631

As a workaround I updated the field settings:

- ✔️ show unpermitted volumes
- ✔️ show unpermitted files
<img width="865" alt="Screenshot 2022-06-14 at 10 20 49" src="https://user-images.githubusercontent.com/10465787/173530375-ca5c9906-1726-4e5e-ab7c-e17f9282549d.png">

This fixes the problem for me.

**Comment by webrgp** [comment]
Having the exact same problem here

**Comment by brandonkelly** [comment]
This is fixed for the next release. Will tag it asap, but there are a couple other issues I want to address first.

To get the fix early, change your `craftcms/redactor` requirement in composer.json to `"dev-develop"` and run `composer update`.

**Comment by brandonkelly** [comment]
Redactor 3.0.1 is out now with that fix.
