### ISSUE TITLE
Site model in edit link dialog isn't switching with the currently selected site, causing issues

### ISSUE THREAD

**Issue by bencresty** [craftcms/redactor#412]
### Description

I just had to re-enter a lot of links because I was unaware this site selection dropdown actually wasn't automatically selecting the current selected site. Which was, sorry for the description, incredibly frustrating and shouldn't be necesary as Craft knows what site (in this case locale) we're on and it wouldn't make much sense to select another site to enter an entry as a link from (at least not per default). 

IMO the dropdown when adding a link to a site entry in the redactor field should ALWAYS be on the current selected site for new links. Only when there was already a link and we are editing it later it would make sense to use the previously selected site for the existing link as a default in the site dropdown in that insert link dialog.

The way it is now is prone to errors and needs all kinds of unnecesary actions by content editors, so really hope this could get a fix soon! 

### Steps to reproduce

1. Hava a multi-site setup with redactor fields (on this site they are within matrix blocks)
2. Go to a site that's not the first/default site
3. Enter text in the redactor field, select a text and hit 'insert link to entry'
4. Look at the site dropdown inside the dialog and see it's always on the first/default site. Without changing this to the site you are actually on you add a link to the entry on the wrong site/wrong locale!! (And you have to switch this again on other links you add)

### Additional info

- Craft version: 3.7.43
- PHP version: 8.0.12
- Database driver & version: Mariadb
- Plugins & versions: -

**Comment by bencresty** [comment]
BTW, I saw this issue: https://github.com/craftcms/redactor/issues/410  but it looks like that's talking about front end so another issue. But could be related.

**Comment by brandonkelly** [comment]
Thanks for reporting! Redactor 2.10.9 and 3.0.1 are out with a fix for this.

**Comment by bencresty** [comment]
> Thanks for reporting! Redactor 2.10.9 and 3.0.1 are out with a fix for this.

Sweet! Thanks, that's very welcome!
