### ISSUE TITLE
Source button missing on fields with custom configuration

### ISSUE THREAD

**Issue by tpmatthes** [craftcms/redactor#42]
First of all, thanks for porting this plugin to Redactor 3! It looks like a solid update for the editor experience. The migration of existing fields and configuration files was seamless, except for one (small) thing:

The [new Redactor docs](https://imperavi.com/redactor/docs/settings/source/) and the [Redactor plugin changelog](https://github.com/craftcms/redactor/blob/v2/CHANGELOG.md) explicitly state that the `source` option is set to true by default. However, if I use any custom configuration, the source button won’t show up in the Redactor field. It looks like this:

![redactor missing html button](https://user-images.githubusercontent.com/30212990/39661654-8326f918-5055-11e8-983b-eb8cff10bdc4.png)

For testing I’ve used the custom configuration example from [README](https://github.com/craftcms/redactor/blob/v2/README.md):

```json
{
    "buttons": ["format", "bold", "italic", "lists", "link", "file", "horizontalrule"],
    "plugins": ["fullscreen"]
}
```

If I add `"source": true`, Redactor just ignores it. I’ve tested this with existing _and_ new fields on existing _and_ new sites, all running Craft Pro 3.0.5.

Am I missing something? Maybe you can point me in the right direction.

**Comment by noxify** [comment]
This should solve your problem : https://github.com/craftcms/redactor/issues/40

**Comment by tpmatthes** [comment]
Thanks for the link! 👍 

I was a little bit confused, because the source button was a plugin before and the plugin migration removed the plugin entirely. I’ve tried to add `source` and `html` to `plugins`, of course it didn’t work. Why is there a `source` config option? What does it do?

Maybe we should update the example config in the README, I’ll create a small pull request.

Correct answer:

```json
{
  "buttons": ["html", "format", "bold", "italic", "lists", "link", "file"],
  "plugins": ["fullscreen"]
}
```

**Comment by andris-sevcenko** [comment]
> Why is there a source config option? What does it do?

Apparently it allows/disallows the use of that button :)
