### ISSUE TITLE
Formatting option is not being applied

### ISSUE THREAD

**Issue by market-south** [craftcms/redactor#438]
### Description
After updating to Craft 3.0.2 (Craft 4), the formatting options are not being applied to the contents. Previously, redactor automatically wraps the content into <p> tag.

### Steps to reproduce

1. Copy and paste some contents into the redactor field and try to apply formatting (ex: h2 tag)

### Additional info

- Craft version: 4.3.1
- PHP version: 8.1
- Database driver & version: mysql & 5.7
- Plugins & versions: 
> Neo
> Formie
> SEOMatic

Custom Redactor styles:
```
{
    "buttons": [
        "html",
        "format",
        "bold",
        "italic",
        "unorderedlist",
        "orderedlist",
        "image",
        "video",
        "link",
        "file"
    ],
    "linkNewTab": true,
    "toolbarFixed": true,
    "paragraphize": false,
    "plugins": [
        "customstyles",
        "fullscreen",
        "video",
        "alignment"
    ],
    "formatting": [
        "p",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "code"
    ],
    "customStyles": {
        "style": {
            "dropdown": {
                "Accent style": {
                    "args": {
                        "tag": "em",
                        "class": "tw-text-red",
                        "type": "toggle"
                    }
                },
                "Don't break words": {
                    "args": {
                        "tag": "span",
                        "class": "tw-whitespace-nowrap",
                        "type": "toggle"
                    }
                },
                "Paragraph 1": {
                    "args": {
                        "tag": "p",
                        "class": "paragraph1",
                        "type": "toggle"
                    }
                },
                "Paragraph 2": {
                    "args": {
                        "tag": "p",
                        "class": "paragraph2",
                        "type": "toggle"
                    }
                },
                "PDF Link": {
                    "args": {
                        "tag": "a",
                        "class": "pdfDownload",
                        "type": "toggle"
                    }
                },
                "Standard Heading style": {
                    "args": {
                        "tag": "h2",
                        "class": "tw-text-red",
                        "type": "toggle"
                    }
                }
            }
        }
    }
}
```

Small video demonstration:

https://user-images.githubusercontent.com/91921916/200740485-4d691272-0d7b-4a10-bc2f-8a4069a63606.mp4

**Comment by i-just** [comment]
Hi, thanks for getting in touch. This behaviour looks to be consistent in Craft 3 with Redactor v2 and Craft 4 with Redactor v3 and is triggered by `"paragraphize": false,` setting.

The last official reference I could find to the `paragraphize` setting is from 2015: https://web.archive.org/web/20151009220122/http://imperavi.com/redactor/docs/settings/clean/, but the setting still seems to be used when defined in the config file.

With `"paragraphize": false,` (in both Craft 3 and Craft 4), if you copy and paste a paragraph or part of it, it will be pasted in as plain text without any tags around it. This then causes block-related styles not to be applied when you select the text and choose a format from the dropdown. 

If you copy and paste a heading, it will be pasted as a heading, and if you then select the text and choose to change its format, the new format will be applied correctly.

I hope this helps!
