### ISSUE TITLE
Empty rich text fields add `<p><br></p>`

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/redactor#44]
After the latest update, my empty rich text fields are all putting code onto the page:
```html
<p>
  <br />
</p>
```

This is breaking my site a little, since I'm using `|length` to check whether to display fields in many cases, and this nothing code does have length. 😄 

Any advice? 

This is the redactor config I'm using:
```json
{
    "buttons": [
        "html",
        "formatting",
        "bold",
        "italic",
        "unorderedlist",
        "orderedlist",
        "link",
        "file"
    ],
    "plugins": [
        "fullscreen"
    ],
    "pastePlainText": true,
    "formatting": [
        "p",
        "h3",
        "h4",
        "h5"
    ]
}
```

**Comment by andris-sevcenko** [comment]
What version are you seeing this on? When I empty a redactor field (Cmd+A, Backspace), it gets saved as `null` to database. Can you check if that's what gets saved to your DB? You would need to look at the `craft_content` table, find the row that has the `elementId` set to the ID of your entry and look for the `field_XXX` column, where XXX is the handle of your Redactor field.

**Comment by andris-sevcenko** [comment]
I’ll try reproducing this again.

**Comment by KatieMFritz** [comment]
Hi @andris-sevcenko , any updates?

**Comment by andris-sevcenko** [comment]
Still no luck. Is this on a site where I could get CP access to? If so, could you send that over to support@craftcms.com?

**Comment by KatieMFritz** [comment]
Could I send you my database instead?

**Comment by andris-sevcenko** [comment]
@KatieMFritz sure thing.

**Comment by KatieMFritz** [comment]
I just sent the database over.

I just did some more testing in one of my entries that has several empty Redactor fields (https://safs.msu.edu/courses/intro-to-sustainable-agriculture-and-food-systems). Didn't see any code in the HTML view when editing the field, but the website showed `<p><br></p>`. Went into the database and saw the same thing. For one of those fields, I manually changed it to NULL in the database, and it persisted on the site, even after I saved the entry again in CP. I could do this as a workaround, but it would be tedious!

**Comment by shoored** [comment]
Ah I've been having the same issue. But - updating to Redactor 2.1.0 seemed to have fixed it. 

Craft 3.0.7
Redactor 2.1.0

Redactor config
```
{
    "buttons": [
        "html",
        "bold",
        "italic",
        "unorderedlist",
        "orderedlist",
        "link"
    ],
    "plugins": [
        "fullscreen"
    ],
    "toolbarFixed": true
}

**Comment by KatieMFritz** [comment]
@shoored It worked for me too!!! I had to go in and save my entries again but the empty paragraph didn't return. 🎉 Thanks for posting!
