### ISSUE TITLE
Linking from Images in Redactor Editor

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/redactor#45]
We should be able to select an image and then choose insert a link to where it goes. Redactor doesn't seem to want to play like that, it just inserts the link outside of the image. For some reason, I thought this worked but a client was asking about it and then I tried it as well.

The workaround is to insert a link, pull the URL out of the link (to make sure you get the reference tag), edit the image, and paste the link in. That seems very un-Craft-like to me.

Matrix blocks are obviously the way to go with that but sometimes you just want to make a link to a thumbnail or something else. As some clients transition from TinyMCE and WordPress, this is always how we've done it.

It would be nice if this box:
![screen shot 2018-05-08 at 11 51 08 am](https://user-images.githubusercontent.com/3707869/39771005-5d463980-52b6-11e8-8e0d-79a3013c3f4a.png)

... as well as a Url field, let you select an entry to link to as well. 

![screen-shot-2018-05-08-at-11 51 08-am2](https://user-images.githubusercontent.com/3707869/39771427-c689c834-52b7-11e8-9866-0712bc1d6eb2.jpg)

I think the would save some pain.

**Comment by mark-chief** [comment]
+1!

Another one of Redactors meh's and client gripes!

**Comment by brandonkelly** [comment]
I’ve passed this FR onto Imperavi.
