### ISSUE TITLE
IE 11 Script execution issue

### ISSUE THREAD

**Issue by magnessjo** [craftcms/redactor#46]
A client noticed that an entry (channel) page 'wasn't work right' while using IE 11.  

I investigated the issue and I was able to reproduce the error using browserstack version of IE 11. I believe that redactor is causing the problem due to the use of the 'includes' method.  I've attached two screen shots of the js error log.  

I tested the issue by removing all redactor fields from that entry.  The issue wasn't able to be reproduce at that point so I assume it it caused by redactor.  

I also did a search of the craftcms/cms directory for 'includes' and the only js files that were returned were RedactorInput.js and the Velocity.js files.  

My client is going to use Chrome going forward to enter content, but I wanted to enter the bug since the Craft and Redactor browser specs say they support IE 11.  

 
![screen shot 2018-05-09 at 12 44 04 pm](https://user-images.githubusercontent.com/856595/39828873-8d496bd2-538a-11e8-9519-9090fbd293a0.png)
![screen shot 2018-05-09 at 12 44 14 pm](https://user-images.githubusercontent.com/856595/39828874-8d600f72-538a-11e8-9c92-1af0386ec27a.png)

**Comment by andris-sevcenko** [comment]
Thanks!

**Comment by boboldehampsink** [comment]
Any idea when this is going to be released? This is also an issue on older Firefox browsers and my client happens to use that ;-)

**Comment by brandonkelly** [comment]
For posterity, this was fixed in v2.1.1 on 2018-07-13.
