### ISSUE TITLE
redactor should contain at most 65535 charcters

### ISSUE THREAD

**Issue by HudsonAustralia** [craftcms/redactor#465]
### Description
how can I increase this limit? I've never got this before, so weird.

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by angrybrad** [comment]
If you go to your Redactor field's settings, scroll to the bottom under "Advanced", you can change the underlying database column type from text (which supports 65 kb) to mediumtext (which supports 16mb).
