### ISSUE TITLE
Transforms now causing error when used with Redactor: finfo_file(FILENAME.jpg): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by page-8** [craftcms/redactor#47]
Issue:
Selecting an image and then a transform from the Redactor Modal Window produces a 500 Error

Steps to Reproduce:
1. Create a Transform
2. Create a WYSIWYG with an Image Button
3. Insert an Image with a Transform
4. Save the post.

```
finfo_file(writing.jpg): failed to open stream: No such file or directory

1. in /vendor/yiisoft/yii2/helpers/BaseFileHelper.php at line 158
```

**Comment by andris-sevcenko** [comment]
What Craft version are you using?

**Comment by noxify** [comment]
I can't reproduce the problem.

* Craft PRO 3.0.7
* Redactor 2.0.1

Assets Configuration:
* Volume: local ( `@webroot/uploads`)
* Transformer: Thumb / Small / Medium ( copied from the HappyLager example)

I have tested it with the following:
* Upload image via Redactor Editor
* Upload image via Assets page and choose it via the Redactor Editor

----

Question: 
* If you have no transformer defined, is it working? 
* Are all directory permissions set correctly

**Comment by page-8** [comment]
Ok thanks @noxify  - I'll dig deeper into it and try to get more info.

**Comment by noxify** [comment]
I have tested it with an Matrix field - and it's working, too.

<img width="963" alt="bildschirmfoto 2018-05-11 um 15 36 48" src="https://user-images.githubusercontent.com/521777/39926988-316900d6-5531-11e8-975d-7b4a890eaee9.png">

**Comment by noxify** [comment]
Maybe you can give it a try with a fresh installation?

**Comment by page-8** [comment]
Thanks for the help @noxify. I'll keep digging.

**Comment by page-8** [comment]
Not sure this helps at all, but for some reason it's not getting the full file path for my transformed image, just the filename:

```
5. in /vendor/craftcms/cms/src/helpers/FileHelper.php at line 260 – yii\helpers\BaseFileHelper::getMimeType('test-file.jpg', null, true)

     /**
     * @inheritdoc
     */
    public static function getMimeType($file, $magicFile = null, $checkExtension = true)
    {
        try {
            $mimeType = parent::getMimeType($file, $magicFile, $checkExtension);
        } catch (\Throwable $e) {
            if (!$checkExtension) {
                throw $e;
            }
            $mimeType = null;
        }
```

**Comment by jameskrill** [comment]
I had this issue just happen. What I figured out in my case, is that the selected image source had a smaller resolution/size than the transform selected, resulting in the file not being found. 

Seems like a bug that you could select a transform that doesn't exist... OR... craft should fall back on the next available transform. 

For example, if the transform 'full' is 1600px wide, but your source image is 800px, the source image should be served if 'full' is selected as the transform to insert. Or better yet, you shouldn't be able to select that transform when inserting the image.

**Comment by page-8** [comment]
Thanks @jameskrill  -- Unfortunately that's not it in my instance.

I've tracked this down to a change in `vendor\craftcms\cms\src\elements\Asset.php` on line `708` in either 3.0.6 or 3.0.7

Specifically `FileHelper::isGif($this->filename)` is causing my problem. If I remove that, the issue is gone.

**Comment by noxify** [comment]
@page-8 - Is this then not a craftcms/cms issue?

Btw. The path info was removed in this commit:
https://github.com/craftcms/cms/commit/112e2f63c91f7a7ed77c65674d5475775e889328#diff-1439c2c7558601e6752050108ba410d4L708

**Comment by andris-sevcenko** [comment]
@page-8 
> Without being more familiar with the codebase I'm not sure if there are repercussions to this.

This will fail for remote Volumes, sadly.

The codeblock you [pasted above](https://github.com/craftcms/redactor/issues/47#issuecomment-388379496) is there exactly because Craft sometimes needs to decide on the mimetype based just on the filename. It's curious that it's not working for you, though.

Are you, by any chance, overriding or disabling the error handler component in your app configuration? That particular block of code relies on Yii's error handler converting errors to exceptions.

**Comment by page-8** [comment]
@andris-sevcenko 

That's what's really weird about this. The only place the exception is (seemingly) not getting caught is in the Redactor Transform. For example, I'm not getting an error on the Assets Listing page.

`Are you, by any chance, overriding or disabling the error handler component in your app configuration? `

No, this is the only thing in my general config:

```
'*' => [
        'defaultWeekStartDay'  => 0,
        'enableCsrfProtection' => true,
        'omitScriptNameInUrls' => true,
        'cpTrigger'            => 'webmaster',
        'securityKey'          => getenv('SECURITY_KEY'),
        'useEmailAsUsername'   => true,
        'allowUpdates'         => false,
        'phpSessionName'       => 'MTMSessId',
        'sendPoweredByHeader'  => false,
    ],
```

This is happening on my local environment using MAMP 4 and the Arcustech server where we have the site hosted. 

This is also happening for me on a fresh installation of Craft 3 with only the Redactor plugin installed and one field type called `Body` with one Transform called `testTransform`

Per your comment @noxify , it seems like it's only happening with Redactor's use of this only when it comes to a transform. (as far as I can tell)

**Comment by andris-sevcenko** [comment]
Got it, I'll see if I can reproduce!

**Comment by andris-sevcenko** [comment]
See the issue, working on a fix

**Comment by page-8** [comment]
Sweet, thanks @andris-sevcenko !
