### ISSUE TITLE
Server error when entry form is opened 

### ISSUE THREAD

**Issue by ejaedesign** [craftcms/redactor#484]
### Description

When an entry form is opened, it results in a server error. When Redactor is disabled, the entry form can be opened (but no content in the Redactor field will show on the front-end)

### Steps to reproduce

1. Enable Redactor
2. Open an entry in the CP

### Additional info

- Craft version: 3.9.10
- PHP version: 8.0.30
- Database driver & version: MariaDB 5.5.68
- Plugins & versions: Redactor 2.10.12

**Comment by ejaedesign** [comment]
Just to add, the trouble started to happen when Craft was updated to the latest version via CLI. 

It somehow deleted ("missing") all plugins and I had to re-install each separately using CLI.

**Comment by brandonkelly** [comment]
It sounds like this is a Composer issue. If you’re still having trouble with it, please write into support@craftcms.com.
