### ISSUE TITLE
Can't select available volumes

### ISSUE THREAD

**Issue by tibbis** [craftcms/redactor#485]
### Description
Can't select available volumes in the redactor field settings and the window is empty when trying to select an asset in the frontend. 
<img width="984" alt="Screenshot 2024-02-05 at 09 49 36" src="https://github.com/craftcms/redactor/assets/26073077/5edb8262-6cce-4d0d-a804-81a0d41807d1">

### Steps to reproduce

1. Add Redactor field to section
2. Try to select assets

### Additional info

- Craft version: Craft Solo 4.7.1
- PHP version: 8.1.22
- Database driver & version: Servd platform 3.5.9
- Plugins & versions: Redactor 3.0.4

Redactor config:
`{
  "buttons": [
    "html",
    "formatting",
    "bold",
    "italic",
    "deleted",
    "unorderedlist",
    "orderedlist",
    "outdent",
    "indent",
"link",
 "file",
    "alignment",
    "horizontalrule"
  ],
  "formatting": [
    "p",
    "blockquote",
    "pre",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6"
  ],
"plugins": ["alignment", "table", "imagemanager"]
}`

**Comment by iamtompickering** [comment]
Also having this issue, is there any update on a fix for this?

**Comment by tibbis** [comment]
> Also having this issue, is there any update on a fix for this?

It was related to servd asset plugin: 
The two things that control what Volumes show on the Field Settings' page are

1. The existence of Volumes
2. Whether the filesystem associated with the volume has its **'Files in this filesystem have public URLs' option enabled**


the second point fixed it for me!

**Comment by iamtompickering** [comment]
@tibbis cheers for this!
