### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by vandres** [craftcms/redactor#489]
Hi!

This is not a bug report per se. I was just browing through the new Craft 5 upgrade dialog and saw, that this plugin is abandoned. Is that real or a bug?

![grafik](https://github.com/craftcms/redactor/assets/1436383/8e45f9d2-2f52-4007-b2ef-b37ff7dd84c4)
![Bildschirmfoto 2024-03-27 um 13 23 17](https://github.com/craftcms/redactor/assets/1436383/eddccaff-5d60-44e0-8360-c90c20a8302e)

**Comment by rinusvandam** [comment]
I have a small addition to this. I've updated two Craft sites to version 5. When I check the CP updates section, I'm seeing a “This plugin is no longer maintained.” message. See attached screenshot (It's in Dutch). 

<img width="762" alt="Scherm­afbeelding 2024-03-27 om 13 58 20" 
src="https://github.com/craftcms/redactor/assets/6650702/12f1b786-715c-477b-9f8c-4142ecf3c527">

**Comment by robzor** [comment]
Yeah, they've gone all in on CKEditor. See this for info:

https://github.com/craftcms/ckeditor#:~:text=Converting%20Redactor%20Fields,CKEditor%20config%20will%20be%20created.

Looks like a relatively painless switch?

**Comment by zadro** [comment]
Not painless if using custom Redactor configs and plugins...

**Comment by samdi** [comment]
How to switch a Redactor field to CKEditor? Any problem if continue using Redactor plugin for Craftcms 5 or later?

**Comment by rjgux** [comment]
I see the `4.0.x-dev` branch supports > Craft 5 beta - will that branch receive any further updates/is it safe to use now we have the full release of Craft 5?

**Comment by johannesSolvr** [comment]
This is a wierd move, we have more than 40 projects, a lot with custom plugins and configs that needs to be converted to CK editor. Just abandoning this plugin without warning is a huge blow for us. Redactor have been the main editor for craft for as long as I can remember, all our projects are using redactor, so just abandoning it over night like this without a warning is conserning regarding how pixel and tonic handles backwards compability. 

I can understand that you want to focus on CK editor, and I understand the choice. But there are thousands (over 78 000) of projects using redactor, a lot using custom configs, and also custom plugins spesific for that project. Now we have to go and update all of our projects to CK editor, convert the fields, create new configs to make CK editor work like redactor, so the clients don't need additional training, and also see if it is even possible to recreate the custom plugins we have made for redactor. 

If we knew that this would happen in andvance, we could have planned this over time. But the way this is done is properly dissapointing. 

This is not how I expected pixel and tonic to handle the lifecycle of one of the most popular

**Comment by robzor** [comment]
@johannesSolvr I'm pretty sure they did say they were going to stop supporting Redactor when Craft 5 came out but I can't find the post where I saw it!

https://www.craftcms.com/blog/ckeditor-revamped

Is the closest I can find to it, but maybe it was in a DotAll recap or something.

**Comment by domstubbs** [comment]
Just to echo the above comment – this feels like an odd choice and the lack of communication on the subject is not what I would’ve expected. According to the plugin store there are around [80k](https://plugins.craftcms.com/redactor) active Redactor installs and [10k](https://plugins.craftcms.com/ckeditor) of CK Editor, so we’re hardly talking about a feature that no one will miss.

This will put me off installing Craft 5 for several projects as the cost/benefit ratio shifts fairly drastically in the wrong direction if you have to retrain everyone to use a new editor.

**Comment by brandonkelly** [comment]
That Upgrade utility is a little misleading: despite being abandoned, Redactor has in fact been updated for Craft 5. You can set `craftcms/redactor` to `^4.0.0` when updating, and deal with converting to CKEditor later on. (The next Craft 3 and 4 releases will [start showing](https://github.com/craftcms/cms/commit/0473839613b9f75edd0796ff27f7a322da4f6d49) compatibility info for abandoned plugins.)

That said, we’ve been signaling for a while now that Redactor is on life support. Redactor II, the editor it’s powered by, has been dead for some time, and we have no plans to switch to Redactor X, as it would be a pretty major effort (given all the code hacks we’ve had to make) with little benefit.

CKEditor 3.x (Craft 4) and 4.x (Craft 5) have feature-parity with Redactor in terms of Craft integration, and include a [`ckeditor/convert`](https://github.com/craftcms/ckeditor?tab=readme-ov-file#converting-redactor-fields) command which makes converting from Redactor a breeze. And feedback has been extremely positive. We haven’t heard any reports of clients struggling with the new editor UI.

**Comment by zadro** [comment]
@brandonkelly I think we all understand. We're just bummed to rewrite plugins that took many hours (weeks) to create. For example, I have a custom plugin that manages link color classes, inserts affiliate codes, and many other inline features for affiliate-based options. The convert feature is nice for fields, though. Too bad it will not help with custom plugins. 

More so, CK Editor is not working properly (in Craft 4). I created a custom config to test it out, and the added elements are not showing when applying the new config to the field. I'll look to open an issue on CK Editor.

**Comment by brandonkelly** [comment]
@zadro Even if we took the time to upgrade to Redactor X, that’s a complete rewrite which would require you to rewrite your custom plugins. So there’s no getting around the need to do that extra work. Since Redactor does work on Craft 5, nothing forces you to do it _now_ any more than any other point in the past year, since CKEditor 3.0.0 came out and we said Redactor is going to be phased out. If you’re happy to continue using an old, unsupported rich text editor, you can keep doing that until Craft 6 :)

**Comment by zadro** [comment]
@brandonkelly, that's good to know about Redactor X. Well, that fact closes the issue for me, at least. Time to learn CK!

**Comment by brandonkelly** [comment]
Craft 3.9.13 and 4.8.7 are out with that upgrade utility fix:

![A row in the Craft 5 Upgrade utility, showing that Redactor is compatible at version 4.0.0, but also abandoned.](https://github.com/craftcms/redactor/assets/47792/af333946-a798-4230-81e3-f30a1278350c)

**Comment by smockensturm** [comment]
And how do we get rid of this?

`OK: You need to be on at least Redactor 3.0.0 before you can update to Redactor 4.2.0.`
