### ISSUE TITLE
Links not editing correctly

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [craftcms/redactor#50]
Hard one to explain so here's a video!

https://youtu.be/8L0UkFF2YXo

When trying to edit a link, upon saving, link is duplicated and saves over link before the one being edited.

Any thoughts?

**Comment by andris-sevcenko** [comment]
In essence this is a duplicate of #48

**Comment by DynamiteGoesBoom** [comment]
Will you re-open the other task @andris-sevcenko?

**Comment by andris-sevcenko** [comment]
Hmm. If you type `$R.version` in your browser's dev console, what do you get?

**Comment by DynamiteGoesBoom** [comment]
Client is also reporting this:

> I can link to a url now but not an entry and it’s actually worse because the modal doesn’t disappear but every-time you click save it’s adding that text as a link on the line above.

**Comment by jameskrill** [comment]
@andris-sevcenko 3.0.9

**Comment by andris-sevcenko** [comment]
@DynamiteGoesBoom @jameskrill is it possible to get access to a site where I can see this behaviour? I'm not able to reproduce this locally (as opposed to I was able to reproduce the original issue in this ticket pre-3.0.9)

**Comment by andris-sevcenko** [comment]
If the answer is yes, then can you send the credentials to support@craftcms.com referencing this ticket?

**Comment by DynamiteGoesBoom** [comment]
@andris-sevcenko Sent!

**Comment by andris-sevcenko** [comment]
FTR this is a bug with Redactor 3.0.9 and I've submitted a bug report to Imperavi.
