### ISSUE TITLE
Uncaught TypeError: $R[s][t] is not a constructor

### ISSUE THREAD

**Issue by monkeyphysics** [craftcms/redactor#52]
Hi,

first a disclaimer: I'm a first time Craft user (but a long time developer).
Today I installed Craft, running it in local Docker containers. I created my first Section (a Single), and upon defining the Entry-type realise I want richt-text, so installed this Redactor plugin (v2.1.0).

Having this Single section, with only one field 'Body' being the Redactor rich-text type. I paste in some plain text in the HTML source (to prevent automatic formatting) and save. Upon editing the entry I'm getting a javascript editor, and no Redactor menubar (the text itself renders fine, including some formatting being done (Youtube link expanded into embedded video, for example), but cannot be edited).

```
jquery.js:3869 Uncaught TypeError: $R[s][t] is not a constructor
    at Function.$R.create (redactor.js:1491)
    at s.<anonymous> (redactor.js:8931)
    at Dom.each (redactor.js:244)
    at s.observe (redactor.js:8919)
    at s.onautoparseobserve (redactor.js:10017)
    at App.callMessageHandler (redactor.js:2249)
    at App.broadcast (redactor.js:2268)
    at s.onstartcode (redactor.js:10668)
    at App.callMessageHandler (redactor.js:2249)
    at App.broadcast (redactor.js:2268)
```

**Comment by andris-sevcenko** [comment]
Can you share the snippet you pasted? Does this happen to every redactor field you paste that snipper to?

I'm unable to reproduce this locally.

**Comment by monkeyphysics** [comment]
I will try and reproduce it in another section / redactor field. If it's persistent, I'll share the snippet (but in a private message if that's possible).

**Comment by andris-sevcenko** [comment]
Of course - just send it over to support@craftcms.com and reference this issue.

**Comment by monkeyphysics** [comment]
I have been able to reproduce this again, with another snippet. My specific case:
1. Create new Section, type Single
2. Edit field type
3. Select Field Group with one field called 'Body', being a Redactor field
4. Go to 'Edit Entries'
5. Edit newly created section
6. Switch Redactor to HTML-mode
7. Paste the snippet https://pastebin.com/raw/kLmG9u9a (link expires in 24 hours)
8. Switch Redactor back to Preview-mode
9. Save Section
10. Edit Section => javascript error + malfunctioning Redactor

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this. Is it possible to get access to a system where you can reproduce this? If so, can you please email us at the email address posted above?
