### ISSUE TITLE
Site selection not working in link dialog

### ISSUE THREAD

**Issue by jacksutherland** [craftcms/redactor#53]
I have a multi-site set up, with a different language for each site. In my redactor rich text editor, I need to create links to entries from a different site/language. However when I change the site/language in the drop down, the entries for that site/language do not display... It only shows the entries for whatever the current site is. See screenshot.

![image](https://user-images.githubusercontent.com/1928834/40197054-4b434026-59e0-11e8-97a5-7c06f4b17b2b.png)

Steps to reproduce:
1. Create 2 or more sites
2. Add entries to both.
3. Add a redactor field to an entry.
4. Edit entry, add text to rtf
5. select text and click hyperlink button
6. change site in site drop down
7... Entries do not change for the site selected

**Comment by jacksutherland** [comment]
I think it would be useful to be able to select an entry from another site within the same craft instance, as often the sites are related in this scenario. However if not, then the drop down should be hidden, because my clients are confused by it... If it's there people are going to try to use it.

**Comment by andris-sevcenko** [comment]
I agree with that but that's impossible until Craft reference tags support specifying the site as well. If an entry is present in two sites, it still has just one entry id, so, unless the site is also specified, Craft would have no idea which entry should be displayed.

The immediate solution is to remove the dropdown and, once reference tags support site, allow selecting the site.

**Comment by timkelty** [comment]
> Before this is addressed we must add support for specifying site in reference tags.

This was just added to 3.2! https://github.com/craftcms/cms/issues/2956
Hoping we can now see this fixed in Redactor.

/cc @andris-sevcenko

**Comment by tomastech** [comment]
I am seeing a similar issue, except it's when pulling in redactor field from site A entry to site B via entries field (craft 3.2.0-beta.1).

Site A entry with a redactor field has a link to another entry within Site A. When site A field is rendered on site B, it shows up unprocessed (i.e. {entry:2:url} ).

**Comment by gregkohn** [comment]
@andris-sevcenko Thanks for your explanation above. Any word on when this will be fixed?

**Comment by steverowling** [comment]
Any news on when this might be fixed to allow linking to entries across sites in multi-site installs from within a Redactor field?

**Comment by brandonkelly** [comment]
This is resolved in Redactor 2.5 thanks to @steverowling’s PR! (2.5 requires Craft 3.4 RC1+)

**Comment by timkelty** [comment]
Greta work @steverowling!!!
