### ISSUE TITLE
Noto Font Support for Traditional Chinese

### ISSUE THREAD

**Issue by jacksutherland** [craftcms/redactor#57]
We're importing a Google Noto font to one of our Craft sites that is in Traditional Chinese. The font contains over 40,000 characters. I need a way for the users to enter this text content in the CMS with the same font. Is this already possible with the Redactor plugin, and if so can you point me to a doc or example? And if not, do you have any suggestions for how to accomplish this?

**Comment by andris-sevcenko** [comment]
This could be accomplished with the help of the CP CSS plugin.
