### ISSUE TITLE
Custom inlinestyle plugin utilizing module.inline.format or module.inline.toggle not working

### ISSUE THREAD

**Issue by davist11** [craftcms/redactor#58]
I took your advice from #38 and copied the `inlinestyle.js` plugin over to my `config/redactor` folder.

Basically, I'm trying to toggle a class on a link, so I adjusted the code in the plugin to be

```
this.styles = {
	"button": {
		title: "Button",
		args: {
			tag: 'a',
			class: 'button',
			type: 'toggle'
		}
	},
	"button_hollow": {
		title: "Button - Hollow",
		args: {
			tag: 'a',
			class: 'button -hollow',
			type: 'toggle'
		}
	}
};
```

That doesn't really work because it inserts an extra link even when you have a link selected. So I modified the code to use the <a href="https://imperavi.com/redactor/docs/api-modules/inline/#s-toggle">module.inline.toggle</a> API method, and even grabbed the example `args`, but none of those attributes were added after applying the style. Since we technically haven't purchased Redactor, I couldn't submit the issue directly to them.

**Comment by davist11** [comment]
This conversation better describes what is going on: https://github.com/craftcms/redactor/issues/38#issuecomment-401897859

Is this something that should get submitted to Redactor itself?

**Comment by andris-sevcenko** [comment]
Is this still an issue if you download the latest redactor version from the Redactor site and replace the redactor.js files in the plugin? There's been an update recently and there's a chance this might have been fixed.

**Comment by davist11** [comment]
Can I download Redactor directly from their site without a license?

**Comment by davist11** [comment]
File sent

**Comment by andris-sevcenko** [comment]
I've just passed this onwards to Imperavi. They're not the most communicative bunch, so let's wait and hope they resolve it. If in the meantime, you come up with a patch that makes this work as you need it to work, feel free to forward a patch and we can add that to https://github.com/craftcms/redactor/blob/v2/src/assets/field/dist/js/RedactorOverrides.js
