### ISSUE TITLE
Plugin buttons are not shown in craft 3.10.0.1

### ISSUE THREAD

**Issue by arjankruithof** [craftcms/redactor#59]
```
"plugins": [
        "clips",
        "fullscreen"
    ],
```

**Comment by lukebailey** [comment]
Experiencing the same issue - thought I was going mad!

**Comment by andris-sevcenko** [comment]
What Redactor plugin version are you using? Did the buttons show up prior to 3.10.0.1?

**Comment by lukebailey** [comment]
I am on redactor version 2.1.0, can't be sure if this was also a problem with Craft 3.10.0 as well.

**Comment by lukebailey** [comment]
This is now resolved with Craft 3.0.10.2

**Comment by lukebailey** [comment]
Actually the issue is now more severe, whilst editing the plugin is fine but upon saving the text disappears and can no longer be seen/edited:

![image](https://user-images.githubusercontent.com/3185073/41107278-f665c084-6a69-11e8-955b-645538993406.png)

**Comment by andris-sevcenko** [comment]
Closing this, then? If anyone is still experiencing this with Craft 3.0.10.3, let me know.
