### ISSUE TITLE
Improved Image handling

### ISSUE THREAD

**Issue by ncc-jwood** [craftcms/redactor#6]
Can you add improvements to how image attachments are handled?  The ability to select image classes from an admin-defined list would be ideal to me for image manipulation in CSS, but if that's not practical then attaching the name of the image transform as a css class  to the image would also be workable solution.

Also, the ability to change the applied transform on an image you've already added to the field would also be appreciated.

**Comment by brandonkelly** [comment]
You’re probably better off swapping your Redactor field for a Matrix field, with Text (Redactor) and Image block types. The Image block type could have a Assets field and a Dropdown field for choosing the transform.
