### ISSUE TITLE
Table plugin translations are not used

### ISSUE THREAD

**Issue by ockam** [craftcms/redactor#63]
I have added a `redactor.php` to my translations directory with translations for the Table plugin. I can confirm the `registerAssetFiles` from `RedactorAsset.php` properly loads them in the UI and that they are added to the $R object.

But somehow, the plugin menu won’t use the locale strings: they are in English while the rest of the Redactor UI is in the locale.

**Comment by andris-sevcenko** [comment]
I'm clarifying this with Imperavi. Seems like translating plugins is a bit tricky compared to Redactor itself.
