### ISSUE TITLE
Set everything bold, italic or underlined doesn't work when everything is selected (CMD + A)

### ISSUE THREAD

**Issue by mdominguez** [craftcms/redactor#65]
[See screencapture](https://cl.ly/siiT)

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this. Are you getting any javascript errors in the browser's console?
What version of the plugin are you using?

**Comment by mdominguez** [comment]
No JS errors in the console unfortunately.
I'm using the latest Redactor plugin version 2.1.0

**Comment by andris-sevcenko** [comment]
Can you try updating to 2.1.1 that we just released and try again?

**Comment by mdominguez** [comment]
I updated but unfortunately still experiencing the issue

**Comment by andris-sevcenko** [comment]
Ah, got it. It's a Redactor bug; I submitted a bug report to Imperavi. Hopefully, they'll fix this one soon.

**Comment by andris-sevcenko** [comment]
Still unfixed as of Redactor 3.1.1
