### ISSUE TITLE
CMD + A and try to unorder-list it erases the selected block...

### ISSUE THREAD

**Issue by mdominguez** [craftcms/redactor#66]
god damn it :) didn't have these issues with Redactor in Craft 2 [view screenrecording](https://cl.ly/shnv)

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this. What Redactor plugin version are you using? Can you reproduce this on https://imperavi.com/redactor/ ?

**Comment by mdominguez** [comment]
Yep, just paste 2 paragraphs of lorem ipsum and then CMD / CTRL + A to select everything. Then click to make a list of it and nothing happens. Probably related to #65 :)

**Comment by andris-sevcenko** [comment]
Yup, definitely related. Closing this one as a duplicate of #65.
