### ISSUE TITLE
Redactor fields inside matrix are not showing up after latest update

### ISSUE THREAD

**Issue by cballenar** [craftcms/redactor#68]
This is pretty weird... after the latest update some of my fields (which are inside matrix blocks) are not appearing. All I see is the label of the field. I was getting `is not an indexOf` error related to redactor.
Then I removed the field from the section, added it back, and I'm no longer seeing the error BUT the field hasn't come back yet.

A side note, some of these fields were regular text fields before. They worked before, not sure if the latest update affected that somehow.

Anyone else experiencing this?

**Comment by cballenar** [comment]
Follow up:
I rolled back to v 2.1.0 and the issue is gone, however as it turns out the indexOf error reported before was already there.

**Comment by andris-sevcenko** [comment]
Can you share the "indexOf error"?

**Comment by andris-sevcenko** [comment]
Should be fixed with the release of 2.1.2 just now.
