### ISSUE TITLE
Unknown property redactorLang

### ISSUE THREAD

**Issue by BryceBubbles** [craftcms/redactor#74]
Getting unknown property error when trying to edit entries.

``
yii\base\UnknownPropertyException: Getting unknown property: 
craft\redactor\assets\redactor\RedactorAsset::redactorLang in ..vendor\yiisoft\yii2\base\BaseObject.php:141
``

Relevant code seems to be on line 246 of: `vendor\craftcms\redactor\src\Field.php`

Craft: 3.0.17.1
Redactor plugin: 2.1.4

Not sure if this is a bug or something wrong with my composer setup. 
I don't have time to test on a fresh install or narrow things down more atm.

**Comment by BryceBubbles** [comment]
I believe line 246 of Field.php:
`$redactorLang = $bundle->redactorLang ?? 'en';`
needs to be:
`$redactorLang = $bundle::$redactorLanguage ?? 'en';`
because of 7a3bdea

No time to add a pull request sorry.

**Comment by brandonkelly** [comment]
@BryceBubbles thanks for reporting! We just released v2.1.5 with a fix.
