### ISSUE TITLE
Able to copy/paste more than is allowed in fields

### ISSUE THREAD

**Issue by robinleblon** [craftcms/redactor#75]
When copy/pasting in a redactor field with a limited amount of characters, the limit is ignored.
Seems to be fixed in [Redactor 3.1](https://imperavi.com/redactor/log/)
Could be easily fixed by updating from 3.0.11 to 3.1.

**Comment by andris-sevcenko** [comment]
@robinleblon should be fixed with the 2.1.6 release, which includes Redactor 3.1.1
