### ISSUE TITLE
linkNewTab in configs not working

### ISSUE THREAD

**Issue by jolyonruss** [craftcms/redactor#76]
I'm trying to activate the Link in new tab feature of redactor.

I've edited both the Simple.json and Standard.json configs to look like this:

Standard.json
```
{
    "buttons": [
        "formatting",
        "bold",
        "italic",
        "unorderedlist",
        "orderedlist",
        "link",
        "image",
        "video"
    ],
    "plugins": [
        "fullscreen",
        "video"
    ],
    "linkNewTab": true,
    "toolbarFixed": true
}
```

Simple
```
{
  "buttons": ["bold", "italic", "lists"],
  "linkNewTab": true,
  "toolbarFixed": true
}
```

Is there anything else I need to do in order to get this to work?

**Comment by olsp** [comment]
@jolyonruss how did you solve it?
For me it just happened that it worked for one craft installation yesterday, for another one it doesn't.
