### ISSUE TITLE
Image and File buttons still missing.

### ISSUE THREAD

**Issue by justinrclarke** [craftcms/redactor#77]
Running Craft version `3.0.17.1`.

I'm still experiencing the issue with the image and file buttons missing. The only version I can get them to show up is version `2.1.0`. Using any version higher removes the buttons. Even if I use version `2.1.1` the buttons are still missing.

I'm not getting any errors that could help solve the issue.

**Comment by andris-sevcenko** [comment]
> Even if I use version 2.1.1 the buttons are still missing.

Even if you use the latest 2.1.5? Could you update to that and see if you still have the issue. If you do, is this a site where it's possible to get CP access to? If so, can you shoot it over to support@craftcms.com?

**Comment by justinrclarke** [comment]
I upgraded from 2.1.0 to 2.1.5 and that is when I noticed that the buttons were no longer there. So I cannot upgrade to 2.1.5 because it will disable features my team needs.

I will send an email to discuss CP access.

**Comment by andris-sevcenko** [comment]
Closing for now, as I'm unable to reproduce and there's lack of activity.

**Comment by justinrclarke** [comment]
Yes this is still an issue. There has been lack of activity because I'm using my current fix as mentioned above. Do I need to fix it myself and respond to this thread with the solution?

**Comment by andris-sevcenko** [comment]
Right, well, I can't reproduce this locally and I can't find that email you wanted to send - probably life got in the way as we're all busy people :)

If you could get around to sending that email, I could try to see what's what and try to fix it.
