### ISSUE TITLE
Custom classes for image position fails

### ISSUE THREAD

**Issue by nordentwickler** [craftcms/redactor#79]
Hey, i would like to use custom classes for image position in the redactor field. This is my Standard.json file:

```json
{
  "buttons": [
    "formatting",
    "bold",
    "italic",
    "unorderedlist",
    "orderedlist",
    "link",
    "image",
    "video",
    "horizontalrule"
  ],
  "imageResizable": true,
  "imagePosition": [
    "None": "image",
    "Left": "float-left",
    "Center": "center",
    "Right": "float-right"
  ],
  "imageFloatMargin": "2rem",
  "plugins": [
    "fullscreen",
    "video"
  ],
  "toolbarFixed": true
}
```

The "imagePosition" is set based on the redactor documentation: https://imperavi.com/redactor/docs/settings/image/#s-imageposition

Getting a syntax error in the backend with this config. If only "imagePosition" is set to true, everything works fine, in fact without custom classes.

**Comment by nordentwickler** [comment]
Ok, my json wasn't corret. This seems to work kind of:

```json
  "imagePosition": {
    "none": "image",
    "left": "float-left",
    "center": "center",
    "right": "float-right"
  },
````
But i'm not able to change the name of the position. Like instead of "left" -> "links"

**Comment by brandonkelly** [comment]
Glad you got the JSON syntax sorted. I don’t see anything in the `imagePosition` docs about renaming the position labels though; guessing that’s not possible.
