### ISSUE TITLE
Add support for Redactor 3

### ISSUE THREAD

**Issue by angrybrad** [craftcms/redactor#8]
Currently in beta: https://imperavi.com/beta

**Comment by unioncodev** [comment]
This is out of beta now - https://imperavi.com/redactor/

**Comment by DanielDarrenJones** [comment]
+1, would really like to see the plugin updated to V3 as it has so many useful plugins bundled!

**Comment by angrybrad** [comment]
On the list, but not going to happen until after 4/4/18 Craft 3 launch!

**Comment by codyjames** [comment]
I'd like to use this for a feature I have to build yesterday. Any chance this'll get done soon?

**Comment by woeye** [comment]
It also seems that the documentation for Redactor 2 is gone missing from Imperavi's website. Which makes it a bit tricky to use this plugin - like which settings to use

**Comment by brandonkelly** [comment]
We just released v2.0.0 which is now powered by Redactor 3.
