### ISSUE TITLE
IE11 bug with creating links

### ISSUE THREAD

**Issue by mikecsmith** [craftcms/redactor#85]
A client of ours identified a problem creating links in IE11 using Redactor yesterday when running version 2.1.5.

When creating a link the a tag was not applied to either text or images.

Following the update for 2.1.6 which we performed today, which had a fix for a similar bug in Firefox, the issue with creating links when highlighting text was resolved (thanks!).

Unfortunately there's still an issue creating links when highlighting an image in IE11 - you're able to go through the interface but on completing the link creation process it doesn't apply.

**Comment by andris-sevcenko** [comment]
Unfortunately, Redactor does not support IE11 (https://imperavi.com/redactor/docs/get-started/initialization/#s-requirements). 

Updating to the latest Redactor has not fixed this issue for IE11 and it's not very likely that it'll be ever fixed...
