### ISSUE TITLE
Sticky toolbar not working

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/redactor#9]
The sticky toolbar doesn't work, making it near-impossible to manage large blocks of content that involve having to scroll back up the page to apply formatting or insert images etc.

**Comment by gregorterrill** [comment]
To add to this - the toolbarFixed setting in Redactor config file doesn't work. Although I have noticed that (seemingly randomly) one of the toolbars will lock, overlapping the edit screen header (even if I scroll out of the Redactor field it remains - clicking anything in the toolbar pops me back up to that Redactor field):
![redactor-bug](https://user-images.githubusercontent.com/1774747/35686656-cc5d0c80-073a-11e8-8a25-2a44ff89fc48.jpeg)

**Comment by billythekid** [comment]
This is a real pain for some clients who post long bits of text to edit as we've shown them. Especially when editing the redactor config doesn't override Craft's settings. Why have the functionality to add settings at all if they're not observed.

Appears to be broken in Craft 2 and 3 (going by the Slack chat) but I suspect it was the "enhancement" in 2.6.3004 that's made it unusable.

**Comment by extiser** [comment]
Hi everyone! I had the same issue and a temporary fix can be made through CSS and connecting an executable file in the admen panel. Following is the code:

`.redactor-layer {
  z-index: 101 !important;
  border-top: 0 !important;
}
.input .redactor-toolbar {
  position: sticky !important;
  border-bottom: 1px solid #e3e5e8 !important;
  z-index: 102 !important;
  background: #fff !important;
}

.elementselectormodal {
  z-index: 1052 !important;
}`

**Comment by zizther** [comment]
@brandonkelly Just wanted to check if this issue was going to be fixed in C2, as well as C3.

**Comment by brandonkelly** [comment]
@zizther this issue only affects the Redactor plugin in Craft 3. The Rich Text field in Craft 2 supports the sticky toolbar.

**Comment by zizther** [comment]
@brandonkelly I and others, like @billythekid have noticed the same issue in Craft 2 as well

**Comment by ockam** [comment]
Just noticed it do work, but only at the mobile breakpoint. 
And it’s JS related, since `position:fixed`is injected on the element.

**Comment by andris-sevcenko** [comment]
@LukePeters What plugin version are you using?

**Comment by LukePeters** [comment]
@andris-sevcenko Redactor version 2.1.2, installed via the Plugin Store.

**Comment by andris-sevcenko** [comment]
@LukePeters is it possible to get access to the site where you're seeing this? If so, can you shoot it over email to support@craftcms.com and reference this issue?

**Comment by andris-sevcenko** [comment]
@LukePeters Thanks! Just released 2.1.3 which fixed this issue!

**Comment by lukeyouell** [comment]
@andris-sevcenko the sticky toolbar still doesn't work for me. I've tested this in the latest versions of Chrome, Firefox & Safari.

**Comment by mattandrews** [comment]
Me too I'm afraid, using 2.1.3.

**Comment by mattandrews** [comment]
I'm afraid I can't arrange that (corporate policies etc) but I just manually applied the changes in your fix [here](https://github.com/craftcms/redactor/commit/00876799a0a3adb84dfafeaed361a97fa0801079) and it looks like it's working!

**Comment by brandonkelly** [comment]
@mattandrews It's fixed for the next release (v2.1.4 probably), coming soon.

**Comment by KatieMFritz** [comment]
Still not working on single column layout.

**Comment by andris-sevcenko** [comment]
@KatieMFritz what Craft and Redactor versions are you using?

**Comment by mark-chief** [comment]
Experiencing this in craft Pro 3.3.15 and Redactor 2.4.0. Used in a Matrix field.

**Comment by RickKukiela** [comment]
I'm using latest craft and latest redactor from plugin store and "toolbarFixed": true does not work for me either :(

Also, I'm not sure if related or not, but also the "context" menu when clicking on a link will show up off screen, ie have to scroll up to see it, but it looks like nothing even happens when you click a link (Long content related).

**Comment by brandonkelly** [comment]
Working on my end, but seems to only kick in when the toolbar has gone up above the entire window, not just above the sticky page header.

**Comment by RickKukiela** [comment]
Yeah I'm not sure why but I just worked around the issue by using the CP CSS plugin and overriding the css for the toolbar to make it position: sticky and jump between the two top values for the two different media queries:
```
div.redactor-toolbar-wrapper {
	position: sticky !important;
	top: 60px !important;
    background: #fff;
    z-index: 11 !important;
}
@media screen and (max-width: 975px) {
	div.redactor-toolbar-wrapper {
		top: 114px !important;
	}
}
```

**Comment by brandonkelly** [comment]
@RickKukiela Make sure you’re running the latest versions of Craft and Redactor.
