### ISSUE TITLE
Make "imageUpload" works for the Redactor "image"

### ISSUE THREAD

**Issue by chanwhab** [craftcms/redactor#90]
"imageUpload" attribute is in redactor config
https://imperavi.com/redactor/docs/settings/image/#s-imageposition

Currently redactor field does not respect the setting, allowing access to all asset source.

**Comment by andris-sevcenko** [comment]
It is unlikely that this will ever be made to work.

It's more likely that eventually, Redactor fields will gain a setting similar to Asset fields (`Restrict uploads to a single folder`) which would also allow you to select a single folder, instead of an entire volume.
