### ISSUE TITLE
linkNewTab Option not showing when linking to Entries

### ISSUE THREAD

**Issue by pseudoclass** [craftcms/redactor#93]
I have included the "linkNewTab" option in my configs and it displays the "Open link in new tab" checkbox correctly when using the general "Insert Link" option however, this checkbox does not appear when using the "Link to an entry" or "Link to a category" options.

**Comment by andris-sevcenko** [comment]
We'd have to figure out the UI for that first (when selecting entries in Craft entry fields, there's no use for such checkbox).

**Comment by mateostabio** [comment]
Just bumped into this same exact issue. The blog I built uses a redactor field, I have in that redactor config file:  `"linkTarget": "_blank"`  but the links only open in a new tab if "Insert Link" was selected. If I select "Link to an Entry" it just opens the page in the same window.

I also tried adding `"linkNewTab": true` which gives me the open to open in new tab or not if I select "Insert Link" but still the same results as before with "Link to an Entry."

**Comment by andris-sevcenko** [comment]
The UI would have been messy, so, instead, we changed things a bit. Now the link modal is the one that Redactor uses, but it now has buttons that allow selecting an element that should be used for the URL. This allows the usage of the checkbox.

This has been implemented for the 2.7 release.

**Comment by brandonkelly** [comment]
Redactor 2.7.0 is out now with this change.
