### ISSUE TITLE
Bug when trying to link to internal entries inside a table

### ISSUE THREAD

**Issue by bowenfan32** [craftcms/redactor#98]
I'm trying to add a link to the words inside the second table cell as shown below: 
![screen shot 2018-10-19 at 2 53 08 pm](https://user-images.githubusercontent.com/14138692/47196910-ce143080-d3ae-11e8-99f1-3c382baf6e43.png)

However, if I link it to an entry, the first table cell's content will be cleared instead:
![screen shot 2018-10-19 at 2 56 11 pm](https://user-images.githubusercontent.com/14138692/47196982-29462300-d3af-11e8-8fdb-65324ca9da3f.png)

Currently I'm only able to link a single word that's not the first or the last in the sentence and write content from within the word I linked:
![screen shot 2018-10-19 at 2 58 59 pm](https://user-images.githubusercontent.com/14138692/47197054-86da6f80-d3af-11e8-97b7-637437a25eb8.png)

However this is not ideal for our client, so if this can be fixed in future release that'd be great.

**Comment by andris-sevcenko** [comment]
I can reproduce this on https://imperavi.com/redactor/plugins/table/ - even though there are no lists available in the plugin demo, I'm unable to create a link if I select all the text in a table cell.

This is Redactor Table plugin issue.

**Comment by bowenfan32** [comment]
P.S. We did some more data entry and found that this isn't restricted to Redactor Table or lists, but rather sentences separated by line breaks in general, hope this helps.
