### ISSUE TITLE
Missmatch between "norsk bokmål" craft languageid and redactor languageid

### ISSUE THREAD

**Issue by nettum** [craftcms/redactor#99]
In craft `Craft::$app->getLocale()->getLanguageID()` return `nb` if you set "norsk bokmål" as language. Redactor uses `no`:  
https://github.com/craftcms/redactor/blob/v2/lib/redactor/lang/no.js  
https://github.com/craftcms/redactor/blob/v2/src/assets/redactor/RedactorAsset.php#L47

The correct way to differentiate between "norsk bokmål" and "norsk nynorsk" according to ISO 639-1 is to use `nb` and `nn`. See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Should `/lib/redactor/lang/no.js` be renamed to `/lib/redactor/lang/nb.js`?

**Comment by brandonkelly** [comment]
@nettum Sorry, we overlooked that. We get those language files directly from Imperavi (maker of Redactor) so going to stick with their language IDs (`no` in this case). So instead the next release will just check if the current locale is `nb` or `nn` and if so, end up using Redactor’s `no.js` language file.

**Comment by nettum** [comment]
thanks! :+1:
